Decorate(ParameterSet ::= "<" Identifier__CSL ">") -> Sequence<SemanticParam>
	:= Decorate(Identifier__CSL);



Decorate(Identifier__CSL ::= IDENTIFIER) -> Sequence<SemanticParam>
	:= [(SemanticParam[name=TokenWorth(IDENTIFIER)])];
Decorate(Identifier__CSL ::= Identifier__CSL "," IDENTIFIER) -> Sequence<SemanticParam>
	:= [
		...Decorate(Identifier__CSL),
		(SemanticParam[name=TokenWorth(IDENTIFIER)]),
	];



Decorate(ArgumentSet ::= "<" ArgumentSet__0__CSL ">") -> Sequence<SemanticArg>
	:= Decorate(ArgumentSet__0__CSL);



Decorate(ArgumentSet__0__CSL ::= "+" IDENTIFIER) -> Sequence<SemanticArg>
	:= [(SemanticArg[name=TokenWorth(IDENTIFIER)][append=TRUE])];
Decorate(ArgumentSet__0__CSL ::= "-" IDENTIFIER) -> Sequence<SemanticArg>
	:= [(SemanticArg[name=TokenWorth(IDENTIFIER)][append=FALSE])];
Decorate(ArgumentSet__0__CSL ::= "?" IDENTIFIER) -> Sequence<SemanticArg>
	:= [(SemanticArg[name=TokenWorth(IDENTIFIER)][append=INHERIT])];
Decorate(ArgumentSet__0__CSL ::= ArgumentSet__0__CSL "," "+" IDENTIFIER) -> Sequence<SemanticArg>
	:= [
		...Decorate(ArgumentSet__0__CSL),
		(SemanticArg[name=TokenWorth(IDENTIFIER)][append=TRUE]),
	];
Decorate(ArgumentSet__0__CSL ::= ArgumentSet__0__CSL "," "-" IDENTIFIER) -> Sequence<SemanticArg>
	:= [
		...Decorate(ArgumentSet__0__CSL),
		(SemanticArg[name=TokenWorth(IDENTIFIER)][append=FALSE]),
	];
Decorate(ArgumentSet__0__CSL ::= ArgumentSet__0__CSL "," "?" IDENTIFIER) -> Sequence<SemanticArg>
	:= [
		...Decorate(ArgumentSet__0__CSL),
		(SemanticArg[name=TokenWorth(IDENTIFIER)][append=INHERIT]),
	];



Decorate(ConditionSet ::= "<" ConditionSet__0__CSL ">") -> Sequence<SemanticCondition>
	:= Decorate(ConditionSet__0__CSL);



Decorate(ConditionSet__0__CSL ::= IDENTIFIER "+") -> Sequence<SemanticCondition>
	:= [(SemanticCondition[name=TokenWorth(IDENTIFIER)][include=TRUE])];
Decorate(ConditionSet__0__CSL ::= IDENTIFIER "-") -> Sequence<SemanticCondition>
	:= [(SemanticCondition[name=TokenWorth(IDENTIFIER)][include=FALSE])];
Decorate(ConditionSet__0__CSL ::= ConditionSet__0__CSL "," IDENTIFIER "+") -> Sequence<SemanticCondition>
	:= [
		...Decorate(ConditionSet__0__CSL),
		(SemanticCondition[name=TokenWorth(IDENTIFIER)][include=TRUE]),
	];
Decorate(ConditionSet__0__CSL ::= ConditionSet__0__CSL "," IDENTIFIER "-") -> Sequence<SemanticCondition>
	:= [
		...Decorate(ConditionSet__0__CSL),
		(SemanticCondition[name=TokenWorth(IDENTIFIER)][include=FALSE]),
	];



Decorate(Reference ::= IDENTIFIER) -> SemanticRef
	:= (SemanticRef[name=TokenWorth(IDENTIFIER)]);
Decorate(Reference ::= Reference ArgumentSet) -> SemanticRef
	:= (SemanticRef[name=Decorate(Reference).name]
		Decorate(Reference)
		...Decorate(ArgumentSet)
	);



Decorate(Unit ::= CHAR_CODE) -> SemanticConst
	:= (SemanticConst[value=CHAR_CODE.source]);
Decorate(Unit ::= STRING) -> SemanticConst
	:= (SemanticConst[value=STRING.source]);
Decorate(Unit ::= CHAR_CLASS) -> SemanticConst
	:= (SemanticConst[value=CHAR_CLASS.source]);
Decorate(Unit ::= Reference) -> SemanticRef
	:= Decorate(Reference);
Decorate(Unit ::= "(" Definition ")") -> SemanticExpr
	:= Decorate(Definition);



Decorate(Unary ::= Unit) -> SemanticExpr
	:= Decorate(Unit);
Decorate(Unary ::= Unit "+") -> SematicOp
	:= (SematicOp[operator=PLUS]
		Decorate(Unit)
	);
Decorate(Unary ::= Unit "*") -> SematicOp
	:= (SematicOp[operator=OPT]
		(SemanticOp[operator=PLUS]
			Decorate(Unit)
		)
	);
Decorate(Unary ::= Unit "#") -> SematicOp
	:= (SematicOp[operator=HASH]
		Decorate(Unit)
	);
Decorate(Unary ::= Unit "?") -> SematicOp
	:= (SematicOp[operator=OPT]
		Decorate(Unit)
	);
Decorate(Unary ::= Unit "+" "?") -> SematicOp
	:= (SematicOp[operator=OPT]
		(SemanticOp[operator=PLUS]
			Decorate(Unit)
		)
	);
Decorate(Unary ::= Unit "*" "?") -> SematicOp
	:= (SematicOp[operator=OPT]
		(SematicOp[operator=OPT]
			(SemanticOp[operator=PLUS]
				Decorate(Unit)
			)
		)
	);
Decorate(Unary ::= Unit "#" "?") -> SematicOp
	:= (SematicOp[operator=OPT]
		(SemanticOp[operator=HASH]
			Decorate(Unit)
		)
	);



Decorate(Item ::= Unary) -> SemanticExpr
	:= Decorate(Unary);
Decorate(Item ::= ConditionSet Item) -> SemanticItem
	:= (SemanticItem
		Decorate(Item)
		...Decorate(ConditionSet)
	);


Decorate(Order ::= Item) -> SemanticExpr
	:= Decorate(Item);
Decorate(Order ::= Order "."? Item) -> SematicOp
	:= (SematicOp[operator=ORDER]
		Decorate(Order)
		Decorate(Item)
	);



Decorate(Concat ::= Order) -> SemanticExpr
	:= Decorate(Order);
Decorate(Concat ::= Concat "&" Order) -> SematicOp
	:= (SematicOp[operator=CONCAT]
		Decorate(Concat)
		Decorate(Order)
	);



Decorate(Altern ::= Concat) -> SemanticExpr
	:= Decorate(Concat);
Decorate(Altern ::= Altern "|" Concat) -> SematicOp
	:= (SematicOp[operator=ALTERN]
		Decorate(Altern)
		Decorate(Concat)
	);



Decorate(Definition ::= Altern) -> SemanticExpr
	:= Decorate(Altern);



Decorate(NonterminalName ::= IDENTIFIER) -> SemanticNonterminal
	:= (SemanticNonterminal[name=TokenWorth(IDENTIFIER)]);
Decorate(NonterminalName ::= NonterminalName ParameterSet) -> SemanticNonterminal
	:= (SemanticNonterminal[name=Decorate(NonterminalName).name]
		Decorate(NonterminalName)
		...Decorate(ParameterSet)
	);



Decorate(Production ::= NonterminalName (":::=" | "::=") "|"? Definition ";") -> SemanticProduction
	:= (SemanticProduction
		Decorate(NonterminalName)
		Decorate(Definition)
	);



Decorate(Goal ::= #x02 #x03) -> SemanticGoal
	:= (SemanticGoal);
Decorate(Goal ::= #x02 Production__List #x03) -> SemanticGoal
	:= (SemanticGoal
		...Decorate(Production__List)
	);



Decorate(Production__List ::= Production) -> Sequence<SemanticProduction>
	:= [Decorate(Production)];
Decorate(Production__List ::= Production__List Production) -> Sequence<SemanticProduction>
	:= [
		...Decorate(Production__List),
		...Decorate(Production),
	];
