SemanticExpr =:=
	| SemanticConst
	| SemanticRef
	| SemanticItem
	| SemanticOp
;

Text =:= Sequence<RealNumber>;



SemanticParam[name: Text]
	::= ();

SemanticArg[name: Text, append: TRUE | FALSE | INHERIT | NOTINHERIT]
	::= ();

SemanticCondition[name: Text, include: TRUE | FALSE]
	::= ();



SemanticConst[value: Text]
	::= ();

SemanticRef[name: Text] ::=
	| ()
	| SemanticRef SemanticArg*
;

SemanticItem
	::= SemanticExpr SemanticCondition*;

SemanticOp[operator: PLUS | HASH | OPT]
	::= SemanticExpr;
SemanticOp[operator: SEQ | UNSEQ | UNCHOICE | CHOICE]
	::= SemanticExpr SemanticExpr;



SemanticNonterminal[name: Text] ::=
	| ()
	| SemanticNonterminal SemanticParam*
;

SemanticProduction
	::= SemanticNonterminal SemanticExpr;

SemanticGoal
	::= SemanticProduction*;
