/*
# Conventions

- «Value» refers to an IR value (a value on the conceptual stack).
- «Number», «Integer», «Natural», «Float», etc. all refer to IR values that are of those respective types. Their types are given by semantic analysis on the AST.
- Types starting with «TYPE.» and «VALUE.» refer to Counterpoint Language types and values respectively.
- Native types are referred to by «native-number», «native-bigint», and «native-string».

IR functions may have zero or more static parameters and consume zero or more dynamic arguments from the stack.
They may return one value back to the stack, or none at all.

Every function signature takes the form «‹NAME›(‹static params› [‹dynamic params›]) -> ‹return›;», where:
- ‹NAME› is an uppercase function name, optionally containg dots
- ‹static params› is a space-separated list of types representing statically known values
- ‹dynamic params› is a space-separated list of types representing dynamic IR values on the stack
- consecutive multiples of the same type «T» can be written as «T*» in shorthand
- « -> ‹return›» is optional — it means the function does not return a value.
*/



TRAP();

NULL.CONST (VALUE.Null)    -> Value;
BOOL.CONST (VALUE.Boolean) -> Value;
SYM.CONST  (VALUE.Symbol)  -> Value;
INT.CONST  (VALUE.Integer) -> Value;
NAT.CONST  (VALUE.Natural) -> Value;
FLOAT.CONST(VALUE.Float)   -> Value;
STR.CONST  (VALUE.String)  -> Value;

GET(SymbolSchemaVar|native-string) -> Value;

STR.TEMPLATE([Value*]) -> String;

TUPLE.NEW([Value*])                       -> Tuple;
RECORD.NEW(Vector<native-bigint, Value>*) -> Record;
LIST.NEW([Value*])                        -> List;
DICT.NEW(Vector<VALUE.Symbol, Value>*)    -> Dict;
SET.NEW([Value*])                         -> Set;
MAP.NEW(Vector<Value, Value>*)            -> Map;
MAYBE.NEW(Value?)                         -> Maybe;

TUPLE.GET (native-bigint [Value]) -> Value;
RECORD.GET(native-bigint [Value]) -> Value;
LIST.GET([Value Value])           -> Value;
DICT.GET([Value Value])           -> Value;
SET.GET ([Value Value])           -> Value;
MAP.GET ([Value Value])           -> Value;

MAYBE.UNWRAP([Value]) -> Value;

CALL([Value*]) -> Value;

ISSET (SymbolSchemaVar|native-string) -> Boolean;
ISNULL([Value])                       -> Boolean;
ISNONE([Value])                       -> Boolean;

NOT([Value])   -> Boolean;
EMP([Value])   -> Boolean;
NEG([Integer]) -> Integer;
NEG([Natural]) -> Natural;
NEG([Float])   -> Float;
NEG([Number])  -> Number;

BOOL.FROM([Value])   -> Boolean;
INT.FROM([Number])   -> Integer;
NAT.FROM([Number])   -> Natural;
FLOAT.FROM([Number]) -> Float;
STR.FROM([Value])    -> String;

LIST.COUNT([Value]) -> Natural;
DICT.COUNT([Value]) -> Natural;
SET.COUNT([Value])  -> Natural;
MAP.COUNT([Value])  -> Natural;

INT.ADD([Integer Integer]) -> Integer;
INT.SUB([Integer Integer]) -> Integer;
INT.MUL([Integer Integer]) -> Integer;
INT.DIV([Integer Integer]) -> Integer;
INT.EXP([Integer Integer]) -> Integer;

NAT.ADD([Natural Natural]) -> Natural;
NAT.SUB([Natural Natural]) -> Natural;
NAT.MUL([Natural Natural]) -> Natural;
NAT.DIV([Natural Natural]) -> Natural;
NAT.EXP([Natural Natural]) -> Natural;

FLOAT.ADD([Float Float]) -> Float;
FLOAT.SUB([Float Float]) -> Float;
FLOAT.MUL([Float Float]) -> Float;
FLOAT.DIV([Float Float]) -> Float;
FLOAT.EXP([Float Float]) -> Float;

LT([Number Number]) -> Boolean;
GT([Number Number]) -> Boolean;
LE([Number Number]) -> Boolean;
GE([Number Number]) -> Boolean;

ID([Value Value]) -> Boolean;
EQ([Value Value]) -> Boolean;

DROP([Value]);

DECL(SymbolSchemaVar|native-string Type [Value?]);
SET (SymbolSchemaVar|native-string      [Value?]);

LIST.SET([Value Value Value]);
DICT.SET([Value Value Value]);
SET.SET ([Value Value Value]);
MAP.SET ([Value Value Value]);

LIST.COPY([Value Value]);
DICT.COPY([Value Value]);
SET.COPY ([Value Value]);
MAP.COPY ([Value Value]);






Build(Null    n) := (NULL.CONST  n);
Build(Boolean b) := (BOOL.CONST  b);
Build(Symbol  s) := (SYM.CONST   s);
Build(Integer i) := (INT.CONST   i);
Build(Natural n) := (NAT.CONST   n);
Build(Float   f) := (FLOAT.CONST f);
Build(String  s) := (STR.CONST   s);

Build(SemanticProperty prop) := Sequence [`Symbol(prop.0)`, `Build(prop.1)`];
Build(SemanticCase     case) := Sequence [`Build(case.0)`, `Build(case.1)`];

Build(SemanticExpressionConstant[value: VALUE.Null]    const) := `Build(const.value)`;
Build(SemanticExpressionConstant[value: VALUE.Boolean] const) := `Build(const.value)`;
Build(SemanticExpressionConstant[value: VALUE.Symbol]  const) := `Build(const.value)`;
Build(SemanticExpressionConstant[value: VALUE.Integer] const) := `Build(const.value)`;
Build(SemanticExpressionConstant[value: VALUE.Natural] const) := `Build(const.value)`;
Build(SemanticExpressionConstant[value: VALUE.Float]   const) := `Build(const.value)`;
Build(SemanticExpressionConstant[value: VALUE.String]  const) := `Build(const.value)`;

Build(SemanticExpressionTemplate tpl) := (STR.TEMPLATE `...tpl.children.map(Build)`);

Build(SemanticExpressionVariable var) := (GET `GetSymbolSchema(var)`);

Build(SemanticExpressionTuple tup)  := (TUPLE.NEW  [`...tup.children.map(Build)`]);
Build(SemanticExpressionRecord rec) := (RECORD.NEW `...rec.children.map(Sequence [prop.0.id, Build(prop.1)])`);
Build(SemanticExpressionList list)  := (LIST.NEW   [`...list.children.map(Build)`]);
Build(SemanticExpressionDict dict)  := (DICT.NEW   `...dict.children.flatMap(Build)`);
Build(SemanticExpressionSet set)    := (SET.NEW    [`...set.children.map(Build)`]);
Build(SemanticExpressionMap map)    := (MAP.NEW    `...map.children.map(Build)`);

Build(SemanticExpressionAccess[kind=NORMAL] ::= SemanticExpression SemanticIndex) := (TUPLE.GET  `SemanticIndex.index` [`Build(SemanticExpression)`]);
Build(SemanticExpressionAccess[kind=NORMAL] ::= SemanticExpression SemanticKey)   := (RECORD.GET `SemanticKey.id`      [`Build(SemanticExpression)`]);
Build(SemanticExpressionAccess[kind=NORMAL] ::= SemanticExpression__0[type: TYPE.List] SemanticExpression__1) := (LIST.GET [`Build(SemanticExpression__0)` `Build(SemanticExpression__1)`]);
Build(SemanticExpressionAccess[kind=NORMAL] ::= SemanticExpression__0[type: TYPE.Dict] SemanticExpression__1) := (DICT.GET [`Build(SemanticExpression__0)` `Build(SemanticExpression__1)`]);
Build(SemanticExpressionAccess[kind=NORMAL] ::= SemanticExpression__0[type: TYPE.Set]  SemanticExpression__1) := (SET.GET  [`Build(SemanticExpression__0)` `Build(SemanticExpression__1)`]);
Build(SemanticExpressionAccess[kind=NORMAL] ::= SemanticExpression__0[type: TYPE.Map]  SemanticExpression__1) := (MAP.GET  [`Build(SemanticExpression__0)` `Build(SemanticExpression__1)`]);

Build(SemanticExpressionBlock blex) := [
	...`blex.0.SemanticStatement.slice(0, 1).map(Build)`
	return `Build(blex.0.-1.SemanticExpression)`.
];

Build(SemanticExpressionAccess[kind=MAYBE] access) := [
	(DECL ‹type› $base `Build(access.0)`)
	(DECL ‹type› $result)
	(GOTO.IF (ISNONE (GET $base)) "then" "else")
	"then":
	(SET $result (MAYBE.NEW))
	(GOTO "endif")
	"else":
	(SET $result (MAYBE.NEW `Build(access[kind=NORMAL] ::= (MAYBE.UNWRAP (GET $base)) access.1)`))
	(GOTO "endif")
	"endif":
	return (GET $result).
];

Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Boolean"):has(SemanticExpression*) call) := (BOOL.FROM  `Build(call.SemanticExpression*.0)`);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Integer"):has(SemanticExpression*) call) := (INT.FROM   `Build(call.SemanticExpression*.0)`);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Natural"):has(SemanticExpression*) call) := (NAT.FROM   `Build(call.SemanticExpression*.0)`);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Float")  :has(SemanticExpression*) call) := (FLOAT.FROM `Build(call.SemanticExpression*.0)`);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "String") :has(SemanticExpression*) call) := (STR.FROM   `Build(call.SemanticExpression*.0)`);

Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "List") call) := (LIST.NEW);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Dict") call) := (DICT.NEW);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Set")  call) := (SET.NEW);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Map")  call) := (MAP.NEW);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "None") call) := (MAYBE.NEW);
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "List"):has(SemanticExpression*) call) := [
	(DECL <List> $destination (LIST.NEW))
	(DECL ‹type› $arg `Build(call.SemanticExpression*.0)`)
	(LIST.COPY (GET $destination) (GET $arg))
	return (GET $destination).
];
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Dict"):has(SemanticExpression) call) := [
	(DECL <Dict> $destination (DICT.NEW))
	(DECL ‹type› $arg `Build(call.SemanticExpression*.0)`)
	(DICT.COPY (GET $destination) (GET $arg))
	return (GET $destination).
];
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Set"):has(SemanticExpression*) call) := [
	(DECL <Set> $destination (SET.NEW))
	(DECL ‹type› $arg `Build(call.SemanticExpression*.0)`)
	(SET.COPY (GET $destination) (GET $arg))
	return (GET $destination).
];
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Map"):has(SemanticExpression*) call) := [
	(DECL <Map> $destination (MAP.NEW))
	(DECL ‹type› $arg `Build(call.SemanticExpression*.0)`)
	(MAP.COPY (GET $destination) (GET $arg))
	return (GET $destination).
];
Build(SemanticExpressionCall:has(SemanticExpressionVariable ::= "Some"):has(SemanticExpression*) call) := (MAYBE.NEW `Build(call.SemanticExpression*.0)`);
Build(SemanticExpressionCall call) := (CALL [`Build(call.0)` `...call.SemanticExpression*.map(Build)`]);

Build(SemanticExpressionClaim claim) := Build(claim.0);

Build(SemanticExpressionIsset ::= SemanticExpressionVariable) := (ISSET `GetSymbolSchema(SemanticExpressionVariable)`);
Build(SemanticExpressionIsset ::= SemanticExpressionAccess)   := (ISNULL `Build(SemanticExpressionAccess)`);

Build(SemanticExpressionOperation[operator=UN_MAYBE]  ::= SemanticExpression)               := (MAYBE.UNWRAP [`Build(SemanticExpression)`]);
Build(SemanticExpressionOperation[operator=UN_RESULT] ::= SemanticExpression)               := TODO:;
Build(SemanticExpressionOperation[operator=NOT]       ::= SemanticExpression)               := (NOT [`Build(SemanticExpression)`]);
Build(SemanticExpressionOperation[operator=EMP]       ::= SemanticExpression)               := (EMP [`Build(SemanticExpression)`]);
Build(SemanticExpressionOperation[operator=NEG]       ::= SemanticExpression[type: Number]) := (NEG [`Build(SemanticExpression)`]);

Build(SemanticExpressionOperation[operator=ADD][0: Integer][1: Integer] op) := (INT.ADD [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=SUB][0: Integer][1: Integer] op) := (INT.SUB [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=MUL][0: Integer][1: Integer] op) := (INT.MUL [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=DIV][0: Integer][1: Integer] op) := (INT.DIV [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=EXP][0: Integer][1: Integer] op) := (INT.EXP [`Build(op.0)` `Build(op.1)`]);

Build(SemanticExpressionOperation[operator=ADD][0: Natural][1: Natural] op) := (NAT.ADD [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=SUB][0: Natural][1: Natural] op) := (NAT.SUB [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=MUL][0: Natural][1: Natural] op) := (NAT.MUL [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=DIV][0: Natural][1: Natural] op) := (NAT.DIV [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=EXP][0: Natural][1: Natural] op) := (NAT.EXP [`Build(op.0)` `Build(op.1)`]);

Build(SemanticExpressionOperation[operator=ADD][0: Float][1: Float] op) := (FLOAT.ADD [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=SUB][0: Float][1: Float] op) := (FLOAT.SUB [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=MUL][0: Float][1: Float] op) := (FLOAT.MUL [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=DIV][0: Float][1: Float] op) := (FLOAT.DIV [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=EXP][0: Float][1: Float] op) := (FLOAT.EXP [`Build(op.0)` `Build(op.1)`]);

Build(SemanticExpressionOperation[operator=LT][0: Number][1: Number] op) := (LT  [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=GT][0: Number][1: Number] op) := (GT  [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=LE][0: Number][1: Number] op) := (LE  [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=GE][0: Number][1: Number] op) := (GE  [`Build(op.0)` `Build(op.1)`]);

Build(SemanticExpressionOperation[operator=ID] op) := (ID  [`Build(op.0)` `Build(op.1)`]);
Build(SemanticExpressionOperation[operator=EQ] op) := (EQ  [`Build(op.0)` `Build(op.1)`]);


Build(SemanticExpressionOperation[operator=AND] op) := [
	(DECL ‹type› $left `Build(op.0)`)
	(DECL ‹type› $result)
	(GOTO.IF (BOOL.FROM (GET $left)) "then" "else")
	"then":
	(SET $result `Build(op.1)`)
	(GOTO "endif")
	"else":
	(SET $result (GET $left))
	(GOTO "endif")
	"endif":
	return (GET $result).
];

Build(SemanticExpressionOperation[operator=OR] op) := [
	(DECL ‹type› $left `Build(op.0)`)
	(DECL ‹type› $result)
	(GOTO.IF (BOOL.FROM (GET $left)) "then" "else")
	"then":
	(SET $result (GET $left))
	(GOTO "endif")
	"else":
	(SET $result `Build(op.1)`)
	(GOTO "endif")
	"endif":
	return (GET $result).
];

Build(SemanticExpressionOperation[operator=COND] op) := [
	(DECL ‹type› $result)
	(GOTO.IF `Build(op.0)` "then" "else")
	"then":
	(SET $result `Build(op.1)`)
	(GOTO "endif")
	"else":
	(SET $result `Build(op.2)`)
	(GOTO "endif")
	"endif":
	return (GET $result).
];

Build(SemanticExpressionSwitch ::= SemanticExpression__0 (SemanticCase ::= SemanticExpression__1+ SemanticExpression__2)* SemanticExpression__3) := [
	(DECL ‹type› $result)
	(GOTO.IF (ID `Build(SemanticExpression__0)` `Build(SemanticCase*[i].children[j])`) "then" "else")
	"then":
	(SET $result `Build(SemanticCase*[i].children.-1)`)
	(GOTO "endif")
	"else":
	(SET $result `Build(SemanticExpressionSwitch ::= SemanticExpression__0 (SemanticCase ::= SemanticExpression__1.slice(1)+ SemanticExpression__2)* SemanticExpression__3)`)
	(GOTO "endif")
	"endif":
	return (GET $result).
];
Build(SemanticExpressionSwitch ::= SemanticExpression__0 (SemanticCase ::= SemanticExpression__1 SemanticExpression__2)* SemanticExpression__3) := [
	(DECL ‹type› $result)
	(GOTO.IF (ID `Build(SemanticExpression__0)` `Build(SemanticCase*[i].children.0)`) "then" "else")
	"then":
	(SET $result `Build(SemanticCase*[i].children.1)`)
	(GOTO "endif")
	"else":
	(SET $result `Build(SemanticExpressionSwitch ::= SemanticExpression__0 SemanticCase.slice(1)* SemanticExpression__3)`)
	(GOTO "endif")
	"endif":
	return (GET $result).
];
Build(SemanticExpressionSwitch ::= SemanticExpression__0 SemanticExpression__1) := [
	(DROP `Build(SemanticExpression__0)`)
	return `Build(SemanticExpression__1)`.
];

Build(SemanticDeclarationType decl) := [];

Build(SemanticDeclarationVariable[id: RealNumber][writable: Boolean] ::= SemanticType? SemanticExpression) := [
	(DECL ‹type› `GetSymbolSchema(id)` `Build(SemanticExpression)`)
];
Build(SemanticDeclarationVariable[writable=false] ::= SemanticType? SemanticExpression) := [
	(DROP `Build(SemanticExpression)`)
];
Build(SemanticDeclarationVariable[id: RealNumber][writable=true] ::= SemanticType) := [
	(DECL ‹type› `GetSymbolSchema(id)` (MAYBE.NEW))
];

Build(SemanticStatementExpression:has(SemanticExpression) stmt) := [
	(DROP `Build(stmt.0)`)
];
Build(SemanticStatementExpression stmt) := [];

Build(SemanticStatementClaim stmt) := [
	(DROP `Build(stmt.0)`)
];

Build(SemanticStatementReassignment ::= SemanticExpressionVariable:of(SymbolSchemaVar[isUninitialized=false]) SemanticExpression) := [
	(SET `GetSymbolSchema(SemanticExpressionVariable)` `Build(SemanticExpression)`)
];
Build(SemanticStatementReassignment ::= SemanticExpressionVariable:of(SymbolSchemaVar[isUninitialized=true]) SemanticExpression) := [
	(SET `GetSymbolSchema(SemanticExpressionVariable)` (MAYBE.NEW `Build(SemanticExpression)`))
];
Build(SemanticStatementReassignment ::= (SemanticExpressionAccess ::= SemanticExpression[type: TYPE.List] SemanticExpression) SemanticExpression) := (LIST.SET [`Build(SemanticExpressionAccess.0)` `Build(SemanticExpressionAccess.1)` `Build(SemanticExpression)`]);
Build(SemanticStatementReassignment ::= (SemanticExpressionAccess ::= SemanticExpression[type: TYPE.Dict] SemanticExpression) SemanticExpression) := (DICT.SET [`Build(SemanticExpressionAccess.0)` `Build(SemanticExpressionAccess.1)` `Build(SemanticExpression)`]);
Build(SemanticStatementReassignment ::= (SemanticExpressionAccess ::= SemanticExpression[type: TYPE.Set]  SemanticExpression) SemanticExpression) := (SET.SET  [`Build(SemanticExpressionAccess.0)` `Build(SemanticExpressionAccess.1)` `Build(SemanticExpression)`]);
Build(SemanticStatementReassignment ::= (SemanticExpressionAccess ::= SemanticExpression[type: TYPE.Map]  SemanticExpression) SemanticExpression) := (MAP.SET  [`Build(SemanticExpressionAccess.0)` `Build(SemanticExpressionAccess.1)` `Build(SemanticExpression)`]);
Build(SemanticStatementReassignment ::= SemanticExpressionVariable) := [
	(SET `GetSymbolSchema(SemanticExpressionVariable)` (MAYBE.NEW))
];
Build(SemanticStatementReassignment ::= SemanticExpressionAccess); // TODO: object/interface support

Build(SemanticStatementConditional[unless=false] ::= SemanticExpression SemanticBlock) := [
	(GOTO.IF `Build(SemanticExpression)` "then" "endif")
	"then":
	...`Build(SemanticBlock)`
	(GOTO "endif")
	"endif":
];
Build(SemanticStatementConditional[unless=true] ::= SemanticExpression SemanticBlock) := [
	(GOTO.IF (NOT `Build(SemanticExpression)`) "then" "endif")
	"then":
	...`Build(SemanticBlock)`
	(GOTO "endif")
	"endif":
];
Build(SemanticStatementConditional[unless=false] ::= SemanticExpression SemanticBlock__0 SemanticBlock__1) := [
	(GOTO.IF `Build(SemanticExpression)` "then" "else")
	"then":
	...`Build(SemanticBlock__0)`
	(GOTO "endif")
	"else":
	...`Build(SemanticBlock__1)`
	(GOTO "endif")
	"endif":
];
Build(SemanticStatementConditional[unless=false] ::= SemanticExpression SemanticBlock SemanticStatementConditional) := [
	(GOTO.IF `Build(SemanticExpression)` "then" "else")
	"then":
	...`Build(SemanticBlock)`
	(GOTO "endif")
	"else":
	...`Build(SemanticStatementConditional)`
	(GOTO "endif")
	"endif":
];

Build(SemanticStatementLoop[doFirst=false][until=false] ::= SemanticExpression SemanticBlock) := [
	(GOTO "while")
	"while":
	(GOTO.IF `Build(SemanticExpression)` "do" "endwhile")
	"do":
	...`Build(SemanticBlock)`
	(GOTO "while")
	"endwhile":
];
Build(SemanticStatementLoop[doFirst=false][until=true] ::= SemanticExpression SemanticBlock) := [
	(GOTO "while")
	"while":
	(GOTO.IF (NOT `Build(SemanticExpression)`) "do" "endwhile")
	"do":
	...`Build(SemanticBlock)`
	(GOTO "while")
	"endwhile":
];
Build(SemanticStatementLoop[doFirst=true][until=false] ::= SemanticExpression SemanticBlock) := [
	(GOTO "do")
	"do":
	...`Build(SemanticBlock)`
	(GOTO "while")
	"while":
	(GOTO.IF `Build(SemanticExpression)` "do" "endwhile")
	"endwhile":
];
Build(SemanticStatementLoop[doFirst=true][until=true] ::= SemanticExpression SemanticBlock) := [
	(GOTO "do")
	"do":
	...`Build(SemanticBlock)`
	(GOTO "while")
	"while":
	(GOTO.IF (NOT `Build(SemanticExpression)`) "do" "endwhile")
	"endwhile":
];

Build(SemanticStatementIteration[id: RealNumber] ::= SemanticType SemanticExpression SemanticBlock) := [
	(DECL <List> $iterable `Build(SemanticExpression)`)
	(DECL <nat> $index (NAT.CONST +0))
	(GOTO "while")
	"while":
	(GOTO.IF (LT (GET $index) (LIST.COUNT (GET $iterable))) "do" "endwhile")
	"do":
	(DECL ‹type› `GetSymbolSchema(id)` (LIST.GET (GET $iterable) (GET $index)))
	...`Build(SemanticBlock)`
	(SET $index (NAT.ADD (GET $index) (NAT.CONST +1)))
	(GOTO "while")
	"endwhile":
];
Build(SemanticStatementIteration ::= SemanticType SemanticExpression SemanticBlock) := [
	(DECL <List> $iterable `Build(SemanticExpression)`)
	(DECL <nat> $index (NAT.CONST +0))
	(GOTO "while")
	"while":
	(GOTO.IF (LT (GET $index) (LIST.COUNT (GET $iterable))) "do" "endwhile")
	"do":
	...`Build(SemanticBlock)`
	(SET $index (NAT.ADD (GET $index) (NAT.CONST +1)))
	(GOTO "while")
	"endwhile":
];

Build(SemanticStatementBreak[skip=false] stmt) := [ (GOTO "endwhile") ];
Build(SemanticStatementBreak[skip=true]  stmt) := [ (GOTO "while") ];

Build(SemanticBlock block) := block.children.map(Build);

Build(SemanticGoal goal) := [
	"start":
	`Build(goal.0)`
];



SymbolSchemaVar GetSymbolSchema(SemanticExpressionVariable var) :=
	1. *Assert:* the validator’s symbol table contains a SymbolSchemaVar `symbol` whose `id` is `var.id`.
	2. *Return:* `symbol`.
;
