Sequence<Instruction> Build(Null n) :=
	1. *Return:* ["Push `0` onto the operand stack."].
;

Sequence<Instruction> Build(Boolean b) :=
	1. *If* `b` is `true`:
		1. *Return:* ["Push `1` onto the operand stack."].
	2. *Assert:* `b` is `false`.
	3. *Return:* ["Push `0` onto the operand stack."].
;

Sequence<Instruction> Build(Number n) :=
	1. *Return:* ["Push `n` onto the operand stack."].
;



Sequence<Instruction> Build(SemanticExpression expr) :=
	1. *Let* `assess` be `Assess(expr)`.
	2. *If* `assess` is an abrupt completion:
		1. *Return:* `BuildExpression(expr)`.
	3. *Assert:* `assess.value` exists.
	4. *Return:* `Build(assess.value)`.
;



Sequence<Instruction> Build(SemanticStatementExpression stmt) :=
	1. *Let* `sequence` be an empty sequence of `Instruction`s.
	2. *If* `stmt.children.count` is greater than 0:
		1. *Set* `sequence` to *UnwrapAffirm:* `Build(stmt.children.0)`.
	3. *Return:* `sequence`.
;



Sequence<Instruction> Build(SemanticDeclaration decl) :=
	// TO BE DETERMINED
;

Sequence<Instruction> Build(SemanticAssignment assign) :=
	// TO BE DETERMINED
;



Sequence<Instruction> Build(SemanticGoal goal) :=
	1. *Let* `sequence` be an empty sequence of `Instruction`s.
	2. For each `SemanticStatment stmt` in `goal.children`:
		1. *Let* `instrs` be *UnwrapAffirm:* `Build(stmt)`.
		2. Push `...instrs` to `sequence`.
	3. *Return:* `sequence`.
;



Sequence<Instruction> BuildExpression(SemanticConstant const) :=
	1. *Let* `assess` be *UnwrapAffirm:* `Assess(const)`.
	2. *Return:* `Build(assess)`.
;



Sequence<Instruction> BuildExpression(SemanticVariable var) :=
	// TO BE DETERMINED
;



Sequence<Instruction> BuildExpression(SemanticTemplate tpl) :=
	// TO BE DETERMINED
;



Sequence<Instruction> BuildExpression(SemanticOperation[operator: NOT | EMP | NEG] expr) :=
	1. *Assert:* `expr.children.count` is 1.
	2. *Let* `instrs` be *UnwrapAffirm:* `Build(expr.children.0)`.
	3. *Return:* [
		...instrs,
		"`expr.operator`",
	].
;

Sequence<Instruction> BuildExpression(SemanticOperation[operator: EXP | MUL | DIV | ADD | LT | GT | LE | GE | IS | EQ] expr) :=
	1. *Let* `builds` be *UnwrapAffirm:* `PrebuildSemanticOperationBinary(expr)`.
	2. *Return:* [
		...builds.0,
		...builds.1,
		"`expr.operator`",
	].
;

Sequence<Instruction> BuildExpression(SemanticOperation[operator: AND] expr) :=
	1. *Let* `builds` be *UnwrapAffirm:* `PrebuildSemanticOperationBinary(expr)`.
	2. *Return:* [
		...builds.1,
		...builds.0,
		"TEE the local variable `operand0`.",
		"GET the local variable `operand0`.",
		"NOT",
		"NOT",
		"SELECT",
	].
;

Sequence<Instruction> BuildExpression(SemanticOperation[operator: OR] expr) :=
	1. *Let* `builds` be *UnwrapAffirm:* `PrebuildSemanticOperationBinary(expr)`.
	2. *Return:* [
		...builds.0,
		"TEE the local variable `operand0`.",
		...builds.1,
		"GET the local variable `operand0`.",
		"NOT",
		"NOT",
		"SELECT",
	].
;

Sequence<Instruction> BuildExpression(SemanticOperation[operator: COND] expr) :=
	1. *Assert:* `expr.children.count` is 3.
	2. *Let* `instrs0` be *UnwrapAffirm:* `Build(expr.children.0)`.
	3. *Let* `instrs1` be *UnwrapAffirm:* `Build(expr.children.1)`.
	4. *Let* `instrs2` be *UnwrapAffirm:* `Build(expr.children.2)`.
	5. *Return:* [
		...instrs0,
		"IF",
		...instrs1,
		"ELSE",
		...instrs2,
		"END",
	].
;



// Prepares instructions for a binary operation.
Sequence<Sequence<Instruction>, Sequence<Instruction>> PrebuildSemanticOperationBinary(SemanticOperation expr) :=
	1. *Assert:* `expr.children.count` is 2.
	2. *Let* `instrs0` be *UnwrapAffirm:* `Build(expr.children.0)`.
	3. *Let* `instrs1` be *UnwrapAffirm:* `Build(expr.children.1)`.
	4. *Return:* [instrs0, instrs1].
;
