CompletionKind =:=
	| NORMAL
	| BREAK_OR_SKIP
	| RETURN_OR_THROW
;



CompletionKind CompletionOf(Or<
	SemanticIndex,
	SemanticKey,
	SemanticItemType,
	SemanticPropertyType,
	SemanticParameterFunction,
	SemanticType,
> node)
	:= NORMAL;



CompletionKind CompletionOf(Sequence<SemanticExpression> exprs) :=
	1. *Let* `completions` be a mapping of `exprs` for each `SemanticExpression` to *UnwrapAffirm:* `CompletionOf(SemanticExpression)`.
	2. *Return:* `MaximumCompletion(completions)`.
;

CompletionKind CompletionOf(Sequence<SemanticProperty> props) :=
	1. *Let* `completions` be a mapping of `props` for each `SemanticProperty` to *UnwrapAffirm:* `CompletionOf(SemanticProperty)`.
	2. *Return:* `MaximumCompletion(completions)`.
;



CompletionKind CompletionOf(SemanticProperty ::= SemanticKey SemanticExpression)
	:= CompletionOf(SemanticExpression);

CompletionKind CompletionOf(SemanticCase ::= SemanticExpression+ SemanticExpression)
	:= CompletionOf([...SemanticExpression+, SemanticExpression]);

CompletionKind CompletionOf(SemanticBlock ::= SemanticStatement+) :=
	1. *Let* `completions` be a mapping of `SemanticStatement+` for each `SemanticStatement` to *UnwrapAffirm:* `CompletionOf(SemanticStatement)`.
	2. *Return:* `MaximumCompletion(completions)`.
;

CompletionKind CompletionOf(SemanticGoal ::= ())
	:= NORMAL;
CompletionKind CompletionOf(SemanticGoal ::= SemanticBlock)
	:= CompletionOf(SemanticBlock);



CompletionKind CompletionOf(SemanticExpressionConstant)
	:= NORMAL;

CompletionKind CompletionOf(SemanticExpressionTemplate ::= SemanticExpression+) := CompletionOf(SemanticExpression+);

CompletionKind CompletionOf(SemanticExpressionVariable)
	:= NORMAL;

CompletionKind CompletionOf(SemanticExpressionTuple ::= ())
	:= NORMAL;
CompletionKind CompletionOf(SemanticExpressionTuple ::= SemanticExpression+)
	:= CompletionOf(SemanticExpression+);

CompletionKind CompletionOf(SemanticExpressionRecord ::= SemanticProperty+) := CompletionOf(SemanticProperty+);

CompletionKind CompletionOf(SemanticExpressionList ::= ())
	:= NORMAL;
CompletionKind CompletionOf(SemanticExpressionList ::= SemanticExpression+)
	:= CompletionOf(SemanticExpression+);

CompletionKind CompletionOf(SemanticExpressionDict ::= SemanticProperty+) := CompletionOf(SemanticProperty+);

CompletionKind CompletionOf(SemanticExpressionSet ::= ())
	:= NORMAL;
CompletionKind CompletionOf(SemanticExpressionSet ::= SemanticExpression+)
	:= CompletionOf(SemanticExpression+);

CompletionKind CompletionOf(SemanticExpressionMap ::= SemanticCase+) :=
	1. *Let* `completions` be a mapping of `SemanticCase+` for each `SemanticCase` to *UnwrapAffirm:* `CompletionOf(SemanticCase)`.
	2. *Return:* `MaximumCompletion(completions)`.
;

CompletionKind CompletionOf(SemanticExpressionBlock ::= SemanticBlock) := CompletionOf(SemanticBlock);

CompletionKind CompletionOf(SemanticExpressionAccess ::= SemanticExpression (SemanticIndex | SemanticKey))
	:= CompletionOf(SemanticExpression);
CompletionKind CompletionOf(SemanticExpressionAccess ::= SemanticExpression__0 SemanticExpression__1)
	:= CompletionOf([SemanticExpression__0, SemanticExpression__1]);

CompletionKind CompletionOf(SemanticExpressionCall ::= SemanticExpression__0 SemanticType* SemanticExpression__1*)
	:= CompletionOf([SemanticExpression__0, ...SemanticExpression__1*]);

CompletionKind CompletionOf(SemanticExpressionClaim ::= SemanticExpression SemanticType)
	:= CompletionOf(SemanticExpression);

CompletionKind CompletionOf(SemanticExpressionOperation ::= SemanticExpression+)
	:= CompletionOf(SemanticExpression+);
CompletionKind CompletionOf(SemanticExpressionOperation[operator: COND] ::= SemanticExpression__0[type: Boolean] SemanticExpression__1 SemanticExpression__2)
	:= MaximumCompletion([
		CompletionOf(SemanticExpression__0),
		MinimumCompletion([
			CompletionOf(SemanticExpression__1),
			CompletionOf(SemanticExpression__2),
		]),
	]);

CompletionKind CompletionOf(SemanticExpressionSwitch ::= SemanticExpression__0 SemanticCase* SemanticExpression__1)
	:= MaximumCompletion([
		CompletionOf(SemanticExpression__0),
		MinimumCompletion([
			...SemanticCase*.map(CompletionOf),
			CompletionOf(SemanticExpression__1),
		]),
	]);

CompletionKind CompletionOf(SemanticExpressionFunction)
	:= NORMAL;



CompletionKind CompletionOf(SemanticDeclarationType) := NORMAL;

CompletionKind CompletionOf(SemanticDeclarationVariable ::= SemanticType)
	:= NORMAL;
CompletionKind CompletionOf(SemanticDeclarationVariable ::= SemanticType? SemanticExpression)
	:= CompletionOf(SemanticExpression);

CompletionKind CompletionOf(SemanticDeclarationFunction) := NORMAL;

CompletionKind CompletionOf(SemanticStatementExpression ::= ())
	:= NORMAL;
CompletionKind CompletionOf(SemanticStatementExpression ::= SemanticExpression)
	:= CompletionOf(SemanticExpression);

CompletionKind CompletionOf(SemanticStatementClaim ::= SemanticExpressionVariable SemanticType) := CompletionOf(SemanticExpressionVariable);
CompletionKind CompletionOf(SemanticStatementClaim ::= SemanticExpressionAccess   SemanticType) := CompletionOf(SemanticExpressionAccess);

CompletionKind CompletionOf(SemanticStatementReassignment ::= SemanticExpressionVariable)
	:= NORMAL;
CompletionKind CompletionOf(SemanticStatementReassignment ::= SemanticExpressionAccess)
	:= CompletionOf(SemanticExpressionAccess);
CompletionKind CompletionOf(SemanticStatementReassignment ::= SemanticExpressionVariable SemanticExpression)
	:= CompletionOf(SemanticExpression);
CompletionKind CompletionOf(SemanticStatementReassignment ::= SemanticExpressionAccess SemanticExpression)
	:= CompletionOf([
		SemanticExpressionAccess,
		SemanticExpression,
	]);

CompletionKind CompletionOf(SemanticStatementConditional ::= SemanticExpression SemanticBlock)
	:= CompletionOf(SemanticExpression);
CompletionKind CompletionOf(SemanticStatementConditional ::= SemanticExpression SemanticBlock__0 SemanticBlock__1)
	:= MaximumCompletion([
		CompletionOf(SemanticExpression),
		MinimumCompletion([
			CompletionOf(SemanticBlock__0),
			CompletionOf(SemanticBlock__1),
		]),
	]);
CompletionKind CompletionOf(SemanticStatementConditional ::= SemanticExpression SemanticBlock SemanticStatementConditional)
	:= MaximumCompletion([
		CompletionOf(SemanticExpression),
		MinimumCompletion([
			CompletionOf(SemanticBlock),
			CompletionOf(SemanticStatementConditional),
		]),
	]);

CompletionKind CompletionOf(SemanticStatementLoop ::= SemanticExpression SemanticBlock)
	:= CompletionOf([
		SemanticExpression,
		SemanticBlock,
	]);

CompletionKind CompletionOf(SemanticStatementIteration ::= SemanticType SemanticExpression SemanticBlock)
	:= CompletionOf(
		SemanticExpression,
		SemanticBlock,
	);

CompletionKind CompletionOf(SemanticStatementBreak)  := BREAK_OR_SKIP;
CompletionKind CompletionOf(SemanticStatementReturn) := RETURN_OR_THROW;
CompletionKind CompletionOf(SemanticStatementThrow)  := RETURN_OR_THROW;



CompletionKind MinimumCompletion(Sequence<CompletionKind> completions) :=
	1. *Let* `result` be *RETURN_OR_THROW*.
	2. *For each* `completion` in `completions`:
		1. *If* `result` is *RETURN_OR_THROW*:
			1. *If* `completion` is not *RETURN_OR_THROW*:
				1. *Set* `result` to `completion`.
			2. *Else:*
				1. Fall through.
		2. *Else If* `result` is *BREAK_OR_SKIP*:
			1. *If* `completion` is *NORMAL*:
				1. *Set* `result` to `completion`.
			2. *Else:*
				1. Fall through.
		3. *Else:*
			1. *Assert:* `result` is *NORMAL*.
			2. Fall through.
	3. *Return:* `result`.
;



CompletionKind MaximumCompletion(Sequence<CompletionKind> completions) :=
	1. *Let* `result` be *NORMAL*.
	2. *For each* `completion` in `completions`:
		1. *If* `result` is *NORMAL*:
			1. *If* `completion` is not *NORMAL*:
				1. *Set* `result` to `completion`.
			2. *Else:*
				1. Fall through.
		2. *Else If* `result` is *BREAK_OR_SKIP*:
			1. *If* `completion` is *RETURN_OR_THROW*:
				1. *Set* `result` to `completion`.
			2. *Else:*
				1. Fall through.
		3. *Else:*
			1. *Assert:* `result` is *RETURN_OR_THROW*.
			2. Fall through.
	3. *Return:* `result`.
;
