_KEYWORD_OTHER =:=
	// operator
		| "mut"
		| "as"
		| "is"
		| "if"
		| "then"
		| "else"
	// storage
		| "type"
		| "val"
		| "claim"
		| "set"
		| "_"
		| "void"
	// modifier
		| "nominal"
	// control
		| "unless"
		| "while"
		| "until"
		| "for"
		| "in"
		| "do"
		| "break"
		| "skip"
;

Decorate(Word ::= _KEYWORD_OTHER) -> SemanticKey
	:= (SemanticKey[id=TokenWorth(_KEYWORD_OTHER)]);
Decorate(Word ::= IDENTIFIER) -> SemanticKey
	:= (SemanticKey[id=TokenWorth(IDENTIFIER)]);
Decorate(Word ::= KeywordType) -> SemanticKey
	:= (SemanticKey[id=TokenId(KeywordType)]);
Decorate(Word ::= KeywordValue) -> SemanticKey
	:= (SemanticKey[id=TokenId(KeywordValue)]);



Decorate(PrimitiveLiteral ::= INTEGER) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Integer(TokenWorth(INTEGER))]);
Decorate(PrimitiveLiteral ::= NATURAL) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Natural(TokenWorth(NATURAL))]);
Decorate(PrimitiveLiteral ::= FLOAT) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Float(TokenWorth(FLOAT))]);
Decorate(PrimitiveLiteral ::= STRING) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=String(TokenWorth(STRING))]);
Decorate(PrimitiveLiteral ::= KeywordValue) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=KeywordValue(KeywordValue)]);
Decorate(PrimitiveLiteral ::= "@" Word) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Symbol(Decorate(Word).id)]);



Decorate(EntryType<-Named><-Optional> ::= Type) -> SemanticItemType
	:= (SemanticItemType[optional=false] Decorate(Type));
Decorate(EntryType<-Named><+Optional> ::= "?:" Type) -> SemanticItemType
	:= (SemanticItemType[optional=true] Decorate(Type));
Decorate(EntryType<+Named><-Optional> ::= Word ":" Type) -> SemanticPropertyType
	:= (SemanticPropertyType[optional=false]
		Decorate(Word)
		Decorate(Type)
	);
Decorate(EntryType<+Named><+Optional> ::= Word "?:" Type) -> SemanticPropertyType
	:= (SemanticPropertyType[optional=true]
		Decorate(Word)
		Decorate(Type)
	);



Decorate(ItemsType ::= ","? EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= ParseList(EntryType<-Named><+Optional>, SemanticItemType);
Decorate(ItemsType ::= EntryType<-Named><-Optional> ",") -> Sequence<SemanticItemType>
	:= [Decorate(EntryType<-Named><-Optional>)];
Decorate(ItemsType ::= EntryType<-Named><-Optional> "," EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= [
		Decorate(EntryType<-Named><-Optional>),
		...ParseList(EntryType<-Named><+Optional>, SemanticItemType),
	];
Decorate(ItemsType ::= "," EntryType<-Named><-Optional># ","?) -> Sequence<SemanticItemType>
	:= ParseList(EntryType<-Named><-Optional>, SemanticItemType);
Decorate(ItemsType ::= "," EntryType<-Named><-Optional># "," EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= [
		...ParseList(EntryType<-Named><-Optional>, SemanticItemType),
		...ParseList(EntryType<-Named><+Optional>, SemanticItemType),
	];
Decorate(ItemsType ::= EntryType<-Named><-Optional>__0 "," EntryType<-Named><-Optional>__1# ","?) -> Sequence<SemanticItemType>
	:= [
		Decorate(EntryType<-Named><-Optional>__0),
		...ParseList(EntryType<-Named><-Optional>__1, SemanticItemType),
	];
Decorate(ItemsType ::= EntryType<-Named><-Optional>__0 "," EntryType<-Named><-Optional>__1# "," EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= [
		Decorate(EntryType<-Named><-Optional>__0),
		...ParseList(EntryType<-Named><-Optional>__1, SemanticItemType),
		...ParseList(EntryType<-Named><+Optional>,    SemanticItemType),
	];



Decorate(PropertiesType ::= ","? EntryType<+Named><∓Optional># ","?) -> Sequence<SemanticPropertyType>
	:= ParseList(EntryType<+Named><∓Optional>, SemanticPropertyType);



Decorate(ParametersType ::= ","? EntryType<-Named><-Optional># ","?) -> Sequence<SemanticItemType>
	:= ParseList(EntryType<-Named><-Optional>, SemanticItemType);
Decorate(ParametersType ::= ","? EntryType<+Named><-Optional># ","?) -> Sequence<SemanticPropertyType>
	:= ParseList(EntryType<+Named><-Optional>, SemanticPropertyType);
Decorate(ParametersType ::= ","? EntryType<-Named><-Optional># "," EntryType<+Named><-Optional># ","?) -> Sequence<...Sequence<SemanticItemType>, ...Sequence<SemanticPropertyType>>
	:= [
		...ParseList(EntryType<-Named><-Optional>, SemanticItemType),
		...ParseList(EntryType<+Named><-Optional>, SemanticPropertyType),
	];



Decorate(PropertyAccessorType ::= INTEGER) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(INTEGER)]);
Decorate(PropertyAccessorType ::= NATURAL) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(NATURAL)]);
Decorate(PropertyAccessorType ::= Word) -> SemanticKey
	:= Decorate(Word);



Decorate(TypeGrouped ::= "(" Type ")") -> SemanticType
	:= Decorate(Type);

Decorate(TypeTupleLiteral ::= "(" ")") -> SemanticTypeTuple
	:= (SemanticTypeTuple);
Decorate(TypeTupleLiteral ::= "(" ItemsType ")") -> SemanticTypeTuple
	:= (SemanticTypeTuple
		...Decorate(ItemsType)
	);

Decorate(TypeRecordLiteral ::= "(" PropertiesType ")") -> SemanticTypeRecord
	:= (SemanticTypeRecord
		...Decorate(PropertiesType)
	);

Decorate(TypeListLiteral ::= "[" Type "]") -> SemanticTypeList
	:= (SemanticTypeList
		...Decorate(Type)
	);

Decorate(TypeDictLiteral ::= "[" ":" Type "]") -> SemanticTypeDict
	:= (SemanticTypeDict
		Decorate(Type)
	);

Decorate(TypeSetLiteral ::= "{" Type "}") -> SemanticTypeSet
	:= (SemanticTypeSet
		...Decorate(Type)
	);

Decorate(TypeMapLiteral ::= "{" Type__0 "->" Type__1 "}") -> SemanticTypeMap
	:= (SemanticTypeMap
		Decorate(Type__0)
		Decorate(Type__1)
	);

Decorate(GenericArguments ::= "<" ","? Type# ","? ">") -> Sequence<SemanticType>
	:= ParseList(Type, SemanticType);



Decorate(TypeUnit ::= IDENTIFIER) -> SemanticTypeAlias
	:= (SemanticTypeAlias[id=TokenWorth(IDENTIFIER)]);
Decorate(TypeUnit ::= KeywordType) -> SemanticTypeConstant
	:= (SemanticTypeConstant[value=KeywordType(KeywordType)]);
Decorate(TypeUnit ::= PrimitiveLiteral) -> SemanticTypeConstant
	:= (SemanticTypeConstant[value=ToType(Decorate(PrimitiveLiteral).value)]);
Decorate(TypeUnit ::= TypeGrouped) -> SemanticType
	:= Decorate(TypeGrouped);
Decorate(TypeUnit ::= TypeTupleLiteral) -> SemanticTypeTuple
	:= Decorate(TypeTupleLiteral);
Decorate(TypeUnit ::= TypeRecordLiteral) -> SemanticTypeRecord
	:= Decorate(TypeRecordLiteral);
Decorate(TypeUnit ::= TypeListLiteral) -> SemanticTypeList
	:= Decorate(TypeListLiteral);
Decorate(TypeUnit ::= TypeDictLiteral) -> SemanticTypeDict
	:= Decorate(TypeDictLiteral);
Decorate(TypeUnit ::= TypeSetLiteral) -> SemanticTypeSet
	:= Decorate(TypeSetLiteral);
Decorate(TypeUnit ::= TypeMapLiteral) -> SemanticTypeMap
	:= Decorate(TypeMapLiteral);



Decorate(TypeCompound ::= TypeUnit) -> SemanticType
	:= Decorate(TypeUnit);
Decorate(TypeCompound ::= TypeCompound "." PropertyAccessorType) -> SemanticTypeAccess
	:= (SemanticTypeAccess[kind=NORMAL]
		Decorate(TypeCompound)
		Decorate(PropertyAccessorType)
	);
Decorate(TypeCompound ::= TypeCompound "?." PropertyAccessorType) -> SemanticTypeAccess
	:= (SemanticTypeAccess[kind=MAYBE]
		Decorate(TypeCompound)
		Decorate(PropertyAccessorType)
	);
Decorate(TypeCompound ::= TypeCompound "." GenericArguments) -> SemanticTypeCall
	:= (SemanticTypeCall
		Decorate(TypeCompound)
		...Decorate(GenericArguments)
	);



Decorate(TypeUnarySymbol ::= TypeCompound) -> SemanticType
	:= Decorate(TypeCompound);
Decorate(TypeUnarySymbol ::= TypeUnarySymbol "?") -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=MAYBE]
		Decorate(TypeUnarySymbol)
	);
Decorate(TypeUnarySymbol ::= TypeUnarySymbol "!") -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=RESULT]
		Decorate(TypeUnarySymbol)
	);



Decorate(TypeUnaryKeyword ::= TypeUnarySymbol) -> SemanticType
	:= Decorate(TypeUnarySymbol);
Decorate(TypeUnaryKeyword ::= "mut" TypeUnaryKeyword) -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=MUTABLE]
		Decorate(TypeUnaryKeyword)
	);



Decorate(TypeIntersection ::= TypeUnaryKeyword) -> SemanticType
	:= Decorate(TypeUnaryKeyword);
Decorate(TypeIntersection ::= TypeIntersection "&" TypeUnaryKeyword) -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=AND]
		Decorate(TypeIntersection)
		Decorate(TypeUnaryKeyword)
	);



Decorate(TypeUnion ::= TypeIntersection) -> SemanticType
	:= Decorate(TypeIntersection);
Decorate(TypeUnion ::= TypeUnion "|" TypeIntersection) -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=OR]
		Decorate(TypeUnion)
		Decorate(TypeIntersection)
	);



Decorate(TypeFunction ::= "\" "(" ")" "=>" "void") -> SemanticTypeFunction
	:= (SemanticTypeFunction);
Decorate(TypeFunction ::= "\" "(" ")" "=>" Type) -> SemanticTypeFunction
	:= (SemanticTypeFunction Decorate(Type));
Decorate(TypeFunction ::= "\" "(" ParametersType ")" "=>" "void") -> SemanticTypeFunction
	:= (SemanticTypeFunction ...Decorate(ParametersType));
Decorate(TypeFunction ::= "\" "(" ParametersType ")" "=>" Type) -> SemanticTypeFunction
	:= (SemanticTypeFunction
		...Decorate(ParametersType)
		Decorate(Type)
	);



Decorate(Type ::= TypeUnion) -> SemanticType
	:= Decorate(TypeUnion);
Decorate(Type ::= TypeFunction) -> SemanticType
	:= Decorate(TypeFunction);



Decorate(StringTemplate<Break, Return> ::= TEMPLATE_FULL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_FULL))])
	);
Decorate(StringTemplate<Break, Return> ::= TEMPLATE_HEAD TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);
Decorate(StringTemplate<Break, Return> ::= TEMPLATE_HEAD Expression<+Block><?Break><?Return> TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		Decorate(Expression<+Block><?Break><?Return>)
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);
Decorate(StringTemplate<Break, Return> ::= TEMPLATE_HEAD StringTemplate__0__List TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		...Decorate(StringTemplate__0__List)
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);
Decorate(StringTemplate<Break, Return> ::= TEMPLATE_HEAD Expression<+Block><?Break><?Return> StringTemplate__0__List TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		Decorate(Expression<+Block><?Break><?Return>)
		...Decorate(StringTemplate__0__List)
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);

	Decorate(StringTemplate__0__List<Break, Return> ::= TEMPLATE_MIDDLE) -> Vector<SemanticExpressionConstant>
		:= [SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]];
	Decorate(StringTemplate__0__List<Break, Return> ::= TEMPLATE_MIDDLE Expression<+Block><?Break><?Return>) -> Vector<SemanticExpressionConstant, SemanticExpression>
		:= [
			(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]),
			Decorate(Expression<+Block><?Break><?Return>),
		];
	Decorate(StringTemplate__0__List<Break, Return> ::= StringTemplate__0__List TEMPLATE_MIDDLE) -> Sequence<...Vector<SemanticExpressionConstant, SemanticExpression?>>
		:= [
			...Decorate(StringTemplate__0__List),
			(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]),
		];
	Decorate(StringTemplate__0__List<Break, Return> ::= StringTemplate__0__List TEMPLATE_MIDDLE Expression<+Block><?Break><?Return>) -> Sequence<...Vector<SemanticExpressionConstant, SemanticExpression?>>
		:= [
			...Decorate(StringTemplate__0__List),
			(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]),
			Decorate(Expression<+Block><?Break><?Return>),
		];



Decorate(Items<Break, Return> ::= Expression<+Block><?Break><?Return> ",") -> Sequence<SemanticExpression>
	:= [Decorate(Expression<+Block><?Break><?Return>)];
Decorate(Items<Break, Return> ::= "," Expression<+Block><?Break><?Return># ","?) -> Sequence<SemanticExpression>
	:= ParseList(Expression<+Block><?Break><?Return>, SemanticExpression);
Decorate(Items<Break, Return> ::= Expression__0<+Block><?Break><?Return> "," Expression__1<+Block><?Break><?Return># ","?) -> Sequence<SemanticExpression>
	:= [
		Decorate(Expression__0<+Block><?Break><?Return>),
		...ParseList(Expression__1<+Block><?Break><?Return>, SemanticExpression),
	];

Decorate(Property<Break, Return> ::= Word "=" Expression<+Block><?Break><?Return>) -> SemanticProperty
	:= (SemanticProperty
		Decorate(Word)
		Decorate(Expression<+Block><?Break><?Return>)
	);

Decorate(CaseMap<Break, Return> ::= Expression__0<+Block><?Break><?Return> "->" Expression__1<+Block><?Break><?Return>) -> SemanticCase
	:= (SemanticCase
		Decorate(Expression__0<+Block><?Break><?Return>)
		Decorate(Expression__1<+Block><?Break><?Return>)
	);

Decorate(CaseSwitch<Break, Return> ::= "case" Expression__0<+Block><?Break><?Return> "->" Expression__1<+Block><?Break><?Return>) -> SemanticCase
	:= (SemanticCase
		Decorate(Expression__0<+Block><?Break><?Return>)
		Decorate(Expression__1<+Block><?Break><?Return>)
	);
Decorate(CaseSwitch<Break, Return> ::= "case" (Expression__0<+Block><?Break><?Return> "|")+ Expression__1<+Block><?Break><?Return> "->" Expression__2<+Block><?Break><?Return>) -> SemanticCase
	:= (SemanticCase
		...ParseList((Expression__0<+Block><?Break><?Return> "|")+ Expression__1<+Block><?Break><?Return> =:: Expression<+Block><?Break><?Return>__List "|" Expression<+Block><?Break><?Return>, SemanticExpression)
		Decorate(Expression__2<+Block><?Break><?Return>)
	);



Decorate(ParameterFunction<Named> ::= "_" ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=false][writable=false][id=*nil*]
		Decorate(Type)
	);
Decorate(ParameterFunction<Named> ::= IDENTIFIER ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=false][writable=false][id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
	);
Decorate(ParameterFunction<Named> ::= "mut" IDENTIFIER ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=false][writable=true][id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
	);
Decorate(ParameterFunction<Named> ::= Word "=" "_" ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=true][writable=false][id=*nil*]
		Decorate(Word)
		Decorate(Type)
	);
Decorate(ParameterFunction<Named> ::= Word "=" IDENTIFIER ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=true][writable=false][id=TokenWorth(IDENTIFIER)]
		Decorate(Word)
		Decorate(Type)
	);
Decorate(ParameterFunction<Named> ::= Word "=" "mut" IDENTIFIER ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=true][writable=true][id=TokenWorth(IDENTIFIER)]
		Decorate(Word)
		Decorate(Type)
	);
Decorate(ParameterFunction<Named> ::= "$" IDENTIFIER ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=true][writable=false][id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
	);
Decorate(ParameterFunction<Named> ::= "mut" "$" IDENTIFIER ":" Type) -> SemanticParameterFunction
	:= (SemanticParameterFunction[named=true][writable=true][id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
	);

Decorate(ParametersFunction ::= ","? ParameterFunction<-Named># ","?) -> Sequence<SemanticParameterFunction>
	:= ParseList(ParameterFunction<-Named>, SemanticParameterFunction);
Decorate(ParametersFunction ::= ","? ParameterFunction<+Named># ","?) -> Sequence<SemanticParameterFunction>
	:= ParseList(ParameterFunction<+Named>, SemanticParameterFunction);
Decorate(ParametersFunction ::= ","? ParameterFunction<-Named># "," ParameterFunction<+Named># ","?) -> Sequence<SemanticParameterFunction>
	:= [
		...ParseList(ParameterFunction<-Named>, SemanticParameterFunction),
		...ParseList(ParameterFunction<+Named>, SemanticParameterFunction),
	];



Decorate(PropertyAccessor<Break, Return> ::= INTEGER) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(INTEGER)]);
Decorate(PropertyAccessor<Break, Return> ::= NATURAL) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(NATURAL)]);
Decorate(PropertyAccessor<Break, Return> ::= Word) -> SemanticKey
	:= Decorate(Word);
Decorate(PropertyAccessor<Break, Return> ::= "[" Expression<+Block><?Break><?Return> "]") -> SemanticExpression
	:= Decorate(Expression<+Block><-Break><?Return>);



Decorate(ExpressionGrouped<Break, Return> ::= "(" Expression<+Block><?Break><?Return> ")") -> SemanticExpression
	:= Decorate(Expression<+Block><?Break><?Return>);

Decorate(ExpressionTupleLiteral<Break, Return> ::= "(" ")") -> SemanticExpressionTuple
	:= (SemanticExpressionTuple);
Decorate(ExpressionTupleLiteral<Break, Return> ::= "(" Items<?Break><?Return> ")") -> SemanticExpressionTuple
	:= (SemanticExpressionTuple
		...Decorate(Items<?Break><?Return>)
	);

Decorate(ExpressionRecordLiteral<Break, Return> ::= "(" ","? Property<?Break><?Return># ","? ")") -> SemanticExpressionRecord
	:= (SemanticExpressionRecord
		...ParseList(Property<?Break><?Return>, SemanticProperty)
	);

Decorate(ExpressionListLiteral<Break, Return> ::= "[" "]") -> SemanticExpressionList
	:= (SemanticExpressionList);
Decorate(ExpressionListLiteral<Break, Return> ::= "[" (","? Expression<+Block><?Break><?Return># ","?)? "]") -> SemanticExpressionList
	:= (SemanticExpressionList
		...ParseList(Expression<+Block><?Break><?Return>, SemanticExpression)
	);

Decorate(ExpressionDictLiteral<Break, Return> ::= [" ","? Property<?Break><?Return># ","? "]") -> SemanticExpressionDict
	:= (SemanticExpressionDict
		...ParseList(Property<?Break><?Return>, SemanticProperty)
	);

Decorate(ExpressionSetLiteral<Break, Return> ::= "{" "}") -> SemanticExpressionSet
	:= (SemanticExpressionSet);
Decorate(ExpressionSetLiteral<Break, Return> ::= "{" (","? Expression<+Block><?Break><?Return># ","?)? "}") -> SemanticExpressionSet
	:= (SemanticExpressionSet
		...ParseList(Expression<+Block><?Break><?Return>, SemanticExpression)
	);

Decorate(ExpressionMapLiteral<Break, Return> ::= "{" ","? CaseMap<?Break><?Return># ","? "}") -> SemanticExpressionMap
	:= (SemanticExpressionMap
		...ParseList(CaseMap<?Break><?Return>, SemanticCase)
	);

Decorate(FunctionArguments<Break, Return> ::= "(" (","? Expression<+Block><?Break><?Return># ","?)? ")") -> Sequence<SemanticExpression>
	:= ParseList(Expression<+Block><?Break><?Return>, SemanticExpression);



Decorate(ExpressionUnit<Block, Break, Return> ::= IDENTIFIER) -> SemanticExpressionVariable
	:= (SemanticExpressionVariable[id=TokenWorth(IDENTIFIER)]);
Decorate(ExpressionUnit<Block, Break, Return> ::= PrimitiveLiteral) -> SemanticExpressionConstant
	:= Decorate(PrimitiveLiteral);
Decorate(ExpressionUnit<Block, Break, Return> ::= StringTemplate<?Break><?Return>) -> SemanticExpressionTemplate
	:= Decorate(StringTemplate<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= ExpressionGrouped<?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionGrouped<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= ExpressionTupleLiteral<?Break><?Return>) -> SemanticExpressionTuple
	:= Decorate(ExpressionTupleLiteral<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= ExpressionRecordLiteral<?Break><?Return>) -> SemanticExpressionRecord
	:= Decorate(ExpressionRecordLiteral<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= ExpressionListLiteral<?Break><?Return>) -> SemanticExpressionList
	:= Decorate(ExpressionListLiteral<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= ExpressionDictLiteral<?Break><?Return>) -> SemanticExpressionDict
	:= Decorate(ExpressionDictLiteral<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= ExpressionSetLiteral<?Break><?Return>) -> SemanticExpressionSet
	:= Decorate(ExpressionSetLiteral<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= ExpressionMapLiteral<?Break><?Return>) -> SemanticExpressionMap
	:= Decorate(ExpressionMapLiteral<?Break><?Return>);
Decorate(ExpressionUnit<Block, Break, Return> ::= Block<?Break><?Return>) -> SemanticExpressionBlock
	:= (SemanticExpressionBlock Decorate(Block<?Break><?Return>));



Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionUnit<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionUnit<?Block><?Break><?Return>);
Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return> "~?") -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=UN_MAYBE]
		Decorate(ExpressionCompound<?Block><?Break><?Return>)
	);
Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return> "~!") -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=UN_RESULT]
		Decorate(ExpressionCompound<?Block><?Break><?Return>)
	);
Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return> "." PropertyAccessor<?Break><?Return>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=NORMAL]
		Decorate(ExpressionCompound<?Block><?Break><?Return>)
		Decorate(PropertyAccessor<?Break><?Return>)
	);
Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return> "?." PropertyAccessor<?Break><?Return>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=MAYBE]
		Decorate(ExpressionCompound<?Block><?Break><?Return>)
		Decorate(PropertyAccessor<?Break><?Return>)
	);
Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return> "!." PropertyAccessor<?Break><?Return>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=RESULT]
		Decorate(ExpressionCompound<?Block><?Break><?Return>)
		Decorate(PropertyAccessor<?Break><?Return>)
	);
Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return> "." FunctionArguments<?Break><?Return>) -> SemanticExpressionCall
	:= (SemanticExpressionCall
		Decorate(ExpressionCompound<?Block><?Break><?Return>)
		...Decorate(FunctionArguments<?Break><?Return>)
	);
Decorate(ExpressionCompound<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return> "." GenericArguments FunctionArguments<?Break><?Return>) -> SemanticExpressionCall
	:= (SemanticExpressionCall
		Decorate(ExpressionCompound<?Block><?Break><?Return>)
		...Decorate(GenericArguments)
		...Decorate(FunctionArguments<?Break><?Return>)
	);



Decorate(ExpressionUnarySymbol<Block, Break, Return> ::= ExpressionCompound<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionCompound<?Block><?Break><?Return>);
Decorate(ExpressionUnarySymbol<Block, Break, Return> ::= "!" ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>)
	);
Decorate(ExpressionUnarySymbol<Block, Break, Return> ::= "?" ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=EMP]
		Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>)
	);
Decorate(ExpressionUnarySymbol<Block, Break, Return> ::= "+" ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>);
Decorate(ExpressionUnarySymbol<Block, Break, Return> ::= "-" ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NEG]
		Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>)
	);



Decorate(ExpressionCast<Block, Break, Return> ::= ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>);
Decorate(ExpressionCast<Block, Break, Return> ::= ExpressionCast<?Block><?Break><?Return> "as" ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=CAST]
		Decorate(ExpressionCast<?Block><?Break><?Return>)
		Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>)
	);
Decorate(ExpressionCast<Block, Break, Return> ::= ExpressionCast<?Block><?Break><?Return> "as?" ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=MAYBE]
		Decorate(ExpressionCast<?Block><?Break><?Return>)
		Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>)
	);
Decorate(ExpressionCast<Block, Break, Return> ::= ExpressionCast<?Block><?Break><?Return> "as!" ExpressionUnarySymbol<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=RESULT]
		Decorate(ExpressionCast<?Block><?Break><?Return>)
		Decorate(ExpressionUnarySymbol<?Block><?Break><?Return>)
	);
Decorate(ExpressionCast<Block, Break, Return> ::= ExpressionCast<?Block><?Break><?Return> "as" "<" Type ">") -> SemanticExpressionClaim
	:= (SemanticExpressionClaim
		Decorate(ExpressionCast<?Block><?Break><?Return>)
		Decorate(Type)
	);



Decorate(ExpressionExponential<Block, Break, Return> ::= ExpressionCast<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionCast<?Block><?Break><?Return>);
Decorate(ExpressionExponential<Block, Break, Return> ::= ExpressionCast<?Block><?Break><?Return> "^" ExpressionExponential<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=EXP]
		Decorate(ExpressionCast<?Block><?Break><?Return>)
		Decorate(ExpressionExponential<?Block><?Break><?Return>)
	);



Decorate(ExpressionMultiplicative<Block, Break, Return> ::= ExpressionExponential<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionExponential<?Block><?Break><?Return>);
Decorate(ExpressionMultiplicative<Block, Break, Return> ::= ExpressionMultiplicative<?Block><?Break><?Return> "*" ExpressionExponential<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=MUL]
		Decorate(ExpressionMultiplicative<?Block><?Break><?Return>)
		Decorate(ExpressionExponential<?Block><?Break><?Return>)
	);
Decorate(ExpressionMultiplicative<Block, Break, Return> ::= ExpressionMultiplicative<?Block><?Break><?Return> "/" ExpressionExponential<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=DIV]
		Decorate(ExpressionMultiplicative<?Block><?Break><?Return>)
		Decorate(ExpressionExponential<?Block><?Break><?Return>)
	);



Decorate(ExpressionAdditive<Block, Break, Return> ::= ExpressionMultiplicative<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionMultiplicative<?Block><?Break><?Return>);
Decorate(ExpressionAdditive<Block, Break, Return> ::= ExpressionAdditive<?Block><?Break><?Return> "+" ExpressionMultiplicative<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=ADD]
		Decorate(ExpressionAdditive<?Block><?Break><?Return>)
		Decorate(ExpressionMultiplicative<?Block><?Break><?Return>)
	);
Decorate(ExpressionAdditive<Block, Break, Return> ::= ExpressionAdditive<?Block><?Break><?Return> "-" ExpressionMultiplicative<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=SUB]
		Decorate(ExpressionAdditive<?Block><?Break><?Return>)
		Decorate(ExpressionMultiplicative<?Block><?Break><?Return>)
	);



Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionAdditive<?Block><?Break><?Return>);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> "<" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=LT]
		Decorate(ExpressionComparative<?Block><?Break><?Return>)
		Decorate(ExpressionAdditive<?Block><?Break><?Return>)
	);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> ">" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=GT]
		Decorate(ExpressionComparative<?Block><?Break><?Return>)
		Decorate(ExpressionAdditive<?Block><?Break><?Return>)
	);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> "<=" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=LE]
		Decorate(ExpressionComparative<?Block><?Break><?Return>)
		Decorate(ExpressionAdditive<?Block><?Break><?Return>)
	);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> ">=" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=GE]
		Decorate(ExpressionComparative<?Block><?Break><?Return>)
		Decorate(ExpressionAdditive<?Block><?Break><?Return>)
	);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> "!<" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=LT]
			Decorate(ExpressionComparative<?Block><?Break><?Return>)
			Decorate(ExpressionAdditive<?Block><?Break><?Return>)
		)
	);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> "!>" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=GT]
			Decorate(ExpressionComparative<?Block><?Break><?Return>)
			Decorate(ExpressionAdditive<?Block><?Break><?Return>)
		)
	);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> "is" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=IS]
		Decorate(ExpressionComparative<?Block><?Break><?Return>)
		Decorate(ExpressionAdditive<?Block><?Break><?Return>)
	);
Decorate(ExpressionComparative<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return> "!is" ExpressionAdditive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=IS]
			Decorate(ExpressionComparative<?Block><?Break><?Return>)
			Decorate(ExpressionAdditive<?Block><?Break><?Return>)
		)
	);



Decorate(ExpressionEquality<Block, Break, Return> ::= ExpressionComparative<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionComparative<?Block>);
Decorate(ExpressionEquality<Block, Break, Return> ::= ExpressionEquality<?Block><?Break><?Return> "===" ExpressionComparative<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=ID]
		Decorate(ExpressionEquality<?Block><?Break><?Return>)
		Decorate(ExpressionComparative<?Block><?Break><?Return>)
	);
Decorate(ExpressionEquality<Block, Break, Return> ::= ExpressionEquality<?Block><?Break><?Return> "!==" ExpressionComparative<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=ID]
			Decorate(ExpressionEquality<?Block><?Break><?Return>)
			Decorate(ExpressionComparative<?Block><?Break><?Return>)
		)
	);
Decorate(ExpressionEquality<Block, Break, Return> ::= ExpressionEquality<?Block><?Break><?Return> "==" ExpressionComparative<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=EQ]
		Decorate(ExpressionEquality<?Block><?Break><?Return>)
		Decorate(ExpressionComparative<?Block><?Break><?Return>)
	);
Decorate(ExpressionEquality<Block, Break, Return> ::= ExpressionEquality<?Block><?Break><?Return> "!=" ExpressionComparative<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=EQ]
			Decorate(ExpressionEquality<?Block><?Break><?Return>)
			Decorate(ExpressionComparative<?Block><?Break><?Return>)
		)
	);



Decorate(ExpressionConjunctive<Block, Break, Return> ::= ExpressionEquality<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionEquality<?Block><?Break><?Return>);
Decorate(ExpressionConjunctive<Block, Break, Return> ::= ExpressionConjunctive<?Block><?Break><?Return> "&&" ExpressionEquality<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=AND]
		Decorate(ExpressionConjunctive<?Block><?Break><?Return>)
		Decorate(ExpressionEquality<?Block><?Break><?Return>)
	);
Decorate(ExpressionConjunctive<Block, Break, Return> ::= ExpressionConjunctive<?Block><?Break><?Return> "!&" ExpressionEquality<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=AND]
			Decorate(ExpressionConjunctive<?Block><?Break><?Return>)
			Decorate(ExpressionEquality<?Block><?Break><?Return>)
		)
	);



Decorate(ExpressionDisjunctive<Block, Break, Return> ::= ExpressionConjunctive<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionConjunctive<?Block><?Break><?Return>);
Decorate(ExpressionDisjunctive<Block, Break, Return> ::= ExpressionDisjunctive<?Block><?Break><?Return> "||" ExpressionConjunctive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=OR]
		Decorate(ExpressionDisjunctive<?Block><?Break><?Return>)
		Decorate(ExpressionConjunctive<?Block><?Break><?Return>)
	);
Decorate(ExpressionDisjunctive<Block, Break, Return> ::= ExpressionDisjunctive<?Block><?Break><?Return> "!|" ExpressionConjunctive<?Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=OR]
			Decorate(ExpressionDisjunctive<?Block><?Break><?Return>)
			Decorate(ExpressionConjunctive<?Block><?Break><?Return>)
		)
	);



Decorate(ExpressionConditional<Break, Return> ::= "if" Expression__0<+Block><?Break><?Return> "then" Expression__1<-Block><?Break><?Return> "else" Expression__2<-Block><?Break><?Return>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=COND]
		Decorate(Expression__0<+Block><?Break><?Return>)
		Decorate(Expression__1<-Block><?Break><?Return>)
		Decorate(Expression__2<-Block><?Break><?Return>)
	);



Decorate(ExpressionSwitch<Break, Return> ::= "switch" Expression__0<+Block><?Break><?Return> "default" Expression__1<+Block><?Break><?Return>) -> SemanticExpressionSwitch
	:= (SemanticExpressionSwitch
		Decorate(Expression__0<+Block><?Break><?Return>)
		Decorate(Expression__1<+Block><?Break><?Return>)
	);
Decorate(ExpressionSwitch<Break, Return> ::= "switch" Expression__0<+Block><?Break><?Return> CaseSwitch<?Break><?Return>+ "default" Expression__1<+Block><?Break><?Return>) -> SemanticExpressionSwitch
	:= (SemanticExpressionSwitch
		Decorate(Expression__0<+Block><?Break><?Return>)
		...ParseList(CaseSwitch<?Break><?Return>, SemanticCase)
		Decorate(Expression__1<+Block><?Break><?Return>)
	);



Decorate(ExpressionFunction ::= "\" "(" ")" ":" "void" Block<-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		Decorate(Block<-Break><+Return>)
	);
Decorate(ExpressionFunction ::= "\" "(" ")" ":" "void" "=>" Expression<+Block><-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(ExpressionFunction ::= "\" "(" ")" ":" Type Block<-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		Decorate(Type)
		Decorate(Block<-Break><+Return>)
	);
Decorate(ExpressionFunction ::= "\" "(" ")" ":" Type "=>" Expression<+Block><-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		Decorate(Type)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(ExpressionFunction ::= "\" "(" ParametersFunction ")" ":" "void" Block<-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		...Decorate(ParametersFunction)
		Decorate(Block<-Break><+Return>)
	);
Decorate(ExpressionFunction ::= "\" "(" ParametersFunction ")" ":" "void" "=>" Expression<+Block><-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		...Decorate(ParametersFunction)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(ExpressionFunction ::= "\" "(" ParametersFunction ")" ":" Type Block<-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		...Decorate(ParametersFunction)
		Decorate(Type)
		Decorate(Block<-Break><+Return>)
	);
Decorate(ExpressionFunction ::= "\" "(" ParametersFunction ")" ":" Type "=>" Expression<+Block><-Break><+Return>) -> SemanticExpressionFunction
	:= (SemanticExpressionFunction
		...Decorate(ParametersFunction)
		Decorate(Type)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);



Decorate(Expression<Block, Break, Return> ::= ExpressionDisjunctive<?Block><?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionDisjunctive<?Block><?Break><?Return>);
Decorate(Expression<Block, Break, Return> ::= ExpressionConditional<?Break><?Return>) -> SemanticExpressionOperation
	:= Decorate(ExpressionConditional<?Break><?Return>);
Decorate(Expression<Block, Break, Return> ::= ExpressionSwitch<?Break><?Return>) -> SemanticExpression
	:= Decorate(ExpressionSwitch<?Break><?Return>);
Decorate(Expression<Block, Break, Return> ::= ExpressionFunction) -> SemanticExpressionFunction
	:= Decorate(ExpressionFunction);



Decorate(Assignee<Break, Return> ::= IDENTIFIER) -> SemanticExpressionVariable
	:= (SemanticExpressionVariable[id=TokenWorth(IDENTIFIER)]);
Decorate(Assignee<Break, Return> ::= ExpressionCompound<+Block><?Break><?Return> "." PropertyAccessor<?Break><?Return>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=NORMAL]
		Decorate(ExpressionCompound<+Block><?Break><?Return>)
		Decorate(PropertyAccessor<?Break><?Return>)
	);



Decorate(StatementExpression<Break, Return> ::= ";") -> SemanticStatementExpression
	:= (SemanticStatementExpression);
Decorate(StatementExpression<Break, Return> ::= Expression<+Block><?Break><?Return> ";") -> SemanticStatementExpression
	:= (SemanticStatementExpression Decorate(Expression<+Block><?Break><?Return>));



Decorate(StatementClaim<Break, Return> ::= "claim" Assignee<?Break><?Return> ":" Type ";") -> SemanticStatementClaim
	:= (SemanticStatementClaim
		Decorate(Assignee<?Break><?Return>)
		Decorate(Type)
	);



Decorate(StatementSet<Break, Return> ::= "set" Assignee<?Break><?Return> "=" Expression<+Block><?Break><?Return> ";") -> SemanticStatementReassignment
	:= (SemanticStatementReassignment
		Decorate(Assignee<?Break><?Return>)
		Decorate(Expression<+Block><?Break><?Return>)
	);



Decorate(StatementDelete<Break, Return> ::= "delete" Assignee<?Break><?Return> ";") -> SemanticStatementReassignment
	:= (SemanticStatementReassignment
		Decorate(Assignee<?Break><?Return>)
	);



Decorate(StatementConditional<Unless, Break, Return> ::= "if" Expression<+Block><?Break><?Return> "then" Block<?Break><?Return> ";") -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=false]
		Decorate(Expression<+Block><?Break><?Return>)
		Decorate(Block<?Break><?Return>)
	);
Decorate(StatementConditional<Unless, Break, Return> ::= "if" Expression<+Block><?Break><?Return> "then" Block__0<?Break><?Return> "else" Block__1<?Break><?Return> ";") -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=false]
		Decorate(Expression<+Block><?Break><?Return>)
		Decorate(Block__0<?Break><?Return>)
		Decorate(Block__1<?Break><?Return>)
	);
Decorate(StatementConditional<Unless, Break, Return> ::= "if" Expression<+Block><?Break><?Return> "then" Block<?Break><?Return> "else" StatementConditional<-Unless><?Break><?Return>) -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=false]
		Decorate(Expression<+Block><?Break><?Return>)
		Decorate(Block<?Break><?Return>)
		Decorate(StatementConditional<-Unless><?Break><?Return>)
	);
Decorate(StatementConditional<Unless, Break, Return> ::= "unless" Expression<+Block><?Break><?Return> "then" Block<?Break><?Return> ";") -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=true]
		Decorate(Expression<+Block><?Break><?Return>)
		Decorate(Block<?Break><?Return>)
	);



Decorate(StatementLoop<Return> ::= "while" Expression<+Block><-Break><?Return> "do" Block<+Break><?Return> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=false][until=false]
		Decorate(Expression<+Block><-Break><?Return>)
		Decorate(Block<+Break><?Return>)
	);
Decorate(StatementLoop<Return> ::= "do" Block<+Break><?Return> "while" Expression<+Block><-Break><?Return> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=true][until=false]
		Decorate(Expression<+Block><-Break><?Return>)
		Decorate(Block<+Break><?Return>)
	);
Decorate(StatementLoop<Return> ::= "until" Expression<+Block><-Break><?Return> "do" Block<+Break><?Return> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=false][until=true]
		Decorate(Expression<+Block><-Break><?Return>)
		Decorate(Block<+Break><?Return>)
	);
Decorate(StatementLoop<Return> ::= "do" Block<+Break><?Return> "until" Expression<+Block><-Break><?Return> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=true][until=true]
		Decorate(Expression<+Block><-Break><?Return>)
		Decorate(Block<+Break><?Return>)
	);



Decorate(StatementIteration<Return> ::= "for" "_" ":" Type "in" Expression<+Block><-Break><?Return> "do" Block<+Break><?Return> ";") -> SemanticStatementIteration
	:= (SemanticStatementIteration
		(SemanticType     Decorate(Type))
		(SemanticIterable Decorate(Expression<+Block><-Break><?Return>))
		Decorate(Block<+Break><?Return>)
	);
Decorate(StatementIteration<Return> ::= "for" IDENTIFIER ":" Type "in" Expression<+Block><-Break><?Return> "do" Block<+Break><?Return> ";") -> SemanticStatementIteration
	:= (SemanticStatementIteration[id=TokenWorth(IDENTIFIER)]
		(SemanticType     Decorate(Type))
		(SemanticIterable Decorate(Expression<+Block><-Break><?Return>))
		Decorate(Block<+Break><?Return>)
	);



Decorate(StatementBreak ::= "break" ";") -> SemanticStatementBreak
	:= (SemanticStatementBreak[skip=false]);
Decorate(StatementBreak ::= "skip" ";") -> SemanticStatementBreak
	:= (SemanticStatementBreak[skip=true]);

Decorate(StatementReturn<Break> ::= "return" ";") -> SemanticStatementReturn
	:= (SemanticStatementReturn);
Decorate(StatementReturn<Break> ::= "return" Expression<+Block><?Break><+Return> ";") -> SemanticStatementReturn
	:= (SemanticStatementReturn Decorate(Expression<+Block><?Break><+Return>));



Decorate(Statement<Break, Return> ::= Declaration<?Break><?Return>) -> SemanticDeclaration
	:= Decorate(Declaration<?Break><?Return>);
Decorate(Statement<Break, Return> ::= StatementExpression<?Break><?Return>) -> SemanticStatementExpression
	:= Decorate(StatementExpression<?Break><?Return>);
Decorate(Statement<Break, Return> ::= StatementClaim<?Break><?Return>) -> SemanticStatementClaim
	:= Decorate(StatementClaim<?Break><?Return>);
Decorate(Statement<Break, Return> ::= StatementSet<?Break><?Return>) -> SemanticStatementReassignment
	:= Decorate(StatementSet<?Break><?Return>);
Decorate(Statement<Break, Return> ::= StatementDelete<?Break><?Return>) -> SemanticStatementReassignment
	:= Decorate(StatementDelete<?Break><?Return>);
Decorate(Statement<Break, Return> ::= StatementConditional<∓Unless><?Break><?Return>) -> SemanticStatementConditional
	:= Decorate(StatementConditional<∓Unless><?Break><?Return>);
Decorate(Statement<Break, Return> ::= StatementLoop<?Return>) -> SemanticStatementLoop
	:= Decorate(StatementLoop<?Return>);
Decorate(Statement<Break, Return> ::= StatementIteration<?Return>) -> SemanticStatementIteration
	:= Decorate(StatementIteration<?Return>);
Decorate(Statement<Break, Return> ::= StatementBreak) -> SemanticStatementBreak
	:= Decorate(StatementBreak);
Decorate(Statement<Break, Return> ::= StatementReturn<?Break>) -> SemanticStatementReturn
	:= Decorate(StatementReturn<?Break>);



Decorate(Block<Break, Return> ::= "{" Statement<?Break><?Return>+ "}") -> SemanticBlock
	:= (SemanticBlock
		...ParseList(Statement<?Break><?Return>, SemanticStatement)
	);



Decorate(DeclarationType ::= "type" "_" "=" Type ";") -> SemanticDeclarationType
	:= (SemanticDeclarationType
		Decorate(Type)
	);
Decorate(DeclarationType ::= "type" IDENTIFIER "=" Type ";") -> SemanticDeclarationType
	:= (SemanticDeclarationType[id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
	);



Decorate(DeclarationVariable<Break, Return> ::= "val" "_" "=" Expression<+Block><?Break><?Return> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=false]
		Decorate(Expression<+Block><?Break><?Return>)
	);
Decorate(DeclarationVariable<Break, Return> ::= "val" "_" ":" Type "=" Expression<+Block><?Break><?Return> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=false]
		Decorate(Type)
		Decorate(Expression<+Block><?Break><?Return>)
	);
Decorate(DeclarationVariable<Break, Return> ::= "val" IDENTIFIER "=" Expression<+Block><?Break><?Return> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=false][id=TokenWorth(IDENTIFIER)]
		Decorate(Expression<+Block><?Break><?Return>)
	);
Decorate(DeclarationVariable<Break, Return> ::= "val" IDENTIFIER ":" Type "=" Expression<+Block><?Break><?Return> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=false][id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
		Decorate(Expression<+Block><?Break><?Return>)
	);
Decorate(DeclarationVariable<Break, Return> ::= "val" "mut" IDENTIFIER "=" Expression<+Block><?Break><?Return> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=true][id=TokenWorth(IDENTIFIER)]
		Decorate(Expression<+Block><?Break><?Return>)
	);
Decorate(DeclarationVariable<Break, Return> ::= "val" "mut" IDENTIFIER ":" Type "=" Expression<+Block><?Break><?Return> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=true][id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
		Decorate(Expression<+Block><?Break><?Return>)
	);
Decorate(DeclarationVariable<Break, Return> ::= "val" "mut" IDENTIFIER "?" ":" Type ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=true][id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
	);



Decorate(DeclarationFunction ::= "func" "_" "(" ")" ":" "void" Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" "_" "(" ")" ":" "void" "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(DeclarationFunction ::= "func" "_" "(" ")" ":" Type Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		Decorate(Type)
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" "_" "(" ")" ":" Type "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		Decorate(Type)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(DeclarationFunction ::= "func" "_" "(" ParametersFunction ")" ":" "void" Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		...Decorate(ParametersFunction)
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" "_" "(" ParametersFunction ")" ":" "void" "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		...Decorate(ParametersFunction)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(DeclarationFunction ::= "func" "_" "(" ParametersFunction ")" ":" Type Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		...Decorate(ParametersFunction)
		Decorate(Type)
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" "_" "(" ParametersFunction ")" ":" Type "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=*nil*]
		...Decorate(ParametersFunction)
		Decorate(Type)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ")" ":" "void" Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ")" ":" "void" "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ")" ":" Type Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ")" ":" Type "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ParametersFunction ")" ":" "void" Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		...Decorate(ParametersFunction)
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ParametersFunction ")" ":" "void" "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		...Decorate(ParametersFunction)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ParametersFunction ")" ":" Type Block<-Break><+Return>) -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		...Decorate(ParametersFunction)
		Decorate(Type)
		Decorate(Block<-Break><+Return>)
	);
Decorate(DeclarationFunction ::= "func" IDENTIFIER "(" ParametersFunction ")" ":" Type "=>" Expression<+Block><-Break><+Return> ";") -> SemanticDeclarationFunction
	:= (SemanticDeclarationFunction[id=TokenWorth(IDENTIFIER)]
		...Decorate(ParametersFunction)
		Decorate(Type)
		Decorate(Parse("{" "return" Expression<+Block><-Break><+Return> ";" "}"))
	);



Decorate(Declaration<Break, Return> ::= DeclarationType) -> SemanticDeclarationType
	:= Decorate(DeclarationType);
Decorate(Declaration<Break, Return> ::= DeclarationVariable<?Break><?Return>) -> SemanticDeclarationVariable
	:= Decorate(DeclarationVariable<?Break><?Return>);
Decorate(Declaration<Break, Return> ::= DeclarationFunction) -> SemanticDeclarationFunction
	:= Decorate(DeclarationFunction);



Decorate(SourceFile ::= #x02 #x03) -> SemanticGoal
	:= (SemanticGoal);
Decorate(SourceFile ::= #x02 Block<-Break><-Return> #x03) -> SemanticGoal
	:= (SemanticGoal
		Decorate(Block<-Break><-Return>)
	);



ParseList(ParseNode, AstNode)(ParseNode__List ::= ParseNode) -> Sequence<AstNode>
	:= [Decorate(ParseNode)];
ParseList(ParseNode, AstNode)(ParseNode__List ::= ParseNode__List ("," | "|")? ParseNode) -> Sequence<AstNode>
	:= [
		...Decorate(ParseNode__List),
		Decorate(ParseNode),
	];



TokenId(KeywordType  ::= "nothing")  -> TokenWorth("nothing");
TokenId(KeywordType  ::= "bool")     -> TokenWorth("bool");
TokenId(KeywordType  ::= "sym")      -> TokenWorth("sym");
TokenId(KeywordType  ::= "int")      -> TokenWorth("int");
TokenId(KeywordType  ::= "nat")      -> TokenWorth("nat");
TokenId(KeywordType  ::= "float")    -> TokenWorth("float");
TokenId(KeywordType  ::= "str")      -> TokenWorth("str");
TokenId(KeywordType  ::= "anything") -> TokenWorth("anything");
TokenId(KeywordValue ::= "null")     -> TokenWorth("null");
TokenId(KeywordValue ::= "false")    -> TokenWorth("false");
TokenId(KeywordValue ::= "true")     -> TokenWorth("true");



KeywordType(KeywordType ::= "nothing")  -> Type := Nothing;
KeywordType(KeywordType ::= "bool")     -> Type := Boolean;
KeywordType(KeywordType ::= "sym")      -> Type := Symbol;
KeywordType(KeywordType ::= "int")      -> Type := Integer;
KeywordType(KeywordType ::= "nat")      -> Type := Natural;
KeywordType(KeywordType ::= "float")    -> Type := Float;
KeywordType(KeywordType ::= "str")      -> Type := String;
KeywordType(KeywordType ::= "anything") -> Type := Anything;



KeywordValue(KeywordValue ::= "null")  -> Object := null;
KeywordValue(KeywordValue ::= "false") -> Object := false;
KeywordValue(KeywordValue ::= "true")  -> Object := true;
