_KEYWORD_OTHER =:=
	// operator
		| "mut"
		| "as"
		| "is"
		| "if"
		| "then"
		| "else"
	// storage
		| "type"
		| "val"
		| "claim"
		| "set"
		| "_"
		| "void"
	// modifier
		| "nominal"
	// control
		| "unless"
		| "while"
		| "until"
		| "for"
		| "in"
		| "do"
		| "break"
		| "skip"
;

Decorate(Word ::= _KEYWORD_OTHER) -> SemanticKey
	:= (SemanticKey[id=TokenWorth(_KEYWORD_OTHER)]);
Decorate(Word ::= IDENTIFIER) -> SemanticKey
	:= (SemanticKey[id=TokenWorth(IDENTIFIER)]);
Decorate(Word ::= KeywordType) -> SemanticKey
	:= (SemanticKey[id=TokenId(KeywordType)]);
Decorate(Word ::= KeywordValue) -> SemanticKey
	:= (SemanticKey[id=TokenId(KeywordValue)]);



Decorate(PrimitiveLiteral ::= INTEGER) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Integer(TokenWorth(INTEGER))]);
Decorate(PrimitiveLiteral ::= NATURAL) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Natural(TokenWorth(NATURAL))]);
Decorate(PrimitiveLiteral ::= FLOAT) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Float(TokenWorth(FLOAT))]);
Decorate(PrimitiveLiteral ::= STRING) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=String(TokenWorth(STRING))]);
Decorate(PrimitiveLiteral ::= KeywordValue) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=KeywordValue(KeywordValue)]);
Decorate(PrimitiveLiteral ::= "@" Word) -> SemanticExpressionConstant
	:= (SemanticExpressionConstant[value=Symbol(Decorate(Word).id)]);



Decorate(EntryType<-Named><-Optional> ::= Type) -> SemanticItemType
	:= (SemanticItemType[optional=false] Decorate(Type));
Decorate(EntryType<-Named><+Optional> ::= "?:" Type) -> SemanticItemType
	:= (SemanticItemType[optional=true] Decorate(Type));
Decorate(EntryType<+Named><-Optional> ::= Word ":" Type) -> SemanticPropertyType
	:= (SemanticPropertyType[optional=false]
		Decorate(Word)
		Decorate(Type)
	);
Decorate(EntryType<+Named><+Optional> ::= Word "?:" Type) -> SemanticPropertyType
	:= (SemanticPropertyType[optional=true]
		Decorate(Word)
		Decorate(Type)
	);



Decorate(ItemsType ::= ","? EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= ParseList(EntryType<-Named><+Optional>, SemanticItemType);
Decorate(ItemsType ::= EntryType<-Named><-Optional> ",") -> Sequence<SemanticItemType>
	:= [Decorate(EntryType<-Named><-Optional>)];
Decorate(ItemsType ::= EntryType<-Named><-Optional> "," EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= [
		Decorate(EntryType<-Named><-Optional>),
		...ParseList(EntryType<-Named><+Optional>, SemanticItemType),
	];
Decorate(ItemsType ::= "," EntryType<-Named><-Optional># ","?) -> Sequence<SemanticItemType>
	:= ParseList(EntryType<-Named><-Optional>, SemanticItemType);
Decorate(ItemsType ::= "," EntryType<-Named><-Optional># "," EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= [
		...ParseList(EntryType<-Named><-Optional>, SemanticItemType),
		...ParseList(EntryType<-Named><+Optional>, SemanticItemType),
	];
Decorate(ItemsType ::= EntryType<-Named><-Optional>__0 "," EntryType<-Named><-Optional>__1# ","?) -> Sequence<SemanticItemType>
	:= [
		Decorate(EntryType<-Named><-Optional>__0),
		...ParseList(EntryType<-Named><-Optional>__1, SemanticItemType),
	];
Decorate(ItemsType ::= EntryType<-Named><-Optional>__0 "," EntryType<-Named><-Optional>__1# "," EntryType<-Named><+Optional># ","?) -> Sequence<SemanticItemType>
	:= [
		Decorate(EntryType<-Named><-Optional>__0),
		...ParseList(EntryType<-Named><-Optional>__1, SemanticItemType),
		...ParseList(EntryType<-Named><+Optional>,    SemanticItemType),
	];



Decorate(PropertiesType ::= ","? EntryType<+Named><-Optional># ","?) -> Sequence<SemanticPropertyType>
	:= ParseList(EntryType<+Named><-Optional>, SemanticPropertyType);
Decorate(PropertiesType ::= ","? EntryType<+Named><+Optional># ","?) -> Sequence<SemanticPropertyType>
	:= ParseList(EntryType<+Named><+Optional>, SemanticPropertyType);



Decorate(PropertyAccessorType ::= INTEGER) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(INTEGER)]);
Decorate(PropertyAccessorType ::= NATURAL) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(NATURAL)]);
Decorate(PropertyAccessorType ::= Word) -> SemanticKey
	:= Decorate(Word);



Decorate(TypeGrouped ::= "(" Type ")") -> SemanticType
	:= Decorate(Type);

Decorate(TypeTupleLiteral ::= "(" ")") -> SemanticTypeTuple
	:= (SemanticTypeTuple);
Decorate(TypeTupleLiteral ::= "(" ItemsType ")") -> SemanticTypeTuple
	:= (SemanticTypeTuple
		...Decorate(ItemsType)
	);

Decorate(TypeRecordLiteral ::= "(" PropertiesType ")") -> SemanticTypeRecord
	:= (SemanticTypeRecord
		...Decorate(PropertiesType)
	);

Decorate(TypeListLiteral ::= "[" Type "]") -> SemanticTypeList
	:= (SemanticTypeList
		...Decorate(Type)
	);

Decorate(TypeDictLiteral ::= "[" ":" Type "]") -> SemanticTypeDict
	:= (SemanticTypeDict
		Decorate(Type)
	);

Decorate(TypeSetLiteral ::= "{" Type "}") -> SemanticTypeSet
	:= (SemanticTypeSet
		...Decorate(Type)
	);

Decorate(TypeMapLiteral ::= "{" Type__0 "->" Type__1 "}") -> SemanticTypeMap
	:= (SemanticTypeMap
		Decorate(Type__0)
		Decorate(Type__1)
	);

Decorate(GenericArguments ::= "<" ","? Type# ","? ">") -> Sequence<SemanticType>
	:= ParseList(Type, SemanticType);



Decorate(TypeUnit ::= IDENTIFIER) -> SemanticTypeAlias
	:= (SemanticTypeAlias[id=TokenWorth(IDENTIFIER)]);
Decorate(TypeUnit ::= KeywordType) -> SemanticTypeConstant
	:= (SemanticTypeConstant[value=KeywordType(KeywordType)]);
Decorate(TypeUnit ::= PrimitiveLiteral) -> SemanticTypeConstant
	:= (SemanticTypeConstant[value=ToType(Decorate(PrimitiveLiteral).value)]);
Decorate(TypeUnit ::= TypeGrouped) -> SemanticType
	:= Decorate(TypeGrouped);
Decorate(TypeUnit ::= TypeTupleLiteral) -> SemanticTypeTuple
	:= Decorate(TypeTupleLiteral);
Decorate(TypeUnit ::= TypeRecordLiteral) -> SemanticTypeRecord
	:= Decorate(TypeRecordLiteral);
Decorate(TypeUnit ::= TypeListLiteral) -> SemanticTypeList
	:= Decorate(TypeListLiteral);
Decorate(TypeUnit ::= TypeDictLiteral) -> SemanticTypeDict
	:= Decorate(TypeDictLiteral);
Decorate(TypeUnit ::= TypeSetLiteral) -> SemanticTypeSet
	:= Decorate(TypeSetLiteral);
Decorate(TypeUnit ::= TypeMapLiteral) -> SemanticTypeMap
	:= Decorate(TypeMapLiteral);



Decorate(TypeCompound ::= TypeUnit) -> SemanticType
	:= Decorate(TypeUnit);
Decorate(TypeCompound ::= TypeCompound "." PropertyAccessorType) -> SemanticTypeAccess
	:= (SemanticTypeAccess[kind=NORMAL]
		Decorate(TypeCompound)
		Decorate(PropertyAccessorType)
	);
Decorate(TypeCompound ::= TypeCompound "?." PropertyAccessorType) -> SemanticTypeAccess
	:= (SemanticTypeAccess[kind=MAYBE]
		Decorate(TypeCompound)
		Decorate(PropertyAccessorType)
	);
Decorate(TypeCompound ::= TypeCompound "." GenericArguments) -> SemanticTypeCall
	:= (SemanticTypeCall
		Decorate(TypeCompound)
		...Decorate(GenericArguments)
	);



Decorate(TypeUnarySymbol ::= TypeCompound) -> SemanticType
	:= Decorate(TypeCompound);
Decorate(TypeUnarySymbol ::= TypeUnarySymbol "?") -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=MAYBE]
		Decorate(TypeUnarySymbol)
	);
Decorate(TypeUnarySymbol ::= TypeUnarySymbol "!") -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=RESULT]
		Decorate(TypeUnarySymbol)
	);



Decorate(TypeUnaryKeyword ::= TypeUnarySymbol) -> SemanticType
	:= Decorate(TypeUnarySymbol);
Decorate(TypeUnaryKeyword ::= "mut" TypeUnaryKeyword) -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=MUTABLE]
		Decorate(TypeUnaryKeyword)
	);



Decorate(TypeIntersection ::= TypeUnaryKeyword) -> SemanticType
	:= Decorate(TypeUnaryKeyword);
Decorate(TypeIntersection ::= TypeIntersection "&" TypeUnaryKeyword) -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=AND]
		Decorate(TypeIntersection)
		Decorate(TypeUnaryKeyword)
	);



Decorate(TypeUnion ::= TypeIntersection) -> SemanticType
	:= Decorate(TypeIntersection);
Decorate(TypeUnion ::= TypeUnion "|" TypeIntersection) -> SemanticTypeOperation
	:= (SemanticTypeOperation[operator=OR]
		Decorate(TypeUnion)
		Decorate(TypeIntersection)
	);



Decorate(Type ::= TypeUnion) -> SemanticType
	:= Decorate(TypeUnion);



Decorate(StringTemplate<Break> ::= TEMPLATE_FULL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_FULL))])
	);
Decorate(StringTemplate<Break> ::= TEMPLATE_HEAD TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);
Decorate(StringTemplate<Break> ::= TEMPLATE_HEAD Expression<+Block><?Break> TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		Decorate(Expression<+Block><?Break>)
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);
Decorate(StringTemplate<Break> ::= TEMPLATE_HEAD StringTemplate__0__List TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		...Decorate(StringTemplate__0__List)
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);
Decorate(StringTemplate<Break> ::= TEMPLATE_HEAD Expression<+Block><?Break> StringTemplate__0__List TEMPLATE_TAIL) -> SemanticExpressionTemplate
	:= (SemanticExpressionTemplate
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_HEAD))])
		Decorate(Expression<+Block><?Break>)
		...Decorate(StringTemplate__0__List)
		(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_TAIL))])
	);

	Decorate(StringTemplate__0__List<Break> ::= TEMPLATE_MIDDLE) -> Vector<SemanticExpressionConstant>
		:= [SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]];
	Decorate(StringTemplate__0__List<Break> ::= TEMPLATE_MIDDLE Expression<+Block><?Break>) -> Vector<SemanticExpressionConstant, SemanticExpression>
		:= [
			(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]),
			Decorate(Expression<+Block><?Break>),
		];
	Decorate(StringTemplate__0__List<Break> ::= StringTemplate__0__List TEMPLATE_MIDDLE) -> Sequence<...Vector<SemanticExpressionConstant, SemanticExpression?>>
		:= [
			...Decorate(StringTemplate__0__List),
			(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]),
		];
	Decorate(StringTemplate__0__List<Break> ::= StringTemplate__0__List TEMPLATE_MIDDLE Expression<+Block><?Break>) -> Sequence<...Vector<SemanticExpressionConstant, SemanticExpression?>>
		:= [
			...Decorate(StringTemplate__0__List),
			(SemanticExpressionConstant[value=String(TokenWorth(TEMPLATE_MIDDLE))]),
			Decorate(Expression<+Block><?Break>),
		];



Decorate(Items<Break> ::= Expression<+Block><?Break> ",") -> Sequence<SemanticExpression>
	:= [Decorate(Expression<+Block><?Break>)];
Decorate(Items<Break> ::= "," Expression<+Block><?Break># ","?) -> Sequence<SemanticExpression>
	:= ParseList(Expression<+Block><?Break>, SemanticExpression);
Decorate(Items<Break> ::= Expression__0<+Block><?Break> "," Expression__1<+Block><?Break># ","?) -> Sequence<SemanticExpression>
	:= [
		Decorate(Expression__0<+Block><?Break>),
		...ParseList(Expression__1<+Block><?Break>, SemanticExpression),
	];

Decorate(Property<Break> ::= Word "=" Expression<+Block><?Break>) -> SemanticProperty
	:= (SemanticProperty
		Decorate(Word)
		Decorate(Expression<+Block><?Break>)
	);

Decorate(CaseMap<Break> ::= Expression__0<+Block><?Break> "->" Expression__1<+Block><?Break>) -> SemanticCase
	:= (SemanticCase
		Decorate(Expression__0<+Block><?Break>)
		Decorate(Expression__1<+Block><?Break>)
	);

Decorate(CaseSwitch<Break> ::= "case" Expression__0<+Block><?Break> "->" Expression__1<+Block><?Break>) -> SemanticCase
	:= (SemanticCase
		Decorate(Expression__0<+Block><?Break>)
		Decorate(Expression__1<+Block><?Break>)
	);
Decorate(CaseSwitch<Break> ::= "case" (Expression__0<+Block><?Break> "|")+ Expression__1<+Block><?Break> "->" Expression__2<+Block><?Break>) -> SemanticCase
	:= (SemanticCase
		...ParseList((Expression__0<+Block><?Break> "|")+ Expression__1<+Block><?Break> =:: Expression<+Block><?Break>__List "|" Expression<+Block><?Break>, SemanticExpression)
		Decorate(Expression__2<+Block><?Break>)
	);



Decorate(PropertyAccessor<Break> ::= INTEGER) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(INTEGER)]);
Decorate(PropertyAccessor<Break> ::= NATURAL) -> SemanticIndex
	:= (SemanticIndex[index=TokenWorth(NATURAL)]);
Decorate(PropertyAccessor<Break> ::= Word) -> SemanticKey
	:= Decorate(Word);
Decorate(PropertyAccessor<Break> ::= "[" Expression<+Block><?Break> "]") -> SemanticExpression
	:= Decorate(Expression<+Block><-Break>);



Decorate(ExpressionGrouped<Break> ::= "(" Expression<+Block><?Break> ")") -> SemanticExpression
	:= Decorate(Expression<+Block><?Break>);

Decorate(ExpressionTupleLiteral<Break> ::= "(" ")") -> SemanticExpressionTuple
	:= (SemanticExpressionTuple);
Decorate(ExpressionTupleLiteral<Break> ::= "(" Items<?Break> ")") -> SemanticExpressionTuple
	:= (SemanticExpressionTuple
		...Decorate(Items<?Break>)
	);

Decorate(ExpressionRecordLiteral<Break> ::= "(" ","? Property<?Break># ","? ")") -> SemanticExpressionRecord
	:= (SemanticExpressionRecord
		...ParseList(Property<?Break>, SemanticProperty)
	);

Decorate(ExpressionListLiteral<Break> ::= "[" "]") -> SemanticExpressionList
	:= (SemanticExpressionList);
Decorate(ExpressionListLiteral<Break> ::= "[" (","? Expression<+Block><?Break># ","?)? "]") -> SemanticExpressionList
	:= (SemanticExpressionList
		...ParseList(Expression<+Block><?Break>, SemanticExpression)
	);

Decorate(ExpressionDictLiteral<Break> ::= [" ","? Property<?Break># ","? "]") -> SemanticExpressionDict
	:= (SemanticExpressionDict
		...ParseList(Property<?Break>, SemanticProperty)
	);

Decorate(ExpressionSetLiteral<Break> ::= "{" "}") -> SemanticExpressionSet
	:= (SemanticExpressionSet);
Decorate(ExpressionSetLiteral<Break> ::= "{" (","? Expression<+Block><?Break># ","?)? "}") -> SemanticExpressionSet
	:= (SemanticExpressionSet
		...ParseList(Expression<+Block><?Break>, SemanticExpression)
	);

Decorate(ExpressionMapLiteral<Break> ::= "{" ","? CaseMap<?Break># ","? "}") -> SemanticExpressionMap
	:= (SemanticExpressionMap
		...ParseList(CaseMap<?Break>, SemanticCase)
	);

Decorate(FunctionArguments<Break> ::= "(" (","? Expression<+Block><?Break># ","?)? ")") -> Sequence<SemanticExpression>
	:= ParseList(Expression<+Block><?Break>, SemanticExpression);



Decorate(ExpressionUnit<Block, Break> ::= IDENTIFIER) -> SemanticExpressionVariable
	:= (SemanticExpressionVariable[id=TokenWorth(IDENTIFIER)]);
Decorate(ExpressionUnit<Block, Break> ::= PrimitiveLiteral) -> SemanticExpressionConstant
	:= Decorate(PrimitiveLiteral);
Decorate(ExpressionUnit<Block, Break> ::= StringTemplate<?Break>) -> SemanticExpressionTemplate
	:= Decorate(StringTemplate<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= ExpressionGrouped<?Break>) -> SemanticExpression
	:= Decorate(ExpressionGrouped<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= ExpressionTupleLiteral<?Break>) -> SemanticExpressionTuple
	:= Decorate(ExpressionTupleLiteral<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= ExpressionRecordLiteral<?Break>) -> SemanticExpressionRecord
	:= Decorate(ExpressionRecordLiteral<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= ExpressionListLiteral<?Break>) -> SemanticExpressionList
	:= Decorate(ExpressionListLiteral<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= ExpressionDictLiteral<?Break>) -> SemanticExpressionDict
	:= Decorate(ExpressionDictLiteral<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= ExpressionSetLiteral<?Break>) -> SemanticExpressionSet
	:= Decorate(ExpressionSetLiteral<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= ExpressionMapLiteral<?Break>) -> SemanticExpressionMap
	:= Decorate(ExpressionMapLiteral<?Break>);
Decorate(ExpressionUnit<Block, Break> ::= Block<?Break>) -> SemanticExpressionBlock
	:= (SemanticExpressionBlock Decorate(Block<?Break>));



Decorate(ExpressionCompound<Block, Break> ::= ExpressionUnit<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionUnit<?Block><?Break>);
Decorate(ExpressionCompound<Block, Break> ::= ExpressionCompound<?Block><?Break> "~?") -> SemanticExpressionAccess
	:=; // TODO:
Decorate(ExpressionCompound<Block, Break> ::= ExpressionCompound<?Block><?Break> "~!") -> SemanticExpressionAccess
	:=; // TODO:
Decorate(ExpressionCompound<Block, Break> ::= ExpressionCompound<?Block><?Break> "." PropertyAccessor<?Break>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=NORMAL]
		Decorate(ExpressionCompound<?Block><?Break>)
		Decorate(PropertyAccessor<?Break>)
	);
Decorate(ExpressionCompound<Block, Break> ::= ExpressionCompound<?Block><?Break> "?." PropertyAccessor<?Break>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=MAYBE]
		Decorate(ExpressionCompound<?Block><?Break>)
		Decorate(PropertyAccessor<?Break>)
	);
Decorate(ExpressionCompound<Block, Break> ::= ExpressionCompound<?Block><?Break> "!." PropertyAccessor<?Break>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=RESULT]
		Decorate(ExpressionCompound<?Block><?Break>)
		Decorate(PropertyAccessor<?Break>)
	);
Decorate(ExpressionCompound<Block, Break> ::= ExpressionCompound<?Block><?Break> "." FunctionArguments<?Break>) -> SemanticExpressionCall
	:= (SemanticExpressionCall
		Decorate(ExpressionCompound<?Block><?Break>)
		...Decorate(FunctionArguments<?Break>)
	);
Decorate(ExpressionCompound<Block, Break> ::= ExpressionCompound<?Block><?Break> "." GenericArguments FunctionArguments<?Break>) -> SemanticExpressionCall
	:= (SemanticExpressionCall
		Decorate(ExpressionCompound<?Block><?Break>)
		...Decorate(GenericArguments)
		...Decorate(FunctionArguments<?Break>)
	);



Decorate(ExpressionUnarySymbol<Block, Break> ::= ExpressionCompound<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionCompound<?Block><?Break>);
Decorate(ExpressionUnarySymbol<Block, Break> ::= "!" ExpressionUnarySymbol<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		Decorate(ExpressionUnarySymbol<?Block><?Break>)
	);
Decorate(ExpressionUnarySymbol<Block, Break> ::= "?" ExpressionUnarySymbol<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=EMP]
		Decorate(ExpressionUnarySymbol<?Block><?Break>)
	);
Decorate(ExpressionUnarySymbol<Block, Break> ::= "+" ExpressionUnarySymbol<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionUnarySymbol<?Block><?Break>);
Decorate(ExpressionUnarySymbol<Block, Break> ::= "-" ExpressionUnarySymbol<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NEG]
		Decorate(ExpressionUnarySymbol<?Block><?Break>)
	);



Decorate(ExpressionUnaryKeyword<Block, Break> ::= ExpressionUnarySymbol<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionUnarySymbol<?Block><?Break>);
Decorate(ExpressionUnaryKeyword<Block, Break> ::= "isset" Assignee<?Break>) -> SemanticExpressionIsset
	:= (SemanticExpressionIsset
		Decorate(Assignee<?Break>)
	);
Decorate(ExpressionUnaryKeyword<Block, Break> ::= "!isset" Assignee<?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionIsset
			Decorate(Assignee<?Break>)
		)
	);



Decorate(ExpressionCast<Block, Break> ::= ExpressionUnaryKeyword<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionUnaryKeyword<?Block><?Break>);
Decorate(ExpressionCast<Block, Break> ::= ExpressionCast<?Block><?Break> "as" ExpressionUnaryKeyword<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=CAST]
		Decorate(ExpressionCast<?Block><?Break>)
		Decorate(ExpressionUnaryKeyword<?Block><?Break>)
	);
Decorate(ExpressionCast<Block, Break> ::= ExpressionCast<?Block><?Break> "as?" ExpressionUnaryKeyword<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=MAYBE]
		Decorate(ExpressionCast<?Block><?Break>)
		Decorate(ExpressionUnaryKeyword<?Block><?Break>)
	);
Decorate(ExpressionCast<Block, Break> ::= ExpressionCast<?Block><?Break> "as!" ExpressionUnaryKeyword<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=RESULT]
		Decorate(ExpressionCast<?Block><?Break>)
		Decorate(ExpressionUnaryKeyword<?Block><?Break>)
	);
Decorate(ExpressionCast<Block, Break> ::= ExpressionCast<?Block><?Break> "as" "<" Type ">") -> SemanticExpressionClaim
	:= (SemanticExpressionClaim
		Decorate(ExpressionCast<?Block><?Break>)
		Decorate(Type)
	);



Decorate(ExpressionExponential<Block, Break> ::= ExpressionCast<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionCast<?Block><?Break>);
Decorate(ExpressionExponential<Block, Break> ::= ExpressionCast<?Block><?Break> "^" ExpressionExponential<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=EXP]
		Decorate(ExpressionCast<?Block><?Break>)
		Decorate(ExpressionExponential<?Block><?Break>)
	);



Decorate(ExpressionMultiplicative<Block, Break> ::= ExpressionExponential<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionExponential<?Block><?Break>);
Decorate(ExpressionMultiplicative<Block, Break> ::= ExpressionMultiplicative<?Block><?Break> "*" ExpressionExponential<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=MUL]
		Decorate(ExpressionMultiplicative<?Block><?Break>)
		Decorate(ExpressionExponential<?Block><?Break>)
	);
Decorate(ExpressionMultiplicative<Block, Break> ::= ExpressionMultiplicative<?Block><?Break> "/" ExpressionExponential<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=DIV]
		Decorate(ExpressionMultiplicative<?Block><?Break>)
		Decorate(ExpressionExponential<?Block><?Break>)
	);



Decorate(ExpressionAdditive<Block, Break> ::= ExpressionMultiplicative<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionMultiplicative<?Block><?Break>);
Decorate(ExpressionAdditive<Block, Break> ::= ExpressionAdditive<?Block><?Break> "+" ExpressionMultiplicative<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=ADD]
		Decorate(ExpressionAdditive<?Block><?Break>)
		Decorate(ExpressionMultiplicative<?Block><?Break>)
	);
Decorate(ExpressionAdditive<Block, Break> ::= ExpressionAdditive<?Block><?Break> "-" ExpressionMultiplicative<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=SUB]
		Decorate(ExpressionAdditive<?Block><?Break>)
		Decorate(ExpressionMultiplicative<?Block><?Break>)
	);



Decorate(ExpressionComparative<Block, Break> ::= ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= Decorate(ExpressionAdditive<?Block><?Break>);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> "<" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=LT]
		Decorate(ExpressionComparative<?Block><?Break>)
		Decorate(ExpressionAdditive<?Block><?Break>)
	);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> ">" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=GT]
		Decorate(ExpressionComparative<?Block><?Break>)
		Decorate(ExpressionAdditive<?Block><?Break>)
	);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> "<=" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=LE]
		Decorate(ExpressionComparative<?Block><?Break>)
		Decorate(ExpressionAdditive<?Block><?Break>)
	);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> ">=" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=GE]
		Decorate(ExpressionComparative<?Block><?Break>)
		Decorate(ExpressionAdditive<?Block><?Break>)
	);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> "!<" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=LT]
			Decorate(ExpressionComparative<?Block><?Break>)
			Decorate(ExpressionAdditive<?Block><?Break>)
		)
	);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> "!>" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=GT]
			Decorate(ExpressionComparative<?Block><?Break>)
			Decorate(ExpressionAdditive<?Block><?Break>)
		)
	);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> "is" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=IS]
		Decorate(ExpressionComparative<?Block><?Break>)
		Decorate(ExpressionAdditive<?Block><?Break>)
	);
Decorate(ExpressionComparative<Block, Break> ::= ExpressionComparative<?Block><?Break> "!is" ExpressionAdditive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=IS]
			Decorate(ExpressionComparative<?Block><?Break>)
			Decorate(ExpressionAdditive<?Block><?Break>)
		)
	);



Decorate(ExpressionEquality<Block, Break> ::= ExpressionComparative<?Block><?Break>) -> SemanticExpressionOperation
	:= Decorate(ExpressionComparative<?Block>);
Decorate(ExpressionEquality<Block, Break> ::= ExpressionEquality<?Block><?Break> "===" ExpressionComparative<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=ID]
		Decorate(ExpressionEquality<?Block><?Break>)
		Decorate(ExpressionComparative<?Block><?Break>)
	);
Decorate(ExpressionEquality<Block, Break> ::= ExpressionEquality<?Block><?Break> "!==" ExpressionComparative<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=ID]
			Decorate(ExpressionEquality<?Block><?Break>)
			Decorate(ExpressionComparative<?Block><?Break>)
		)
	);
Decorate(ExpressionEquality<Block, Break> ::= ExpressionEquality<?Block><?Break> "==" ExpressionComparative<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=EQ]
		Decorate(ExpressionEquality<?Block><?Break>)
		Decorate(ExpressionComparative<?Block><?Break>)
	);
Decorate(ExpressionEquality<Block, Break> ::= ExpressionEquality<?Block><?Break> "!=" ExpressionComparative<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=EQ]
			Decorate(ExpressionEquality<?Block><?Break>)
			Decorate(ExpressionComparative<?Block><?Break>)
		)
	);



Decorate(ExpressionConjunctive<Block, Break> ::= ExpressionEquality<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionEquality<?Block><?Break>);
Decorate(ExpressionConjunctive<Block, Break> ::= ExpressionConjunctive<?Block><?Break> "&&" ExpressionEquality<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=AND]
		Decorate(ExpressionConjunctive<?Block><?Break>)
		Decorate(ExpressionEquality<?Block><?Break>)
	);
Decorate(ExpressionConjunctive<Block, Break> ::= ExpressionConjunctive<?Block><?Break> "!&" ExpressionEquality<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=AND]
			Decorate(ExpressionConjunctive<?Block><?Break>)
			Decorate(ExpressionEquality<?Block><?Break>)
		)
	);



Decorate(ExpressionDisjunctive<Block, Break> ::= ExpressionConjunctive<?Block><?Break>) -> SemanticExpressionOperation
	:= Decorate(ExpressionConjunctive<?Block><?Break>);
Decorate(ExpressionDisjunctive<Block, Break> ::= ExpressionDisjunctive<?Block><?Break> "||" ExpressionConjunctive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=OR]
		Decorate(ExpressionDisjunctive<?Block><?Break>)
		Decorate(ExpressionConjunctive<?Block><?Break>)
	);
Decorate(ExpressionDisjunctive<Block, Break> ::= ExpressionDisjunctive<?Block><?Break> "!|" ExpressionConjunctive<?Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=NOT]
		(SemanticExpressionOperation[operator=OR]
			Decorate(ExpressionDisjunctive<?Block><?Break>)
			Decorate(ExpressionConjunctive<?Block><?Break>)
		)
	);



Decorate(ExpressionConditional<Break> ::= "if" Expression__0<+Block><?Break> "then" Expression__1<-Block><?Break> "else" Expression__2<-Block><?Break>) -> SemanticExpressionOperation
	:= (SemanticExpressionOperation[operator=COND]
		Decorate(Expression__0<+Block><?Break>)
		Decorate(Expression__1<-Block><?Break>)
		Decorate(Expression__2<-Block><?Break>)
	);



Decorate(ExpressionSwitch<Break> ::= "switch" Expression__0<+Block><?Break> "default" Expression__1<+Block><?Break>) -> SemanticExpressionSwitch
	:= (SemanticExpressionSwitch
		Decorate(Expression__0<+Block><?Break>)
		Decorate(Expression__1<+Block><?Break>)
	);
Decorate(ExpressionSwitch<Break> ::= "switch" Expression__0<+Block><?Break> CaseSwitch<?Break>+ "default" Expression__1<+Block><?Break>) -> SemanticExpressionSwitch
	:= (SemanticExpressionSwitch
		Decorate(Expression__0<+Block><?Break>)
		...ParseList(CaseSwitch<?Break>, SemanticCase)
		Decorate(Expression__1<+Block><?Break>)
	);



Decorate(Expression<Block, Break> ::= ExpressionDisjunctive<?Block><?Break>) -> SemanticExpression
	:= Decorate(ExpressionDisjunctive<?Block><?Break>);
Decorate(Expression<Block, Break> ::= ExpressionConditional<?Break>) -> SemanticExpression
	:= Decorate(ExpressionConditional<?Break>);
Decorate(Expression<Block, Break> ::= ExpressionSwitch<?Break>) -> SemanticExpression
	:= Decorate(ExpressionSwitch<?Break>);



Decorate(Assignee<Break> ::= IDENTIFIER) -> SemanticExpressionVariable
	:= (SemanticExpressionVariable[id=TokenWorth(IDENTIFIER)]);
Decorate(Assignee<Break> ::= ExpressionCompound<+Block><?Break> "." PropertyAccessor<?Break>) -> SemanticExpressionAccess
	:= (SemanticExpressionAccess[kind=NORMAL]
		Decorate(ExpressionCompound<+Block><?Break>)
		Decorate(PropertyAccessor<?Break>)
	);



Decorate(StatementExpression<Break> ::= ";") -> SemanticStatementExpression
	:= (SemanticStatementExpression);
Decorate(StatementExpression<Break> ::= Expression<+Block><?Break> ";") -> SemanticStatementExpression
	:= (SemanticStatementExpression Decorate(Expression<+Block><?Break>));



Decorate(StatementClaim<Break> ::= "claim" Assignee<?Break> ":" Type ";") -> SemanticStatementClaim
	:= (SemanticStatementClaim
		Decorate(Assignee<?Break>)
		Decorate(Type)
	);



Decorate(StatementSet<Break> ::= "set" Assignee<?Break> "=" Expression<+Block><?Break> ";") -> SemanticStatementReassignment
	:= (SemanticStatementReassignment
		Decorate(Assignee<?Break>)
		Decorate(Expression<+Block><?Break>)
	);



Decorate(StatementDelete<Break> ::= "delete" Assignee<?Break> ";") -> SemanticStatementReassignment
	:= (SemanticStatementReassignment
		Decorate(Assignee<?Break>)
	);



Decorate(StatementConditional<Unless, Break> ::= "if" Expression<+Block><?Break> "then" Block<?Break> ";") -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=false]
		Decorate(Expression<+Block><?Break>)
		Decorate(Block<?Break>)
	);
Decorate(StatementConditional<Unless, Break> ::= "if" Expression<+Block><?Break> "then" Block__0<?Break> "else" Block__1<?Break> ";") -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=false]
		Decorate(Expression<+Block><?Break>)
		Decorate(Block__0<?Break>)
		Decorate(Block__1<?Break>)
	);
Decorate(StatementConditional<Unless, Break> ::= "if" Expression<+Block><?Break> "then" Block<?Break> "else" StatementConditional<-Unless><?Break>) -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=false]
		Decorate(Expression<+Block><?Break>)
		Decorate(Block<?Break>)
		Decorate(StatementConditional<-Unless><?Break>)
	);
Decorate(StatementConditional<Unless, Break> ::= "unless" Expression<+Block><?Break> "then" Block<?Break> ";") -> SemanticStatementConditional
	:= (SemanticStatementConditional[unless=true]
		Decorate(Expression<+Block><?Break>)
		Decorate(Block<?Break>)
	);



Decorate(StatementLoop ::= "while" Expression<+Block><-Break> "do" Block<+Break> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=false][until=false]
		Decorate(Expression<+Block><-Break>)
		Decorate(Block<+Break>)
	);
Decorate(StatementLoop ::= "do" Block<+Break> "while" Expression<+Block><-Break> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=true][until=false]
		Decorate(Expression<+Block><-Break>)
		Decorate(Block<+Break>)
	);
Decorate(StatementLoop ::= "until" Expression<+Block><-Break> "do" Block<+Break> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=false][until=true]
		Decorate(Expression<+Block><-Break>)
		Decorate(Block<+Break>)
	);
Decorate(StatementLoop ::= "do" Block<+Break> "until" Expression<+Block><-Break> ";") -> SemanticStatementLoop
	:= (SemanticStatementLoop[doFirst=true][until=true]
		Decorate(Expression<+Block><-Break>)
		Decorate(Block<+Break>)
	);



Decorate(StatementIteration ::= "for" "_" ":" Type "in" Expression<+Block><+Break> "do" Block<+Break> ";") -> SemanticStatementIteration
	:= (SemanticStatementIteration
		(SemanticType     Decorate(Type))
		(SemanticIterable Decorate(Expression<+Block><+Break>))
		Decorate(Block<+Break>)
	);
Decorate(StatementIteration ::= "for" IDENTIFIER ":" Type "in" Expression<+Block><+Break> "do" Block<+Break> ";") -> SemanticStatementIteration
	:= (SemanticStatementIteration[id=TokenWorth(IDENTIFIER)]
		(SemanticType     Decorate(Type))
		(SemanticIterable Decorate(Expression<+Block><+Break>))
		Decorate(Block<+Break>)
	);



Decorate(StatementBreak ::= "break" ";") -> SemanticStatementBreak
	:= (SemanticStatementBreak[skip=false]);
Decorate(StatementBreak ::= "skip" ";") -> SemanticStatementBreak
	:= (SemanticStatementBreak[skip=true]);



Decorate(Statement<Break> ::= Declaration<?Break>) -> SemanticDeclaration
	:= Decorate(Declaration<?Break>);
Decorate(Statement<Break> ::= StatementExpression<?Break>) -> SemanticStatementExpression
	:= Decorate(StatementExpression<?Break>);
Decorate(Statement<Break> ::= StatementClaim<?Break>) -> SemanticStatementClaim
	:= Decorate(StatementClaim<?Break>);
Decorate(Statement<Break> ::= StatementSet<?Break>) -> SemanticStatementReassignment
	:= Decorate(StatementSet<?Break>);
Decorate(Statement<Break> ::= StatementDelete<?Break>) -> SemanticStatementReassignment
	:= Decorate(StatementDelete<?Break>);
Decorate(Statement<Break> ::= StatementConditional<∓Unless><?Break>) -> SemanticStatementConditional
	:= Decorate(StatementConditional<∓Unless><?Break>);
Decorate(Statement<Break> ::= StatementLoop) -> SemanticStatementLoop
	:= Decorate(StatementLoop);
Decorate(Statement<Break> ::= StatementIteration) -> SemanticStatementIteration
	:= Decorate(StatementIteration);
Decorate(Statement<Break> ::= StatementBreak) -> SemanticStatementBreak
	:= Decorate(StatementBreak);



Decorate(Block<Break> ::= "{" Statement<?Break>+ "}") -> SemanticBlock
	:= (SemanticBlock
		...ParseList(Statement<?Break>, SemanticStatement)
	);



Decorate(DeclarationType ::= "type" "_" "=" Type ";") -> SemanticDeclarationType
	:= (SemanticDeclarationType
		Decorate(Type)
	);
Decorate(DeclarationType ::= "type" IDENTIFIER "=" Type ";") -> SemanticDeclarationType
	:= (SemanticDeclarationType[id=TokenWorth(IDENTIFIER)]
		Decorate(Type)
	);



Decorate(DeclarationVariable<Break> ::= "val" "_" "=" Expression<+Block><?Break> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=false]
		Decorate(Expression<+Block><?Break>)
	);
Decorate(DeclarationVariable<Break> ::= "val" "_" ":" Type "=" Expression<+Block><?Break> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[writable=false]
		Decorate(Type)
		Decorate(Expression<+Block><?Break>)
	);
Decorate(DeclarationVariable<Break> ::= "val" IDENTIFIER "=" Expression<+Block><?Break> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[id=TokenWorth(IDENTIFIER)][writable=false]
		Decorate(Expression<+Block><?Break>)
	);
Decorate(DeclarationVariable<Break> ::= "val" IDENTIFIER ":" Type "=" Expression<+Block><?Break> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[id=TokenWorth(IDENTIFIER)][writable=false]
		Decorate(Type)
		Decorate(Expression<+Block><?Break>)
	);
Decorate(DeclarationVariable<Break> ::= "val" "mut" IDENTIFIER "=" Expression<+Block><?Break> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[id=TokenWorth(IDENTIFIER)][writable=true]
		Decorate(Expression<+Block><?Break>)
	);
Decorate(DeclarationVariable<Break> ::= "val" "mut" IDENTIFIER ":" Type "=" Expression<+Block><?Break> ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[id=TokenWorth(IDENTIFIER)][writable=true]
		Decorate(Type)
		Decorate(Expression<+Block><?Break>)
	);
Decorate(DeclarationVariable<Break> ::= "val" "mut" IDENTIFIER "?" ":" Type ";") -> SemanticDeclarationVariable
	:= (SemanticDeclarationVariable[id=TokenWorth(IDENTIFIER)][writable=true]
		Decorate(Type)
	);



Decorate(Declaration<Break> ::= DeclarationType) -> SemanticDeclarationType
	:= Decorate(DeclarationType);
Decorate(Declaration<Break> ::= DeclarationVariable<?Break>) -> SemanticDeclarationVariable
	:= Decorate(DeclarationVariable<?Break>);



Decorate(SourceFile ::= #x02 #x03) -> SemanticGoal
	:= (SemanticGoal);
Decorate(SourceFile ::= #x02 Block #x03) -> SemanticGoal
	:= (SemanticGoal
		Decorate(Block)
	);



ParseList(ParseNode, AstNode)(ParseNode__List ::= ParseNode) -> Sequence<AstNode>
	:= [Decorate(ParseNode)];
ParseList(ParseNode, AstNode)(ParseNode__List ::= ParseNode__List ("," | "|")? ParseNode) -> Sequence<AstNode>
	:= [
		...Decorate(ParseNode__List),
		Decorate(ParseNode),
	];



TokenId(KeywordType  ::= "nothing")  -> TokenWorth("nothing");
TokenId(KeywordType  ::= "bool")     -> TokenWorth("bool");
TokenId(KeywordType  ::= "sym")      -> TokenWorth("sym");
TokenId(KeywordType  ::= "int")      -> TokenWorth("int");
TokenId(KeywordType  ::= "nat")      -> TokenWorth("nat");
TokenId(KeywordType  ::= "float")    -> TokenWorth("float");
TokenId(KeywordType  ::= "str")      -> TokenWorth("str");
TokenId(KeywordType  ::= "anything") -> TokenWorth("anything");
TokenId(KeywordValue ::= "null")     -> TokenWorth("null");
TokenId(KeywordValue ::= "false")    -> TokenWorth("false");
TokenId(KeywordValue ::= "true")     -> TokenWorth("true");



KeywordType(KeywordType ::= "nothing")  -> Type := Nothing;
KeywordType(KeywordType ::= "bool")     -> Type := Boolean;
KeywordType(KeywordType ::= "sym")      -> Type := Symbol;
KeywordType(KeywordType ::= "int")      -> Type := Integer;
KeywordType(KeywordType ::= "nat")      -> Type := Natural;
KeywordType(KeywordType ::= "float")    -> Type := Float;
KeywordType(KeywordType ::= "str")      -> Type := String;
KeywordType(KeywordType ::= "anything") -> Type := Anything;



KeywordValue(KeywordValue ::= "null")  -> Object := null;
KeywordValue(KeywordValue ::= "false") -> Object := false;
KeywordValue(KeywordValue ::= "true")  -> Object := true;
