Identifier
	:::= [A-Z] [A-Za-z0-9_]*;

CharCode
	:::= "#x" [0-9a-f]+;

String
	:::= #x22 [^"]* #x22; // U+0022 QUOTATION MARK

Char
	:::= [#x20-#x5c#x5e-#7e]; // excluding U+005D RIGHT SQUARE BRAKET

CharClass
	:::= "[" "^"? (Char | CharCode | Char "-" Char | CharCode "-" CharCode)+ "]";

Comment
	:::= "//" [^#x0a#03]* #x0a;
