Interpret((TRAP)) :=
	1. *Throw:* a new Error.
;

Null Interpret((NULL.CONST `n`)) :=
	1. *Return:* `n`.
;
Boolean Interpret((BOOL.CONST `b`)) :=
	1. *Return:* `b`.
;
Symbol Interpret((SYM.CONST `s`)) :=
	1. *Return:* `s`.
;
Integer Interpret((INT.CONST `i`)) :=
	1. *Return:* `i`.
;
Natural Interpret((NAT.CONST `n`)) :=
	1. *Return:* `n`.
;
Float Interpret((FLOAT.CONST `f`)) :=
	1. *Return:* `f`.
;
String Interpret((STR.CONST `s`)) :=
	1. *Return:* `s`.
;

Value! Interpret((GET `id`)) :=
	1. *If* the interpreter’s symbol table contains `id`:
		1. *Return:* the value stored at `id`.
	2. *Else:*
		1. *Throw:* a new ReferenceError.
;

Value! Interpret((STR.TEMPLATE `values`)) :=
	1. *Let* `values` be a mapping for each `value` in `values` to *Unwrap:* `Interpret(value)`.
	2. *Let* `strings` be a mapping for each `value` in `values` to `String(value)`.
	3. *Return:* the string-concatenation of each item in `strings`, preserving order.
;

Tuple! Interpret((TUPLE.NEW `values`)) :=
	1. *Let* `data` be a mapping of `values` for each `it` to *Unwrap:* `Interpret(it)`.
	2. *Return:* a new Tuple containing the items in `data`.
;

Record! Interpret((RECORD.NEW `pairs`)) :=
	1. *Let* `data` be a new Schema.
	2. *For index* `i` in `pairs`:
		1. Set `data` to a new Schema [
			...data,
			`pairs[i].0`= *Unwrap:* `Interpret(pairs[i].1)`,
		].
	3. *Return:* a new Record containing the properties in `data`.
;

List! Interpret((LIST.NEW `values`)) :=
	1. *Let* `data` be a mapping of `values` for each `it` to *Unwrap:* `Interpret(it)`.
	2. *Return:* a new List containing the items in `data`.
;

Dict! Interpret((DICT.NEW `pairs`)) :=
	1. *Let* `data` be a new Schema.
	2. *For index* `i` in `pairs`:
		1. Set `data` to a new Schema [
			...data,
			`pairs[i].0.id`= *Unwrap:* `Interpret(pairs[i].1)`,
		].
	3. *Return:* a new Dict containing the properties in `data`.
;

Set! Interpret((SET.NEW `values`)) :=
	1. *Let* `data` be a mapping of `values` for each `it` to *Unwrap:* `Interpret(it)`.
	2. *Return:* a new Set containing the items in `data`.
;

Map! Interpret((MAP.NEW `pairs`)) :=
	1. *Let* `data` be a mapping of `pairs` for each `case` to a new Vector [
		*Unwrap:* `Interpret(case.0)`,
		*Unwrap:* `Interpret(case.1)`,
	].
	2. *Return:* a new Map containing the pairs in `data`.
;

Value! Interpret((TUPLE.GET `index` `obj`)) :=
	1. *Let* `base` be *Unwrap:* `Interpret(obj)`.
	2. *Assert:* `base` is an instance of `Tuple`.
	3. *If* `index` is an index in `base`:
		1. *Return:* the item accessed at index `index` in `base`.
	4. *Else:*
		1. *Return:* `null`.
;

Value! Interpret((RECORD.GET `key` `obj`)) :=
	1. *Let* `base` be *Unwrap:* `Interpret(obj)`.
	2. *Assert:* `base` is an instance of `Record`.
	3. *If* `key` is a key in `base`:
		1. *Return:* the value accessed at key `key` in `base`.
	4. *Else:*
		1. *Return:* `null`.
;

Value! Interpret((LIST.GET `obj` `accessor`)) :=
	1. *Let* `base` be *Unwrap:* `Interpret(obj)`.
	2. *Let* `index` be *Unwrap:* `Interpret(accessor)`.
	3. *Assert:* `base` is an instance of `List`.
	4. *Assert:* `index` is an instance of `Integer` *or* `index` is an instance of `Natural`.
	5. *If* `index` is an index in `base`:
		1. *Return:* the item accessed at index `index` in `base`.
	6. *Else:*
		1. *Return:* `null`.
;

Value! Interpret((DICT.GET `obj` `accessor`)) :=
	1. *Let* `base` be *Unwrap:* `Interpret(obj)`.
	2. *Let* `key` be *Unwrap:* `Interpret(accessor)`.
	3. *Assert:* `base` is an instance of `Dict`.
	4. *Assert:* `key` is an instance of `Symbol` *or* `key` is an instance of `String`.
	5. *If* `key` is an instance of `String`:
		1. *Note:* This step will be updated once string keys are supported.
		2. *Throw:* a new Error "String keys for dict access are not yet supported."
	6. *If* `key` is a key in `base`:
		1. *Return:* the value accessed at key `key` in `base`.
	7. *Else:*
		1. *Return:* `null`.
;

Value! Interpret((SET.GET `obj` `accessor`)) :=
	1. *Let* `base` be *Unwrap:* `Interpret(obj)`.
	2. *Let* `value` be *Unwrap:* `Interpret(accessor)`.
	3. *Assert:* `base` is an instance of `Set`.
	4. *If* `value` is in `base`:
		1. *Return:* `true`.
	5. *Else:*
		1. *Return:* `false`.
;

Value! Interpret((MAP.GET `obj` `accessor`)) :=
	1. *Let* `base` be *Unwrap:* `Interpret(obj)`.
	2. *Let* `ant` be *Unwrap:* `Interpret(accessor)`.
	3. *Assert:* `base` is an instance of `Map`.
	4. Find an antecedent `k` in `base` such that *UnwrapAffirm:* `Identical(k, ant)`.
	5. *If* `k` is set:
		1. *Return:* the consequent accessed at antecedent `k` in `base`.
	6. *Else:*
		1. *Return:* `null`.
;

// Value! Interpret((CALL `callable` `args`));

Value! Interpret((ISNULL `v`)) :=
	1. *Return:* `Identical(v, null)`.
;

Value! Interpret((NOT `v`)) :=
	1. *If* *UnwrapAffirm:* `ToBoolean(v)` is `true`:
		1. *Return:* `false`.
	2. *Return:* `true`.
;

Value! Interpret((EMP `v`)) :=
	1. *If* *UnwrapAffirm:* `ToBoolean(v)` is `false`:
		1. *Return:* `true`.
	2. *If* `v` is an instance of `Integer` *and* `v` is `0`:
		1. *Return:* `true`.
	3. *If* `v` is an instance of `Natural` *and* `v` is `+0`:
		1. *Return:* `true`.
	4. *If* `v` is an instance of `Float` *and* `v` is `0.0` or `-0.0`:
		1. *Return:* `true`.
	5. *If* `v` is an instance of `String` *and* `v` contains 0 codepoints:
		1. *Return:* `true`.
	6. *If* `v` is an instance of `Tuple` or `Record` or `List` or `Dict` or `Set` or `Map` *and* `v.count` is 0:
		1. *Return:* `true`.
	7. *Return:* `false`.
;

Value! Interpret((NEG `v`)) :=
	1. *Let* `negation` be the additive inverse, `-v`,
		obtained by negating `v`.
	2. *Return:* `negation`.
;

Value! Interpret((TOBOOL `v`)) :=
	1. *Return:* `ToBoolean(v)`.
;

Value! Interpret((TOINT `v`)) :=
	1. *If* `v` is an instance of `Natural`:
		1. *Let* `as_int` be the reinterpretation of `v` as a 64-bit signed integer value.
		2. *Return:* `as_int`.
	2. *If* `v` is an instance of `Float`:
		1. *Let* `as_int` be the conversion of `v` to a 64-bit signed integer value.
		2. *Return:* `as_int`.
	3. *Assert:* `v` is an instance of `Integer`.
	4. *Return:* `v`.
;

Value! Interpret((TONAT `v`)) :=
	1. *If* `v` is an instance of `Integer`:
		1. *Let* `as_nat` be the reinterpretation of `v` to a 64-bit unsigned integer value.
		2. *Return:* `as_nat`.
	2. *If* `v` is an instance of `Float`:
		1. *Let* `as_nat` be the conversion of `v` to a 64-bit unsigned integer value.
		2. *Return:* `as_nat`.
	3. *Assert:* `v` is an instance of `Natural`.
	4. *Return:* `v`.
;

Value! Interpret((TOFLOAT `v`)) :=
	1. *If* `v` is an instance of `Integer` *or* `v` is an instance of `Natural`:
		1. *Let* `as_float` be the conversion of `v` to a 64-bit binary floating-point value.
		2. *Return:* `as_float`.
	2. *Assert:* `v` is an instance of `Float`.
	3. *Return:* `v`.
;

Value! Interpret((TOSTR `v`)) :=
	1. *If* `v` is an instance of `String`:
		1. *Return:* `v`.
	2. *Else:*
		1. *Let* `native_string` be a native string representation of `v`.
		2. *Let* `encoding` be the UTF-8 encoding of `native_string`.
		3. *Return:* `encoding`.
;

Value! Interpret((LIST.COUNT `obj`)) :=
	1. *Assert:* `obj` is an instance of `List`.
	2. *Return:* `Natural(obj.count)`.
;

Value! Interpret((DICT.COUNT `obj`)) :=
	1. *Assert:* `obj` is an instance of `Dict`.
	2. *Return:* `Natural(obj.count)`.
;

Value! Interpret((SET.COUNT `obj`)) :=
	1. *Assert:* `obj` is an instance of `Set`.
	2. *Return:* `Natural(obj.count)`.
;

Value! Interpret((MAP.COUNT `obj`)) :=
	1. *Assert:* `obj` is an instance of `Map`.
	2. *Return:* `Natural(obj.count)`.
;

None! Interpret((DROP `v`)) :=
	1. *Perform:* `Interpret(v)`.
;

None! Interpret((DECL `id` `type` `v`)) :=
	1. Set the key `id` to the value `Interpret(v)` in the interpreter’s symbol table.
;

None! Interpret((SET `id` `v`)) :=
	1. Set the key `id` to the value `Interpret(v)` in the interpreter’s symbol table.
;
