TRAP() -> Nothing;
CONST(Primitive) -> Value;
GET(SemanticVariable | String) -> Value;

TOINT(Number)   -> Integer;
TONAT(Number)   -> Natural;
TOFLOAT(Number) -> Float;

NOT(Value) -> Boolean;
EMP(Value) -> Boolean;

INT.NEG(Integer) -> Integer;
FLOAT.NEG(Float) -> Float;

INT.ADD(Integer, Integer) -> Integer;
INT.SUB(Integer, Integer) -> Integer;
INT.MUL(Integer, Integer) -> Integer;
INT.DIV(Integer, Integer) -> Integer;
INT.EXP(Integer, Integer) -> Integer;

NAT.ADD(Natural, Natural) -> Natural;
NAT.SUB(Natural, Natural) -> Natural;
NAT.MUL(Natural, Natural) -> Natural;
NAT.DIV(Natural, Natural) -> Natural;
NAT.EXP(Natural, Natural) -> Natural;

FLOAT.ADD(Float, Float) -> Float;
FLOAT.SUB(Float, Float) -> Float;
FLOAT.MUL(Float, Float) -> Float;
FLOAT.DIV(Float, Float) -> Float;
FLOAT.EXP(Float, Float) -> Float;

LT (Number, Number) -> Boolean;
GT (Number, Number) -> Boolean;
LE (Number, Number) -> Boolean;
GE (Number, Number) -> Boolean;
NLT(Number, Number) -> Boolean;
NGT(Number, Number) -> Boolean;

ID (Value, Value) -> Boolean;
EQ (Value, Value) -> Boolean;
NID(Value, Value) -> Boolean;
NEQ(Value, Value) -> Boolean;

DROP(Value);
DECL(SemanticVariable | String);
SET(SemanticVariable | String, Value);






Lower(Null n)    := (CONST n);
Lower(Boolean b) := (CONST b);
Lower(Symbol s)  := (CONST s);
Lower(Number n)  := (CONST n);

Lower(SemanticProperty prop) := (`#`prop.0.id `Lower(prop.1)`);

Lower(SemanticConstant const) := (CONST Lower(ValueOf(const)~!));
Lower(SemanticVariable var)   := (GET var);

// Lower(SemanticTemplate tpl);

Lower(SemanticTuple tup) := (TUPLE.NEW ...tup.children.map(Lower));
Lower(SemanticRecord rec) := (RECORD.NEW ...rec.children.map(Lower));

// Lower(SemanticList list);
// Lower(SemanticDict dict);
// Lower(SemanticSet set);
// Lower(SemanticMap map);
// Lower(SemanticAccess access);
// Lower(SemanticCall call);
// Lower(SemanticClaim claim);

Lower(SemanticOperation[operator=NOT] op)             := (NOT op.0);
Lower(SemanticOperation[operator=EMP] op)             := (EMP op.0);
Lower(SemanticOperation[operator=NEG][0: Integer] op) := (INT.NEG   op.0);
Lower(SemanticOperation[operator=NEG][0: Float]   op) := (FLOAT.NEG op.0);

Lower(SemanticOperation[operator=ADD][0: Integer][1: Integer] op) := (INT.ADD op.0 op.1);
Lower(SemanticOperation[operator=SUB][0: Integer][1: Integer] op) := (INT.SUB op.0 op.1);
Lower(SemanticOperation[operator=MUL][0: Integer][1: Integer] op) := (INT.MUL op.0 op.1);
Lower(SemanticOperation[operator=DIV][0: Integer][1: Integer] op) := (INT.DIV op.0 op.1);
Lower(SemanticOperation[operator=EXP][0: Integer][1: Integer] op) := (INT.EXP op.0 op.1);

Lower(SemanticOperation[operator=ADD][0: Natural][1: Natural] op) := (NAT.ADD op.0 op.1);
Lower(SemanticOperation[operator=SUB][0: Natural][1: Natural] op) := (NAT.SUB op.0 op.1);
Lower(SemanticOperation[operator=MUL][0: Natural][1: Natural] op) := (NAT.MUL op.0 op.1);
Lower(SemanticOperation[operator=DIV][0: Natural][1: Natural] op) := (NAT.DIV op.0 op.1);
Lower(SemanticOperation[operator=EXP][0: Natural][1: Natural] op) := (NAT.EXP op.0 op.1);

Lower(SemanticOperation[operator=ADD][0: Float][1: Float] op) := (FLOAT.ADD op.0 op.1);
Lower(SemanticOperation[operator=SUB][0: Float][1: Float] op) := (FLOAT.SUB op.0 op.1);
Lower(SemanticOperation[operator=MUL][0: Float][1: Float] op) := (FLOAT.MUL op.0 op.1);
Lower(SemanticOperation[operator=DIV][0: Float][1: Float] op) := (FLOAT.DIV op.0 op.1);
Lower(SemanticOperation[operator=EXP][0: Float][1: Float] op) := (FLOAT.EXP op.0 op.1);

Lower(SemanticOperation[operator=LT] [0: Number][1: Number] op) := (LT op.0 op.1);
Lower(SemanticOperation[operator=GT] [0: Number][1: Number] op) := (GT op.0 op.1);
Lower(SemanticOperation[operator=LE] [0: Number][1: Number] op) := (LE op.0 op.1);
Lower(SemanticOperation[operator=GE] [0: Number][1: Number] op) := (GE op.0 op.1);
Lower(SemanticOperation[operator=NLT][0: Number][1: Number] op) := (NLT op.0 op.1);
Lower(SemanticOperation[operator=NGT][0: Number][1: Number] op) := (NGT op.0 op.1);

Lower(SemanticOperation[operator=ID]  op) := (ID  op.0 op.1);
Lower(SemanticOperation[operator=EQ]  op) := (EQ  op.0 op.1);
Lower(SemanticOperation[operator=NID] op) := (NID op.0 op.1);
Lower(SemanticOperation[operator=NEQ] op) := (NEQ op.0 op.1);


Lower(SemanticOperation[operator=AND] op) := [
	(DECL $result)
	(DECL $left)
	(SET $left `Lower(op.0)`)
	if_false (GET $left), goto "else".
	(SET $result `Lower(op.1)`)
	goto "endif".
	"else":
	(SET $result (GET $left))
	"endif":
	return (GET $result).
];

Lower(SemanticOperation[operator=OR] op) := [
	(DECL $result)
	(DECL $left)
	(SET $left `Lower(op.0)`)
	if_false (GET $left), goto "else".
	(SET $result (GET $left))
	goto "endif".
	"else":
	(SET $result `Lower(op.1)`)
	"endif":
	return (GET $result).
];

Lower(SemanticOperation[operator=COND] op) := [
	(DECL $result)
	if_false `Lower(op.0)`, goto "else".
	(SET $result `Lower(op.1)`)
	goto "endif".
	"else":
	(SET $result `Lower(op.2)`)
	"endif":
	return (GET $result).
];
