// IDENTIFIER      ::= [./lexicon.ebnf#Identifier];
// INTEGER         ::= [./lexicon.ebnf#Integer];
// NATURAL         ::= [./lexicon.ebnf#Natural];
// FLOAT           ::= [./lexicon.ebnf#Float];
// STRING          ::= [./lexicon.ebnf#String];
// TEMPLATE_FULL   ::= [./lexicon.ebnf#TemplateFull];
// TEMPLATE_HEAD   ::= [./lexicon.ebnf#TemplateHead];
// TEMPLATE_MIDDLE ::= [./lexicon.ebnf#TempalteMiddle];
// TEMPLATE_TAIL   ::= [./lexicon.ebnf#TempalteTail];



KeywordType ::=
	| "nothing"
	| "bool"
	| "sym"
	| "int"
	| "nat"
	| "float"
	| "str"
	| "anything"
;

KeywordValue ::=
	| "null"
	| "false"
	| "true"
;



Word ::=
	// operator
		| "mut"
		| "as"
		| "is"
		| "if"
		| "then"
		| "else"
	// storage
		| "type"
		| "val"
		| "claim"
		| "set"
		| "_"
		| "void"
	// modifier
		| "nominal"
	// control
		| "unless"
		| "while"
		| "until"
		| "for"
		| "in"
		| "do"
		| "break"
		| "skip"
	| IDENTIFIER
	| KeywordType
	| KeywordValue
;



PrimitiveLiteral ::=
	| INTEGER
	| NATURAL
	| FLOAT
	| STRING
	| KeywordValue
	| "@" Word
;



EntryType<Named, Optional>
	::= <Named+>(Word & <Optional->":") <Optional+>"?:" Type;

ItemsType ::=
	|                                                                  ","?  EntryType<-Named><+Optional>#   ","?
	| EntryType<-Named><-Optional>                                     ","  (EntryType<-Named><+Optional>#   ","?)?
	| EntryType<-Named><-Optional>? "," EntryType<-Named><-Optional># (","   EntryType<-Named><+Optional>#)? ","?
;

PropertiesType
	::= ","? EntryType<+Named><∓Optional># ","?;

PropertyAccessorType
	::= INTEGER | NATURAL | Word;

TypeGrouped       ::= "(" Type             ")";
TypeTupleLiteral  ::= "(" ItemsType?       ")";
TypeRecordLiteral ::= "(" PropertiesType   ")";
TypeListLiteral   ::= "[" Type             "]";
TypeDictLiteral   ::= "[" ":" Type         "]";
TypeSetLiteral    ::= "{" Type             "}";
TypeMapLiteral    ::= "{" Type "->" Type   "}";
GenericArguments  ::= "<"  ","? Type# ","? ">";

TypeUnit ::=
	| IDENTIFIER
	| KeywordType
	| PrimitiveLiteral
	| TypeGrouped
	| TypeTupleLiteral
	| TypeListLiteral
	| TypeRecordLiteral
	| TypeDictLiteral
	| TypeSetLiteral
	| TypeMapLiteral
;

TypeCompound ::=
	| TypeUnit
	| TypeCompound (
		| ("." | "?.") PropertyAccessorType
		|  "."         GenericArguments
	)
;

TypeUnarySymbol  ::= TypeCompound    | TypeUnarySymbol ("?" | "!");
TypeUnaryKeyword ::= TypeUnarySymbol | "mut" TypeUnaryKeyword;

TypeIntersection ::= (TypeIntersection "&")? TypeUnaryKeyword;
TypeUnion        ::= (TypeUnion        "|")? TypeIntersection;

Type ::=
	| TypeUnion
;



StringTemplate<Break> ::=
	| TEMPLATE_FULL
	| TEMPLATE_HEAD Expression<+Block><?Break>? (TEMPLATE_MIDDLE Expression<+Block><?Break>?)* TEMPLATE_TAIL
;

Items<Break> ::=
	| Expression<+Block><?Break>  ","
	| Expression<+Block><?Break>? "," Expression<+Block><?Break># ","?
;

Property <Break> ::= Word                       "="  Expression<+Block><?Break>;
Case     <Break> ::= Expression<+Block><?Break> "->" Expression<+Block><?Break>;

PropertyAccessor<Break>
	::= INTEGER | NATURAL | Word | "[" Expression<+Block><?Break> "]";

ExpressionGrouped       <Break> ::= "("       Expression<+Block><?Break>         ")";
ExpressionTupleLiteral  <Break> ::= "("       Items<?Break>?                     ")";
ExpressionRecordLiteral <Break> ::= "("  ","? Property<?Break>#           ","?   ")";
ExpressionListLiteral   <Break> ::= "[" (","? Expression<+Block><?Break># ","?)? "]";
ExpressionDictLiteral   <Break> ::= "["  ","? Property<?Break>#           ","?   "]";
ExpressionSetLiteral    <Break> ::= "{" (","? Expression<+Block><?Break># ","?)? "}";
ExpressionMapLiteral    <Break> ::= "{"  ","? Case<?Break>#               ","?   "}";
FunctionArguments       <Break> ::= "(" (","? Expression<+Block><?Break># ","?)? ")";

ExpressionUnit<Block, Break> ::=
	| IDENTIFIER
	| PrimitiveLiteral
	| StringTemplate          <?Break>
	| ExpressionGrouped       <?Break>
	| ExpressionTupleLiteral  <?Break>
	| ExpressionRecordLiteral <?Break>
	| ExpressionListLiteral   <?Break>
	| ExpressionDictLiteral   <?Break>
	| ExpressionSetLiteral    <?Break>
	| ExpressionMapLiteral    <?Break>
	| <Block+>Block           <?Break>
;

ExpressionCompound<Block, Break> ::=
	| ExpressionUnit<?Block><?Break>
	| ExpressionCompound<?Block><?Break> (
		| ("." | "?." | "!.") PropertyAccessor<?Break>
		|  "."                GenericArguments? FunctionArguments<?Break>
	)
;

ExpressionUnarySymbol  <Block, Break> ::= ExpressionCompound    <?Block><?Break> | ("!" | "?" | "+" | "-")   ExpressionUnarySymbol  <?Block><?Break>;
ExpressionUnaryKeyword <Block, Break> ::= ExpressionUnarySymbol <?Block><?Break> | ("int" | "nat" | "float") ExpressionUnaryKeyword <?Block><?Break>;

ExpressionCast<Block, Break> ::=
	| (ExpressionCast<?Block><?Break> ("as" | "as?" | "as!"))? ExpressionUnaryKeyword<?Block><?Break>
	|  ExpressionCast<?Block><?Break>  "as"                    "<" Type ">"
;

ExpressionExponential<Block, Break>
	::= ExpressionCast<?Block><?Break> ("^" ExpressionExponential<?Block><?Break>)?;

ExpressionMultiplicative <Block, Break> ::= (ExpressionMultiplicative <?Block><?Break> ("*" | "/" ))?                                           ExpressionExponential    <?Block><?Break>;
ExpressionAdditive       <Block, Break> ::= (ExpressionAdditive       <?Block><?Break> ("+" | "-" ))?                                           ExpressionMultiplicative <?Block><?Break>;
ExpressionComparative    <Block, Break> ::= (ExpressionComparative    <?Block><?Break> ("<" | ">" | "<=" | ">=" | "!<" | "!>" | "is" | "!is"))? ExpressionAdditive       <?Block><?Break>;
ExpressionEquality       <Block, Break> ::= (ExpressionEquality       <?Block><?Break> ("===" | "!==" | "==" | "!="))?                          ExpressionComparative    <?Block><?Break>;
ExpressionConjunctive    <Block, Break> ::= (ExpressionConjunctive    <?Block><?Break> ("&&" | "!&"))?                                          ExpressionEquality       <?Block><?Break>;
ExpressionDisjunctive    <Block, Break> ::= (ExpressionDisjunctive    <?Block><?Break> ("||" | "!|"))?                                          ExpressionConjunctive    <?Block><?Break>;

ExpressionConditional<Break> ::=
	& "if"
	& Expression<+Block><?Break>
	& "then"
	& Expression<-Block><?Break>
	& "else"
	& Expression<-Block><?Break>
;

Expression<Block, Break> ::=
	| ExpressionDisjunctive<?Block><?Break>
	| ExpressionConditional<?Break>
;



Assignee<Break> ::=
	| IDENTIFIER
	| ExpressionCompound<+Block><?Break> "." PropertyAccessor<?Break>
;



StatementExpression<Break>
	::= Expression<+Block><?Break>? ";";

StatementClaim        <Break> ::= "claim" Assignee<?Break> ":" Type                       ";";
StatementReassignment <Break> ::= "set"   Assignee<?Break> "=" Expression<+Block><?Break> ";";

StatementConditional<Unless, Break> ::=
	& <Unless->"if" <Unless+>"unless" Expression<+Block><?Break>
	& "then" Block<?Break>
	& <Unless->(
		| ("else" Block<?Break>)? ";"
		| "else" StatementConditional<?Unless><?Break>
	)
	& <Unless+>";"
;

StatementLoop ::= (
	&& ("while" | "until") Expression<+Block><-Break>
	&& "do"                Block<+Break>
) ";";

StatementIteration
	::= "for" ("_" | IDENTIFIER) ":" Type "in" Expression<+Block><-Break> "do" Block<+Break> ";";

StatementBreak
	::= ("break" | "skip") ";";

Statement<Break> ::=
	| Declaration                     <?Break>
	| StatementExpression             <?Break>
	| StatementClaim                  <?Break>
	| StatementReassignment           <?Break>
	| StatementConditional   <∓Unless><?Break>
	| StatementLoop
	| StatementIteration
	| <Break+>StatementBreak
;



Block<Break>
	::= "{" Statement<?Break>+ "}";



DeclarationType
	::= "type" ("_" | IDENTIFIER) "=" Type ";";

DeclarationVariable<Break> ::=
	| "val" ("_" | "mut"? IDENTIFIER)    (":" Type)? "=" Expression<+Block><?Break> ";"
	| "val"        "mut"  IDENTIFIER  "?" ":" Type                                  ";"
;

Declaration<Break> ::=
	| DeclarationType
	| DeclarationVariable<?Break>
;



SourceFile
	::= #x02 Block<-Break>? #x03;
