// IDENTIFIER      ::= [./lexicon.ebnf#Identifier];
// INTEGER         ::= [./lexicon.ebnf#Integer];
// NATURAL         ::= [./lexicon.ebnf#Natural];
// FLOAT           ::= [./lexicon.ebnf#Float];
// STRING          ::= [./lexicon.ebnf#String];
// TEMPLATE_FULL   ::= [./lexicon.ebnf#TemplateFull];
// TEMPLATE_HEAD   ::= [./lexicon.ebnf#TemplateHead];
// TEMPLATE_MIDDLE ::= [./lexicon.ebnf#TempalteMiddle];
// TEMPLATE_TAIL   ::= [./lexicon.ebnf#TempalteTail];



KeywordType ::=
	| "nothing"
	| "bool"
	| "sym"
	| "int"
	| "nat"
	| "float"
	| "str"
	| "anything"
;

KeywordValue ::=
	| "null"
	| "false"
	| "true"
;



Word ::=
	// operator
		| "mut"
		| "isset"
		| "as"
		| "is"
		| "if"
		| "then"
		| "else"
		| "switch"
		| "case"
		| "default"
	// storage
		| "type"
		| "val"
		| "func"
		| "claim"
		| "set"
		| "delete"
		| "_"
		| "with"
		| "ref"
		| "void"
	// modifier
		| "nominal"
	// control
		| "unless"
		| "while"
		| "until"
		| "for"
		| "in"
		| "do"
		| "break"
		| "skip"
		| "return"
	| IDENTIFIER
	| KeywordType
	| KeywordValue
;



PrimitiveLiteral ::=
	| INTEGER
	| NATURAL
	| FLOAT
	| STRING
	| KeywordValue
	| "@" Word
;



EntryType<Named, Optional>
	::= <Named+>(Word & <Optional->":") <Optional+>"?:" Type;

ItemsType ::=
	|                                                                  ","?  EntryType<-Named><+Optional>#   ","?
	| EntryType<-Named><-Optional>                                     ","  (EntryType<-Named><+Optional>#   ","?)?
	| EntryType<-Named><-Optional>? "," EntryType<-Named><-Optional># (","   EntryType<-Named><+Optional>#)? ","?
;

PropertiesType
	::= ","? EntryType<+Named><∓Optional># ","?;

ParametersType ::=
	| ","? EntryType<-Named><-Optional># ("," EntryType<+Named><-Optional>#)? ","?
	| ","?                                    EntryType<+Named><-Optional>#   ","?
;

PropertyAccessorType
	::= INTEGER | NATURAL | Word;

TypeGrouped       ::= "(" Type             ")";
TypeTupleLiteral  ::= "(" ItemsType?       ")";
TypeRecordLiteral ::= "(" PropertiesType   ")";
TypeListLiteral   ::= "[" Type             "]";
TypeDictLiteral   ::= "[" ":" Type         "]";
TypeSetLiteral    ::= "{" Type             "}";
TypeMapLiteral    ::= "{" Type "->" Type   "}";
GenericArguments  ::= "<"  ","? Type# ","? ">";

TypeUnit ::=
	| IDENTIFIER
	| KeywordType
	| PrimitiveLiteral
	| TypeGrouped
	| TypeTupleLiteral
	| TypeListLiteral
	| TypeRecordLiteral
	| TypeDictLiteral
	| TypeSetLiteral
	| TypeMapLiteral
;

TypeCompound ::=
	| TypeUnit
	| TypeCompound (
		| ("." | "?.") PropertyAccessorType
		|  "."         GenericArguments
	)
;

TypeUnarySymbol  ::= TypeCompound    | TypeUnarySymbol ("?" | "!");
TypeUnaryKeyword ::= TypeUnarySymbol | "mut" TypeUnaryKeyword;

TypeIntersection ::= (TypeIntersection "&")? TypeUnaryKeyword;
TypeUnion        ::= (TypeUnion        "|")? TypeIntersection;

TypeFunction
	::= "\" "(" ParametersType? ")" "=>" "void";

Type ::=
	| TypeUnion
	| TypeFunction
;



StringTemplate<Break, Return> ::=
	| TEMPLATE_FULL
	| TEMPLATE_HEAD Expression<+Block><?Break><?Return>? (TEMPLATE_MIDDLE Expression<+Block><?Break><?Return>?)* TEMPLATE_TAIL
;

Items<Break, Return> ::=
	| Expression<+Block><?Break><?Return>  ","
	| Expression<+Block><?Break><?Return>? "," Expression<+Block><?Break><?Return># ","?
;

Property   <Break, Return> ::=                                                   Word                                "="  Expression<+Block><?Break><?Return>;
CaseMap    <Break, Return> ::=                                                   Expression<+Block><?Break><?Return> "->" Expression<+Block><?Break><?Return>;
CaseSwitch <Break, Return> ::= "case" (Expression<+Block><?Break><?Return> "|")* Expression<+Block><?Break><?Return> "->" Expression<+Block><?Break><?Return>;

ParameterFunction<Named> ::= (
	| <Named+>(Word "=") ("_" | "mut"? IDENTIFIER)
	| <Named+>("mut"? "$" IDENTIFIER)
) ":" Type;

ParametersFunction ::=
	| ","? ParameterFunction<-Named># ("," ParameterFunction<+Named>#)? ","?
	| ","?                                 ParameterFunction<+Named>#   ","?
;

PropertyAccessor<Break, Return>
	::= INTEGER | NATURAL | Word | "[" Expression<+Block><?Break><?Return> "]";

ExpressionGrouped       <Break, Return> ::= "("       Expression <+Block><?Break><?Return>         ")";
ExpressionTupleLiteral  <Break, Return> ::= "("       Items              <?Break><?Return>?        ")";
ExpressionRecordLiteral <Break, Return> ::= "("  ","? Property           <?Break><?Return># ","?   ")";
ExpressionListLiteral   <Break, Return> ::= "[" (","? Expression <+Block><?Break><?Return># ","?)? "]";
ExpressionDictLiteral   <Break, Return> ::= "["  ","? Property           <?Break><?Return># ","?   "]";
ExpressionSetLiteral    <Break, Return> ::= "{" (","? Expression <+Block><?Break><?Return># ","?)? "}";
ExpressionMapLiteral    <Break, Return> ::= "{"  ","? CaseMap            <?Break><?Return># ","?   "}";
FunctionArguments       <Break, Return> ::= "(" (","? Expression <+Block><?Break><?Return># ","?)? ")";

ExpressionUnit<Block, Break, Return> ::=
	| IDENTIFIER
	| PrimitiveLiteral
	| StringTemplate          <?Break><?Return>
	| ExpressionGrouped       <?Break><?Return>
	| ExpressionTupleLiteral  <?Break><?Return>
	| ExpressionRecordLiteral <?Break><?Return>
	| ExpressionListLiteral   <?Break><?Return>
	| ExpressionDictLiteral   <?Break><?Return>
	| ExpressionSetLiteral    <?Break><?Return>
	| ExpressionMapLiteral    <?Break><?Return>
	| <Block+>Block           <?Break><?Return>
;

ExpressionCompound<Block, Break, Return> ::=
	| ExpressionUnit<?Block><?Break><?Return>
	| ExpressionCompound<?Block><?Break><?Return> (
		| ("." | "?." | "!.") PropertyAccessor<?Break><?Return>
		|  "."                GenericArguments? FunctionArguments<?Break><?Return>
	)
;

ExpressionUnarySymbol<Block, Break, Return> ::=
	| ExpressionCompound<?Block><?Break><?Return>
	| ("!" | "?" | "+" | "-") ExpressionUnarySymbol<?Block><?Break><?Return>
;

ExpressionUnaryKeyword<Block, Break, Return> ::=
	| ExpressionUnarySymbol<?Block><?Break><?Return>
	| ("isset" | "!isset") Assignee<?Break><?Return>
;

ExpressionCast<Block, Break, Return> ::=
	| (ExpressionCast<?Block><?Break><?Return> ("as" | "as?" | "as!"))? ExpressionUnaryKeyword<?Block><?Break><?Return>
	|  ExpressionCast<?Block><?Break><?Return>  "as"                    "<" Type ">"
;

ExpressionExponential<Block, Break, Return>
	::= ExpressionCast<?Block><?Break><?Return> ("^" ExpressionExponential<?Block><?Break><?Return>)?;

ExpressionMultiplicative <Block, Break, Return> ::= (ExpressionMultiplicative <?Block><?Break><?Return> ("*" | "/" ))?                                           ExpressionExponential    <?Block><?Break><?Return>;
ExpressionAdditive       <Block, Break, Return> ::= (ExpressionAdditive       <?Block><?Break><?Return> ("+" | "-" ))?                                           ExpressionMultiplicative <?Block><?Break><?Return>;
ExpressionComparative    <Block, Break, Return> ::= (ExpressionComparative    <?Block><?Break><?Return> ("<" | ">" | "<=" | ">=" | "!<" | "!>" | "is" | "!is"))? ExpressionAdditive       <?Block><?Break><?Return>;
ExpressionEquality       <Block, Break, Return> ::= (ExpressionEquality       <?Block><?Break><?Return> ("===" | "!==" | "==" | "!="))?                          ExpressionComparative    <?Block><?Break><?Return>;
ExpressionConjunctive    <Block, Break, Return> ::= (ExpressionConjunctive    <?Block><?Break><?Return> ("&&" | "!&"))?                                          ExpressionEquality       <?Block><?Break><?Return>;
ExpressionDisjunctive    <Block, Break, Return> ::= (ExpressionDisjunctive    <?Block><?Break><?Return> ("||" | "!|"))?                                          ExpressionConjunctive    <?Block><?Break><?Return>;

ExpressionConditional<Break, Return> ::=
	& "if"
	& Expression<+Block><?Break><?Return>
	& "then"
	& Expression<-Block><?Break><?Return>
	& "else"
	& Expression<-Block><?Break><?Return>
;

ExpressionSwitch<Break, Return>
	::= "switch" Expression<+Block><?Break><?Return> CaseSwitch<?Break><?Return>* "default" Expression<+Block><?Break><?Return>;

ExpressionFunction
	::= "\" "(" ParametersFunction? ")" ":" "void" Block<-Break><+Return>;

Expression<Block, Break, Return> ::=
	| ExpressionDisjunctive<?Block><?Break><?Return>
	| ExpressionConditional<?Break><?Return>
	| ExpressionSwitch<?Break><?Return>
	| ExpressionFunction
;



Assignee<Break, Return> ::=
	| IDENTIFIER
	| ExpressionCompound<+Block><?Break><?Return> "." PropertyAccessor<?Break><?Return>
;



StatementExpression<Break, Return>
	::= Expression<+Block><?Break><?Return>? ";";

StatementClaim  <Break, Return> ::= "claim"  Assignee<?Break><?Return> ":" Type                                ";";
StatementSet    <Break, Return> ::= "set"    Assignee<?Break><?Return> "=" Expression<+Block><?Break><?Return> ";";
StatementDelete <Break, Return> ::= "delete" Assignee<?Break><?Return>                                         ";";

StatementConditional<Unless, Break, Return> ::=
	& <Unless->"if" <Unless+>"unless" Expression<+Block><?Break><?Return>
	& "then" Block<?Break><?Return>
	& <Unless->(
		| ("else" Block<?Break><?Return>)? ";"
		| "else" StatementConditional<?Unless><?Break><?Return>
	)
	& <Unless+>";"
;

StatementLoop<Return> ::= (
	&& ("while" | "until") Expression<+Block><-Break><?Return>
	&& "do"                Block<+Break><?Return>
) ";";

StatementIteration<Return> ::=
	& "for" ("_" | IDENTIFIER) ":" Type
	& "in" Expression<+Block><+Break><?Return>
	& "do" Block<+Break><?Return> ";"
;

StatementBreak  ::= ("break" | "skip") ";";
StatementReturn ::=  "return"          ";";

Statement<Break, Return> ::=
	| Declaration                   <?Break><?Return>
	| StatementExpression           <?Break><?Return>
	| StatementClaim                <?Break><?Return>
	| StatementSet                  <?Break><?Return>
	| StatementDelete               <?Break><?Return>
	| StatementConditional <∓Unless><?Break><?Return>
	| StatementLoop                         <?Return>
	| StatementIteration                    <?Return>
	| <Break+> StatementBreak
	| <Return+>StatementReturn
;



Block<Break, Return>
	::= "{" Statement<?Break><?Return>+ "}";



DeclarationType
	::= "type" ("_" | IDENTIFIER) "=" Type ";";

DeclarationVariable<Break, Return> ::=
	| "val" ("_" | "mut"? IDENTIFIER)    (":" Type)? "=" Expression<+Block><?Break><?Return> ";"
	| "val"        "mut"  IDENTIFIER  "?" ":" Type                                           ";"
;

DeclarationFunction
	::= "func" ("_" | IDENTIFIER) "(" ParametersFunction? ")" ":" "void" Block<-Break><+Return>

Declaration<Break, Return> ::=
	| DeclarationType
	| DeclarationVariable<?Break><?Return>
	| DeclarationFunction
;



SourceFile
	::= #x02 Block<-Break><-Return>? #x03;
