TokenWorth(Punctuator :::= "(")   -> RealNumber := \x00;
TokenWorth(Punctuator :::= ")")   -> RealNumber := \x01;
TokenWorth(Punctuator :::= "[")   -> RealNumber := \x02;
TokenWorth(Punctuator :::= "]")   -> RealNumber := \x03;
TokenWorth(Punctuator :::= "{")   -> RealNumber := \x04;
TokenWorth(Punctuator :::= "}")   -> RealNumber := \x05;
TokenWorth(Punctuator :::= ",")   -> RealNumber := \x06;
TokenWorth(Punctuator :::= "->")  -> RealNumber := \x07;
TokenWorth(Punctuator :::= "?:")  -> RealNumber := \x08;
TokenWorth(Punctuator :::= ".")   -> RealNumber := \x09;
TokenWorth(Punctuator :::= "?.")  -> RealNumber := \x0a;
TokenWorth(Punctuator :::= "!.")  -> RealNumber := \x0b;
TokenWorth(Punctuator :::= "?")   -> RealNumber := \x0c;
TokenWorth(Punctuator :::= "!")   -> RealNumber := \x0d;
TokenWorth(Punctuator :::= "+")   -> RealNumber := \x0e;
TokenWorth(Punctuator :::= "-")   -> RealNumber := \x0f;
TokenWorth(Punctuator :::= "^")   -> RealNumber := \x10;
TokenWorth(Punctuator :::= "*")   -> RealNumber := \x11;
TokenWorth(Punctuator :::= "/")   -> RealNumber := \x12;
TokenWorth(Punctuator :::= "<")   -> RealNumber := \x13;
TokenWorth(Punctuator :::= ">")   -> RealNumber := \x14;
TokenWorth(Punctuator :::= "<=")  -> RealNumber := \x15;
TokenWorth(Punctuator :::= ">=")  -> RealNumber := \x16;
TokenWorth(Punctuator :::= "!<")  -> RealNumber := \x17;
TokenWorth(Punctuator :::= "!>")  -> RealNumber := \x18;
TokenWorth(Punctuator :::= "===") -> RealNumber := \x19;
TokenWorth(Punctuator :::= "!==") -> RealNumber := \x1a;
TokenWorth(Punctuator :::= "==")  -> RealNumber := \x1b;
TokenWorth(Punctuator :::= "!=")  -> RealNumber := \x1c;
TokenWorth(Punctuator :::= "&&")  -> RealNumber := \x1d;
TokenWorth(Punctuator :::= "!&")  -> RealNumber := \x1e;
TokenWorth(Punctuator :::= "||")  -> RealNumber := \x1f;
TokenWorth(Punctuator :::= "!|")  -> RealNumber := \x20;
TokenWorth(Punctuator :::= "&")   -> RealNumber := \x21;
TokenWorth(Punctuator :::= "|")   -> RealNumber := \x22;
TokenWorth(Punctuator :::= ";")   -> RealNumber := \x23;
TokenWorth(Punctuator :::= ":")   -> RealNumber := \x24;
TokenWorth(Punctuator :::= "=")   -> RealNumber := \x25;
TokenWorth(Punctuator :::= "\")   -> RealNumber := \x26;
TokenWorth(Punctuator :::= "=>")  -> RealNumber := \x27;



TokenWorth(KeywordType  :::= "nothing")  -> RealNumber := \x40;
TokenWorth(KeywordType  :::= "bool")     -> RealNumber := \x41;
TokenWorth(KeywordType  :::= "sym")      -> RealNumber := \x42;
TokenWorth(KeywordType  :::= "int")      -> RealNumber := \x43;
TokenWorth(KeywordType  :::= "nat")      -> RealNumber := \x44;
TokenWorth(KeywordType  :::= "float")    -> RealNumber := \x45;
TokenWorth(KeywordType  :::= "str")      -> RealNumber := \x46;
TokenWorth(KeywordType  :::= "anything") -> RealNumber := \x47;
TokenWorth(KeywordValue :::= "null")     -> RealNumber := \x48;
TokenWorth(KeywordValue :::= "false")    -> RealNumber := \x49;
TokenWorth(KeywordValue :::= "true")     -> RealNumber := \x4a;
TokenWorth(KeywordOther :::= "mut")      -> RealNumber := \x4b;
TokenWorth(KeywordOther :::= "isset")    -> RealNumber := \x4c;
TokenWorth(KeywordOther :::= "!isset")   -> RealNumber := \x4d;
TokenWorth(KeywordOther :::= "as")       -> RealNumber := \x4e;
TokenWorth(KeywordOther :::= "as?")      -> RealNumber := \x4f;
TokenWorth(KeywordOther :::= "as!")      -> RealNumber := \x50;
TokenWorth(KeywordOther :::= "is")       -> RealNumber := \x51;
TokenWorth(KeywordOther :::= "!is")      -> RealNumber := \x52;
TokenWorth(KeywordOther :::= "if")       -> RealNumber := \x53;
TokenWorth(KeywordOther :::= "then")     -> RealNumber := \x54;
TokenWorth(KeywordOther :::= "else")     -> RealNumber := \x55;
TokenWorth(KeywordOther :::= "switch")   -> RealNumber := \x56;
TokenWorth(KeywordOther :::= "case")     -> RealNumber := \x57;
TokenWorth(KeywordOther :::= "default")  -> RealNumber := \x58;
TokenWorth(KeywordOther :::= "type")     -> RealNumber := \x59;
TokenWorth(KeywordOther :::= "val")      -> RealNumber := \x5a;
TokenWorth(KeywordOther :::= "func")     -> RealNumber := \x5b;
TokenWorth(KeywordOther :::= "claim")    -> RealNumber := \x5c;
TokenWorth(KeywordOther :::= "set")      -> RealNumber := \x5d;
TokenWorth(KeywordOther :::= "delete")   -> RealNumber := \x5e;
TokenWorth(KeywordOther :::= "_")        -> RealNumber := \x5f;
TokenWorth(KeywordOther :::= "$")        -> RealNumber := \x60;
TokenWorth(KeywordOther :::= "void")     -> RealNumber := \x61;
TokenWorth(KeywordOther :::= "nominal")  -> RealNumber := \x62;
TokenWorth(KeywordOther :::= "unless")   -> RealNumber := \x63;
TokenWorth(KeywordOther :::= "while")    -> RealNumber := \x64;
TokenWorth(KeywordOther :::= "until")    -> RealNumber := \x65;
TokenWorth(KeywordOther :::= "for")      -> RealNumber := \x66;
TokenWorth(KeywordOther :::= "in")       -> RealNumber := \x67;
TokenWorth(KeywordOther :::= "do")       -> RealNumber := \x68;
TokenWorth(KeywordOther :::= "break")    -> RealNumber := \x69;
TokenWorth(KeywordOther :::= "skip")     -> RealNumber := \x6a;
TokenWorth(KeywordOther :::= "return")   -> RealNumber := \x6b;



TokenWorth(Identifier :::= "Object") -> RealNumber := \x80;
TokenWorth(Identifier :::= "Integer" -> RealNumber := \x81;
TokenWorth(Identifier :::= "Natural" -> RealNumber := \x82;
TokenWorth(Identifier :::= "Float"   -> RealNumber := \x83;
TokenWorth(Identifier :::= "String"  -> RealNumber := \x84;
TokenWorth(Identifier :::= "List"    -> RealNumber := \x85;
TokenWorth(Identifier :::= "Dict"    -> RealNumber := \x86;
TokenWorth(Identifier :::= "Set"     -> RealNumber := \x87;
TokenWorth(Identifier :::= "Map"     -> RealNumber := \x88;

TokenWorth(Identifier) -> RealNumber :=
	1. Convert the source text of `Identifier` to a string of bytes in the UTF-8 encoding.
	2. Hash each byte, folding in the results from start to end, using a modified Fowler–Noll–Vo hash function.
	3. *Return:* the sum of the hash and `\x100`.
;



TokenWorth(Integer :::= WholeDigits) -> RealNumber
	:= TokenWorth(WholeDigits);
TokenWorth(Integer :::= "-" WholeDigits) -> RealNumber
	:= -1 * TokenWorth(WholeDigits);

TokenWorth(Natural :::= "+" WholeDigits) -> RealNumber
	:= TokenWorth(WholeDigits);

TokenWorth(WholeDigits :::= "\b"  DigitSequenceBin) -> RealNumber
	:= TokenWorth(DigitSequenceBin);
TokenWorth(WholeDigits :::= "\q"  DigitSequenceQua) -> RealNumber
	:= TokenWorth(DigitSequenceQua);
TokenWorth(WholeDigits :::= "\s"  DigitSequenceSex) -> RealNumber
	:= TokenWorth(DigitSequenceSex);
TokenWorth(WholeDigits :::= "\o"  DigitSequenceOct) -> RealNumber
	:= TokenWorth(DigitSequenceOct);
TokenWorth(WholeDigits :::= "\d"? DigitSequenceDec) -> RealNumber
	:= TokenWorth(DigitSequenceDec);
TokenWorth(WholeDigits :::= "\x"  DigitSequenceHex) -> RealNumber
	:= TokenWorth(DigitSequenceHex);
TokenWorth(WholeDigits :::= "\z"  DigitSequenceNif) -> RealNumber
	:= TokenWorth(DigitSequenceNif);

TokenWorth(Float :::= SignedDigitSequenceDec ".") -> RealNumber
	:= TokenWorth(SignedDigitSequenceDec);
TokenWorth(Float :::= SignedDigitSequenceDec "." DigitSequenceDec) -> RealNumber
	:= TokenWorth(SignedDigitSequenceDec) + TokenWorth(DigitSequenceDec);
TokenWorth(Float :::= SignedDigitSequenceDec "." DigitSequenceDec ExponentPart) -> RealNumber
	:= (TokenWorth(SignedDigitSequenceDec) + TokenWorth(DigitSequenceDec)) * TokenWorth(ExponentPart);

TokenWorth(ExponentPart :::= "e" SignedDigitSequenceDec) -> RealNumber
	:= 10 ^ TokenWorth(SignedDigitSequenceDec);

TokenWorth(SignedDigitSequenceDec :::= "+"? DigitSequenceDec) -> RealNumber
	:= TokenWorth(DigitSequenceDec);
TokenWorth(SignedDigitSequenceDec :::= "-"  DigitSequenceDec) -> RealNumber
	:= -1 * TokenWorth(DigitSequenceDec);

TokenWorth(DigitSequenceBin :::= [0-1]) -> RealNumber
	:= TokenWorth([0-1]);
TokenWorth(DigitSequenceBin :::= DigitSequenceBin "_"? [0-1]) -> RealNumber
	:= 2 * TokenWorth(DigitSequenceBin) + TokenWorth([0-1]);
TokenWorth(DigitSequenceQua :::= [0-3]) -> RealNumber
	:= TokenWorth([0-3]);
TokenWorth(DigitSequenceQua :::= DigitSequenceQua "_"? [0-3]) -> RealNumber
	:= 4 * TokenWorth(DigitSequenceQua) + TokenWorth([0-3]);
TokenWorth(DigitSequenceSex :::= [0-5]) -> RealNumber
	:= TokenWorth([0-5]);
TokenWorth(DigitSequenceSex :::= DigitSequenceSex "_"? [0-5]) -> RealNumber
	:= 6 * TokenWorth(DigitSequenceSex) + TokenWorth([0-5]);
TokenWorth(DigitSequenceOct :::= [0-7]) -> RealNumber
	:= TokenWorth([0-7]);
TokenWorth(DigitSequenceOct :::= DigitSequenceOct "_"? [0-7]) -> RealNumber
	:= 8 * TokenWorth(DigitSequenceOct) + TokenWorth([0-7]);
TokenWorth(DigitSequenceDec :::= [0-9]) -> RealNumber
	:= TokenWorth([0-9]);
TokenWorth(DigitSequenceDec :::= DigitSequenceDec "_"? [0-9]) -> RealNumber
	:= 10 * TokenWorth(DigitSequenceDec) + TokenWorth([0-9]);
TokenWorth(DigitSequenceHex :::= [0-9a-f]) -> RealNumber
	:= TokenWorth([0-9a-f]);
TokenWorth(DigitSequenceHex :::= DigitSequenceHex "_"? [0-9a-f]) -> RealNumber
	:= 16 * TokenWorth(DigitSequenceHex) + TokenWorth([0-9a-f]);
TokenWorth(DigitSequenceNif :::= [0-9a-z]) -> RealNumber
	:= TokenWorth([0-9a-z]);
TokenWorth(DigitSequenceNif :::= DigitSequenceNif "_"? [0-9a-z]) -> RealNumber
	:= 36 * TokenWorth(DigitSequenceNif) + TokenWorth([0-9a-z]);

TokenWorth([0-9a-z] :::= "0") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "0") -> RealNumber  :=  TokenWorth([0-9] :::= "0") -> RealNumber  :=  TokenWorth([0-7] :::= "0") -> RealNumber  :=  TokenWorth([0-5] :::= "0") -> RealNumber  :=  TokenWorth([0-3] :::= "0") -> RealNumber  :=  TokenWorth([0-1] :::= "0") -> RealNumber  :=  \x00;
TokenWorth([0-9a-z] :::= "1") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "1") -> RealNumber  :=  TokenWorth([0-9] :::= "1") -> RealNumber  :=  TokenWorth([0-7] :::= "1") -> RealNumber  :=  TokenWorth([0-5] :::= "1") -> RealNumber  :=  TokenWorth([0-3] :::= "1") -> RealNumber  :=  TokenWorth([0-1] :::= "1") -> RealNumber  :=  \x01;
TokenWorth([0-9a-z] :::= "2") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "2") -> RealNumber  :=  TokenWorth([0-9] :::= "2") -> RealNumber  :=  TokenWorth([0-7] :::= "2") -> RealNumber  :=  TokenWorth([0-5] :::= "2") -> RealNumber  :=  TokenWorth([0-3] :::= "2") -> RealNumber  :=  \x02;
TokenWorth([0-9a-z] :::= "3") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "3") -> RealNumber  :=  TokenWorth([0-9] :::= "3") -> RealNumber  :=  TokenWorth([0-7] :::= "3") -> RealNumber  :=  TokenWorth([0-5] :::= "3") -> RealNumber  :=  TokenWorth([0-3] :::= "3") -> RealNumber  :=  \x03;
TokenWorth([0-9a-z] :::= "4") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "4") -> RealNumber  :=  TokenWorth([0-9] :::= "4") -> RealNumber  :=  TokenWorth([0-7] :::= "4") -> RealNumber  :=  TokenWorth([0-5] :::= "4") -> RealNumber  :=  \x04;
TokenWorth([0-9a-z] :::= "5") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "5") -> RealNumber  :=  TokenWorth([0-9] :::= "5") -> RealNumber  :=  TokenWorth([0-7] :::= "5") -> RealNumber  :=  TokenWorth([0-5] :::= "5") -> RealNumber  :=  \x05;
TokenWorth([0-9a-z] :::= "6") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "6") -> RealNumber  :=  TokenWorth([0-9] :::= "6") -> RealNumber  :=  TokenWorth([0-7] :::= "6") -> RealNumber  :=  \x06;
TokenWorth([0-9a-z] :::= "7") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "7") -> RealNumber  :=  TokenWorth([0-9] :::= "7") -> RealNumber  :=  TokenWorth([0-7] :::= "7") -> RealNumber  :=  \x07;
TokenWorth([0-9a-z] :::= "8") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "8") -> RealNumber  :=  TokenWorth([0-9] :::= "8") -> RealNumber  :=  \x08;
TokenWorth([0-9a-z] :::= "9") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "9") -> RealNumber  :=  TokenWorth([0-9] :::= "9") -> RealNumber  :=  \x09;
TokenWorth([0-9a-z] :::= "a") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "a") -> RealNumber  :=  \x0a;
TokenWorth([0-9a-z] :::= "b") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "b") -> RealNumber  :=  \x0b;
TokenWorth([0-9a-z] :::= "c") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "c") -> RealNumber  :=  \x0c;
TokenWorth([0-9a-z] :::= "d") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "d") -> RealNumber  :=  \x0d;
TokenWorth([0-9a-z] :::= "e") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "e") -> RealNumber  :=  \x0e;
TokenWorth([0-9a-z] :::= "f") -> RealNumber  :=  TokenWorth([0-9a-f] :::= "f") -> RealNumber  :=  \x0f;
TokenWorth([0-9a-z] :::= "g") -> RealNumber  :=  \x010;
TokenWorth([0-9a-z] :::= "h") -> RealNumber  :=  \x011;
TokenWorth([0-9a-z] :::= "i") -> RealNumber  :=  \x012;
TokenWorth([0-9a-z] :::= "j") -> RealNumber  :=  \x013;
TokenWorth([0-9a-z] :::= "k") -> RealNumber  :=  \x014;
TokenWorth([0-9a-z] :::= "l") -> RealNumber  :=  \x015;
TokenWorth([0-9a-z] :::= "m") -> RealNumber  :=  \x016;
TokenWorth([0-9a-z] :::= "n") -> RealNumber  :=  \x017;
TokenWorth([0-9a-z] :::= "o") -> RealNumber  :=  \x018;
TokenWorth([0-9a-z] :::= "p") -> RealNumber  :=  \x019;
TokenWorth([0-9a-z] :::= "q") -> RealNumber  :=  \x01a;
TokenWorth([0-9a-z] :::= "r") -> RealNumber  :=  \x01b;
TokenWorth([0-9a-z] :::= "s") -> RealNumber  :=  \x01c;
TokenWorth([0-9a-z] :::= "t") -> RealNumber  :=  \x01d;
TokenWorth([0-9a-z] :::= "u") -> RealNumber  :=  \x01e;
TokenWorth([0-9a-z] :::= "v") -> RealNumber  :=  \x01f;
TokenWorth([0-9a-z] :::= "w") -> RealNumber  :=  \x020;
TokenWorth([0-9a-z] :::= "x") -> RealNumber  :=  \x021;
TokenWorth([0-9a-z] :::= "y") -> RealNumber  :=  \x022;
TokenWorth([0-9a-z] :::= "z") -> RealNumber  :=  \x023;



TokenWorth(String :::= #x22 #x22) -> Sequence<RealNumber>
	:= [];
TokenWorth(String :::= #x22 StringChars #x22) -> Sequence<RealNumber>
	:= TokenWorth(StringChars);
TokenWorth(String :::= #x22 StringUnfinished #x22) -> Sequence<RealNumber>
	:= TokenWorth(StringUnfinished);
TokenWorth(String :::= #x22 StringChars StringUnfinished #x22) -> Sequence<RealNumber>
	:= [...TokenWorth(StringChars), ...TokenWorth(StringUnfinished)];

	TokenWorth(StringChars :::= StringChar) -> Sequence<RealNumber>
		:= TokenWorth(StringChar);
	TokenWorth(StringChars :::= StringChar StringChars) -> Sequence<RealNumber>
		:= [...TokenWorth(StringChar), ...TokenWorth(StringChars)];

		TokenWorth(StringChar :::= [^"\%#x03]) -> Sequence<RealNumber>
			:= UTF8Encoding(CodePoint([^"\%#x03]));
		TokenWorth(StringChar :::= "\" StringEscape) -> Sequence<RealNumber>
			:= TokenWorth(StringEscape);
		TokenWorth(StringChar :::= "\u" [^"{#x03]) -> Sequence<RealNumber>
			:= [...UTF8Encoding(\x75), ...UTF8Encoding(CodePoint([^"{#x03]))];
		TokenWorth(StringChar :::= "%" ([^"%#x0a#x03] [^"#x0a#x03]*)? #x0a) -> Sequence<RealNumber>
			:= UTF8Encoding(\x0a);
		TokenWorth(StringChar :::= "%%" ("%"? [^"%#x03])* "%%") -> Sequence<RealNumber>
			:= [];

			TokenWorth(StringEscape :::= #x22) -> Sequence<RealNumber>
				:= UTF8Encoding(\x22); // U+0022 QUOTATION MARK
			TokenWorth(StringEscape :::= "\") -> Sequence<RealNumber>
				:= UTF8Encoding(\x5c); // U+005C REVERSE SOLIDUS
			TokenWorth(StringEscape :::= "%") -> Sequence<RealNumber>
				:= UTF8Encoding(\x25); // U+0025 PERCENT SIGN
			TokenWorth(StringEscape :::= "s") -> Sequence<RealNumber>
				:= UTF8Encoding(\x20); // U+0020 SPACE
			TokenWorth(StringEscape :::= "t") -> Sequence<RealNumber>
				:= UTF8Encoding(\x09); // U+0009 CHARACTER TABULATION
			TokenWorth(StringEscape :::= "n") -> Sequence<RealNumber>
				:= UTF8Encoding(\x0a); // U+000A LINE FEED (LF)
			TokenWorth(StringEscape :::= "r") -> Sequence<RealNumber>
				:= UTF8Encoding(\x0d); // U+000D CARRIAGE RETURN (CR)
			TokenWorth(StringEscape :::= "u{" "}") -> Sequence<RealNumber>
				:= UTF8Encoding(\x00); // U+0000 NULL
			TokenWorth(StringEscape :::= "u{" DigitSequenceHex "}") -> Sequence<RealNumber>
				:= UTF8Encoding(TokenWorth(DigitSequenceHex));
			TokenWorth(StringEscape :::= #x0A) -> Sequence<RealNumber>
				:= UTF8Encoding(\x20); // U+0020 SPACE
			TokenWorth(StringEscape :::= [^"\%stnru#x0a#x03]) -> Sequence<RealNumber>
				:= UTF8Encoding(CodePoint([^"\%stnru#x0a#x03]));

	TokenWorth(StringUnfinished :::= "\u") -> Sequence<RealNumber>
		:= UTF8Encoding(\x75); // U+0075 LATIN SMALL LETTER U
	TokenWorth(StringUnfinished :::= "%" ([^"%#x0a#x03] [^"#x0a#x03]*)?) -> Sequence<RealNumber>
		:= [];
	TokenWorth(StringUnfinished :::= "%%" ("%"? [^"%#x03])*) -> Sequence<RealNumber>
		:= [];



TokenWorth(TemplateFull :::= #x22 #x22 #x22 #x22 #x22 #x22) -> Sequence<RealNumber>
	:= [];
TokenWorth(TemplateFull :::= #x22 #x22 #x22 TemplateChars__EndDelim #x22 #x22 #x22) -> Sequence<RealNumber>
	:= TokenWorth(TemplateChars__EndDelim);

TokenWorth(TemplateHead :::= #x22 #x22 #x22 "{{") -> Sequence<RealNumber>
	:= [];
TokenWorth(TemplateHead :::= #x22 #x22 #x22 TemplateChars__EndInterp "{{") -> Sequence<RealNumber>
	:= TokenWorth(TemplateChars__EndInterp);

TokenWorth(TemplateMiddle :::= "}}" "{{") -> Sequence<RealNumber>
	:= [];
TokenWorth(TemplateMiddle :::= "}}" TemplateChars__EndInterp "{{") -> Sequence<RealNumber>
	:= TokenWorth(TemplateChars__EndInterp);

TokenWorth(TemplateTail :::= "}}" #x22 #x22 #x22) -> Sequence<RealNumber>
	:= [];
TokenWorth(TemplateTail :::= "}}" TemplateChars__EndDelim #x22 #x22 #x22) -> Sequence<RealNumber>
	:= TokenWorth(TemplateChars__EndDelim);

	TokenWorth(TemplateChars__EndDelim) -> Sequence<RealNumber>
		:= "Return a mapping of `TemplateChars__EndDelim` for each `character` to `UTF8Encoding(CodePoint(character))`.";

	TokenWorth(TemplateChars__EndInterp) -> Sequence<RealNumber>
		:= "Return a mapping of `TemplateChars__EndInterp` for each `character` to `UTF8Encoding(CodePoint(character))`.";
