Nil! TypeCheck(Or<
	SemanticIndex,
	SemanticKey,
	SemanticItemType,
	SemanticPropertyType
	SemanticProperty,
	SemanticCase,
	SemanticBlock,
	SemanticGoal,
	SemanticStatementExpression,
	SemanticStatementBreak,
	SemanticStatementReturn,
> list) :=
	1. *For each* `it` in `list.children`:
		1. *Perform:* *Unwrap:* `TypeCheck(it)`.
;



Nil! TypeCheck(SemanticParameterFunction param) :=
	1. *For each* `it` in `param.children`:
		1. *Perform:* *Unwrap:* `TypeCheck(it)`.
	2. *Let* `typenode` be an item `child` in `param.children` such that `child` is a SemanticType.
	3. *Let* `param_type` be *Unwrap:* `TypeValueOf(typenode)`.
	4. *If* `param.id` is not *nil*:
		1. *Let* `parent` be the parent node of `param`.
		2. *Assert:* `parent` is a SemanticExpressionFunction or a SemanticDeclarationFunction.
		3. *Let* `block` be `parent.children.-1`.
		4. *Assert:* `block` is a SemanticBlock.
		5. *Let* `validator` be the validator of `block`.
		6. *Assert:* `validator`’s symbol table contains a SymbolSchema `symbol` whose `id` is `param.id`.
		7. *Assert:* `symbol` is an instance of `SymbolSchemaVar`.
		8. *Set* `symbol.type` to `param_type`.
	5. *Else:*
		1. *Return.*
;



Nil TypeCheck(SemanticType typexpr) :=
	1. *Perform:* *Unwrap:* `TypeValueOf(typexpr)`.
		1. *Note:* The result of this step is not used; it is only performed to rethrow any TypeErrors.
;



Nil! TypeCheck(SemanticExpression expr) :=
	1. *Perform:* *Unwrap:* `TypeOf(expr)`.
		1. *Note:* The result of this step is not used; it is only performed to rethrow any TypeErrors.
;



Nil! TypeCheck(SemanticDeclarationType decl) :=
	1. *Let* `typevalue` be *Unwrap:* `TypeValueOf(decl.children.0)`.
	2. *Assert:* The validator’s symbol table contains a SymbolSchema `symbol` whose `id` is `decl.id`.
	3. *Assert:* `symbol` is an instance of `SymbolSchemaType`.
	4. *Set* `symbol.typevalue` to `typevalue`.
;



Nil! TypeCheck(SemanticDeclarationVariable decl) :=
	1. *Let* `typenode` be an item `child` in `decl.children` such that `child` is a SemanticType.
	2. *Let* `assigned` be an item `child` in `decl.children` such that `child` is a SemanticExpression.
	3. *If* `typenode` is *nil*:
		1. *Assert:* `assigned` is not *nil*.
		2. *Set* `typenode` to an inferred type of `assigned`.
	4. *Else:*
		1. Fall through.
	5. *If* `assigned` is not *nil*:
		1. *Perform:* *UnwrapAffirm:* `TypeCheck(assigned)`.
	6. *Else:*
		1. Fall through.
	7. *Let* `assignee_type` be *Unwrap:* `TypeValueOf(typenode)`.
	8. *If* `assigned` is not *nil*:
		1. *Perform:* *Unwrap:* `TypeCheckAssign(assigned, assignee_type)`.
	9. *Else:*
		1. Fall through.
	10. *If* `decl.id` is not *nil*:
		1. *Assert:* The validator’s symbol table contains a SymbolSchema `symbol` whose `id` is `decl.id`.
		2. *Assert:* `symbol` is an instance of `SymbolSchemaVar`.
		3. *Set* `symbol.type` to `assignee_type`.
	11. *Else:*
		1. *Return.*
;



None! TypeCheck(SemanticDeclarationFunction fn) :=
	1. *For each* `it` in `fn.children`:
		1. *Perform:* *Unwrap:* `TypeCheck(it)`.
	2. *Let* `parameters` be a filtering of `fn.children` for each `child` such that `child` is a SemanticParameterFunction.
	3. *Let* `positional_params` be a filtering of `parameters` for each `param` such that `param.named` is `false`.
	4. *Let* `positional_param_types` be a new Sequence.
	5. *For each* `param` in `positional_params`:
		1. *Assert:* `param.children.count` is *1*.
		2. *Let* `typedatum` be a new EntryTypeSchema [
			type=     *Unwrap:* `TypeValueOf(param.children.0)`,
			optional= `false`, // TODO: with optional paramers: `param.optional`
		].
		3. Push `typedatum` to `positional_param_types`.
	6. *Let* `named_params` be a filtering of `parameters` for each `param` such that `param.named` is `true`.
	7. *Let* `named_param_types` be a new Schema.
	8. *For each* `param` in `named_params`:
		1. *If* `param.children.count` is *2*:
			1. *Let* `key_id` be `param.children.0.id`.
			2. *Let* `param_type` be *Unwrap:* `TypeValueOf(param.children.1)`.
		2. *Else:*
			1. *Assert:* `param.children.count` is *1*.
			2. *Assert:* `param.id` is set.
			3. *Let* `key_id` be `param.id`.
			4. *Let* `param_type` be *Unwrap:* `TypeValueOf(param.children.0)`.
		3. *Let* `typedatum` be a new EntryTypeSchema [
			type=     `param_type`,
			optional= `false`, // TODO: with optional paramers: `param.optional`
		].
		4. Set the property `key_id` on `named_param_types` to the value `typedatum`.
	9. *Let* `fn_type` be a new Function type whose positional parameter types are `positional_param_types`,
		whose named parameter types are `named_param_types`,
		and who does not contain a return type.
	10. *If* `fn.id` is not *none*:
		1. *Assert:* The validator’s symbol table contains a SymbolSchema `symbol` whose `id` is `fn.id`.
		2. *Assert:* `symbol` is an instance of `SymbolSchemaFunc`.
		3. *Set* `symbol.type` to `fn_type`.
	11. *Else:*
		1. *Return.*
;



Type! TypeCheck(SemanticStatementClaim claim) :=
	1. *Assert:* `claim.children.count` is 2.
	2. *Let* `assignee` be `claim.children.0`.
	3. *Let* `computed_type` be *Unwrap:* `TypeOf(assignee)`.
	4. *Let* `claimed_type` be *Unwrap:* `TypeValueOf(claim.children.1)`.
	5. *If* *UnwrapAffirm:* `Subtype(claimed_type, computed_type)` is `false`:
		1. *Throw:* a new TypeErrorNotNarrow.
	6. *If* `assignee` is a SemanticExpressionVariable:
		1. *If* the validator’s symbol table contains a SymbolSchema `symbol` whose `id` is `assignee.id`:
			1. *Assert:* `symbol` is an instance of `SymbolSchemaVar`.
			2. *Set* `symbol.type` to `claimed_type`.
	7. *Else:*
		1. *Assert:* `assignee` is a SemanticExpressionAccess.
		2. *Assert:* `assignee.children.count` is 2.
		3. *Let* `base_type` be *Unwrap:* `TypeOf(assignee.children.0)`.
		4. *Let* `accessor` be `assignee.children.1`.
		5. *If* `base_type` is a Tuple type:
			1. *Assert:* `accessor` is a SemanticIndex.
			2. *If* `accessor.index` is an index in `base_type`:
				1. *Let* `old_entry` be a the item accessed at index `accessor.index` in `base_type`.
				2. *Let* `new_entry` be a new EntryTypeSchema [
					type=     `claimed_type`,
					optional= `old_entry.optional`,
				].
				3. *Set* the item at index `accessor.index` in `base_type` to `new_entry`.
			3. *Else:*
				1. *Throw:* a new TypeErrorNoEntry.
		6. *Else If* `base_type` is a Record type:
			1. *Assert:* `accessor` is a SemanticKey.
			2. *If* `accessor.id` is a key in `base_type`:
				1. *Let* `old_entry` be the item accessed at key `accessor.id` in `base_type`.
				2. *Let* `new_entry` be a new EntryTypeSchema [
					type=     `claimed_type`,
					optional= `old_entry.optional`,
				].
				3. *Set* the item at key `accessor.id` in `base_type` to `new_entry`.
			3. *Else:*
				1. *Throw:* a new TypeErrorNoEntry.
		7. *Else:*
			1. *Assert:* `accessor` is a SemanticExpression.
			// TODO
;



Nil! TypeCheck(SemanticStatementReassignment ::= SemanticExpressionVariable) :=
	1. *Return:* `TypeCheck(SemanticExpressionVariable)`.
;
Nil! TypeCheck(SemanticStatementReassignment ::= SemanticExpressionVariable SemanticExpression) :=
	1. *Perform:* *Unwrap:* `TypeCheck(SemanticExpressionVariable)`.
	2. *Perform:* *Unwrap:* `TypeCheck(SemanticExpression)`.
	3. *Let* `assignee_type` be *Unwrap:* `WriteTypeOf(SemanticExpressionVariable)`.
	4. *Return:* `TypeCheckAssign(SemanticExpression, assignee_type)`.
;
Nil! TypeCheck(SemanticStatementReassignment ::= SemanticExpressionAccess) :=
	1. *Perform:* *Unwrap:* `TypeCheck(SemanticExpressionAccess)`.
	2. *Let* `base_type` be *Unwrap:* `TypeOf(SemanticExpressionAccess)`.
	3. *If* `base_type` is not mutable:
		1. *Throw:* a new MutabilityError01.
	4. *If* `base_type` is not an interface type:
		1. *Throw:* a new TypeError "The `delete` statement is only applicable to interface types.". // TODO: temporary error type until we get interfaces
	// TODO: if entry is not optional, throw.
	5. *Return.*
;
Nil! TypeCheck(SemanticStatementReassignment ::= SemanticExpressionAccess SemanticExpression) :=
	1. *Perform:* *Unwrap:* `TypeCheck(SemanticExpressionAccess)`.
	2. *Perform:* *Unwrap:* `TypeCheck(SemanticExpression)`.
	3. *Let* `base_type` be *Unwrap:* `TypeOf(SemanticExpressionAccess)`.
	4. *If* `base_type` is not mutable:
		1. *Throw:* a new MutabilityError01.
	5. *Let* `assignee_type` be *Unwrap:* `WriteTypeOf(SemanticExpressionAccess)`.
	6. *Return:* `TypeCheckAssign(SemanticExpression, assignee_type)`.
;



Nil! TypeCheck(SemanticStatementConditional stmt) :=
	1. *For each* `it` in `stmt.children`:
		1. *Perform:* *Unwrap:* `TypeCheck(it)`.
	2. *Assert:* `stmt.children.count` is greater than 1.
	3. *Assert:* `stmt.children.0` is a SemanticExpression.
	4. *Let* `condition_type` be *Unwrap:* `TypeOf(stmt.children.0)`.
	5. *If* *UnwrapAffirm:* `Subtype(condition_type, Boolean)` is `true`:
		1. *Return.*
	6. *Else:*
		1. *Throw:* a new TypeErrorNotAssignable.
;



Nil! TypeCheck(SemanticStatementLoop stmt) :=
	1. *For each* `it` in `stmt.children`:
		1. *Perform:* *Unwrap:* `TypeCheck(it)`.
	2. *Let* `condition` be an item `child` in `stmt.children` such that `child` is a SemanticExpression.
	3. *Assert:* `condition` is not *nil*.
	4. *Let* `condition_type` be *Unwrap:* `TypeOf(condition)`.
	5. *If* *UnwrapAffirm:* `Subtype(condition_type, Boolean)` is `true`:
		1. *Return.*
	6. *Else:*
		1. *Throw:* a new TypeErrorNotAssignable.
;



Nil! TypeCheck(SemanticStatementIteration stmt) :=
	1. *Let* `typenode` be an item `child` in `stmt.children` such that `child` is a SemanticType.
	2. *Let* `iterable` be an item `child` in `stmt.children` such that `child` is a SemanticExpression.
	3. *Let* `block`    be an item `child` in `stmt.children` such that `child` is a SemanticBlock.
	4. *Assert:* `typenode` is not *nil*.
	5. *Let* `assignee_type` be *Unwrap:* `TypeValueOf(typenode)`.
	6. *Assert:* `iterable` is not *nil*.
	7. *Let* `iterable_type` be *Unwrap:* `TypeOf(iterable)`.
	8. *If* `iterable_type` is not a List type:
		1. *Throw:* a new TypeErrorNotAssignable.
	9. *Let* `item_type` be the type argument over `iterable_type`.
	10. *If* *UnwrapAffirm:* `Subtype(item_type, assignee_type)` is `false`:
		1. *Throw:* a new TypeErrorNotNarrow.
	11. *Assert:* `block` is not *nil*.
	12. *If* `assignee` is not *nil*:
		1. *Let* `validator` be the validator of `block`.
		2. *Assert:* `validator`’s symbol table contains a SymbolSchema `symbol` whose `id` is `assignee.id`.
		3. *Assert:* `symbol` is an instance of `SymbolSchemaVar`.
		4. *Set* `symbol.type` to `assignee_type`.
	13. *Perform:* *Unwrap:* `TypeCheck(block)`.
;



Nil! TypeCheck(SemanticStatementReturn ::= ()) :=
	1. *Let* `parent` be the result of walking up the AST and finding a node
		that is either a SemanticExpressionFunction or a SemanticDeclarationFunction.
	2. *If* `parent` is set:
		1. *Let* `return_node` be an item `node` in `parent` such that `item` is a SemanticType.
		2. *If* `return_node` is set:
			1. *Let* `return_type` be *Unwrap:* `TypeValueOf(return_node)`.
			2. *Throw:* a new Error """A function with return type \`{{ return_type.value }}\` does not return a value."""
		3. *Else:*
			1. *Note:* The function is a void function and the return statement has no expression.
			2. *Return.*
	3. *Else:*
		1. *Return.*
;
Nil! TypeCheck(SemanticStatementReturn ::= SemanticExpression) :=
	1. *Let* `parent` be the result of walking up the AST and finding a node
		that is either a SemanticExpressionFunction or a SemanticDeclarationFunction.
	2. *If* `parent` is set:
		1. *Let* `return_node` be an item `node` in `parent` such that `item` is a SemanticType.
		2. *If* `return_node` is set:
			1. *Let* `return_type` be *Unwrap:* `TypeValueOf(return_node)`.
			2. *Return:* `TypeCheckAssign(SemanticExpression, return_type.value)`.
		3. *Else:*
			1. *Throw:* a new Error """Expression \`{{ SemanticExpression }}\` is returned from a void function."""
	3. *Else:*
		1. *Return.*
;



Nil! TypeCheckAssign(SemanticExpression assigned, Type assignee_type) :=
	1. *Let* `assigned_type` be *Unwrap:* `TypeOf(assigned)`.
	2. *If* *UnwrapAffirm:* `Subtype(assigned_type, assignee_type)` is `false`:
		1. *If* `assigned` is a SemanticExpressionCollection:
			1. *Return:* `AssignTo(assigned, assignee_type)`.
		2. *Else:*
			1. *Throw:* a new TypeErrorNotAssignable.
;
