Or<Null, Boolean, Symbol, Number, String> ValueOf(SemanticExpressionConstant const) :=
	1. *Return:* `const.value`.
;



String! ValueOf(SemanticExpressionTemplate tpl) :=
	1. *Let* `values` be a mapping for each `node` in `tpl.children` to *Unwrap:* `ValueOf(node)`.
	2. *Let* `strings` be a mapping for each `value` in `values` to `String(value)`.
	3. *Return:* the string-concatenation of each item in `strings`, preserving order.
;



Object! ValueOf(SemanticExpressionVariable var) :=
	1. *Assert:* The validator’s symbol table contains a SymbolSchema `symbol` whose `id` is `var.id`.
	2. *Assert:* `symbol` is an instance of `SymbolSchemaVar`.
	3. *If* `symbol.isWritable` is `false`:
		1. *Assert:* `symbol.value` is not *none*.
		2. *Return:* `symbol.value`.
	2. *Throw:* *none*.
;



Tuple! ValueOf(SemanticExpressionTuple tuple) :=
	1. *Let* `data` be a mapping of `tuple` for each `it` to *Unwrap:* `ValueOf(it)`.
	2. *Return:* a new Tuple containing the items in `data`.
;



Record! ValueOf(SemanticExpressionRecord record) :=
	1. *Let* `data` be a new Schema.
	2. *For each* `property` in `record`:
		1. Set `data` to a new Schema [
			...data,
			`property.children.0.id`= *Unwrap:* `ValueOf(property.children.1)`,
		].
	3. *Return:* a new Record containing the properties in `data`.
;



Set! ValueOf(SemanticExpressionList list) :=
	1. *Let* `data` be a mapping of `list` for each `it` to *Unwrap:* `ValueOf(it)`.
	2. *Return:* a new List containing the items in `data`.
;



Set! ValueOf(SemanticExpressionDict dict) :=
	1. *Let* `data` be a mapping of `dict` for each `prop` to *Unwrap:* `ValueOf(prop.children.1)`.
	2. *Return:* a new List containing the items in `data`.
;



Set! ValueOf(SemanticExpressionSet set) :=
	1. *Let* `data` be a mapping of `set` for each `el` to *Unwrap:* `ValueOf(el)`.
	2. *Return:* a new Set containing the items in `data`.
;



Map! ValueOf(SemanticExpressionMap map) :=
	1. *Let* `data` be a mapping of `map` for each `case` to a new Sequence [
		*Unwrap:* `ValueOf(case.children.0)`,
		*Unwrap:* `ValueOf(case.children.1)`,
	].
	2. *For each* `it` in `data`:
		1. *Assert:* `it.count` is 2.
	3. *Return:* a new Map containing the pairs in `data`.
;



Value! ValueOf(SemanticExpressionBlock block) :=
	1. *Assert:* `block.children.count` is greater than 0.
	2. *For each* `stmt` in `block.children`:
		1. *If* `stmt` is not a SemanticStatementExpression:
			1. *Throw:* *none*.
		2. *If* `stmt.children.count` is 1:
		3. *Perform:* *Unwrap:* `ValueOf(stmt.children.0)`.
	3. *Let* `last_stmt` be `block.children.-1`.
	4. *Assert:* `last_stmt` is a SemanticStatementExpression.
	5. *Assert:* `last_stmt.children.count` is greater than 0.
	6. *Let* `expr` be `last_stmt.children.0`.
	7. *Assert:* `expr` is a SemanticExpression.
	8. *Return:* `ValueOf(expr)`.
;



Object! ValueOf(SemanticExpressionAccess[kind: RESULT] access) :=
	// TODO: implement
;

Object! ValueOf(SemanticExpressionAccess[kind: NORMAL | MAYBE] access) :=
	1. *Assert:* `access.children.count` is 2.
	2. *Let* `base` be `access.children.0`.
	3. *Let* `accessor` be `access.children.1`.
	4. *Let* `base_value` be *Unwrap:* `ValueOf(base)`.
	5. *If* `accessor` is a SemanticIndex:
		1. *If* `base_value` is an instance of `Tuple`:
			1. *Let* `index` be `accessor.index`.
			2. *If* `index` is less than *0*:
				1. *Set* `index` to `index + base_value.count`.
			3. *If* `index` is an index in `base_value`:
				1. *Return:* the item accessed at index `index` in `base_value`.
			4. *Else If* `access.kind` is `MAYBE`:
				1. *Return:* `null`.
			5. *Else:*
				1. *Throw:* a new VoidError.
		2. *Else:*
			1. *Assert:* `access.kind` is `MAYBE`.
			2. *Return:* `null`.
	6. *Else If* `accessor` is a SemanticKey:
		1. *If* `base_value` is an instance of `Record`:
			1. *If* `accessor.id` is a key in `base_value`:
				1. *Return:* the value accessed at key `accessor.id` in `base_value`.
			2. *Else If* `access.kind` is `MAYBE`:
				1. *Return:* `null`.
			3. *Else:*
				1. *Throw:* a new VoidError.
		2. *Else:*
			1. *Assert:* `access.kind` is `MAYBE`.
			2. *Return:* `null`.
	7. *Else:*
		1. *Assert:* `accessor` is a SemanticExpression.
		2. *Let* `accessor_value` be *Unwrap:* `ValueOf(accessor)`.
		3. *If* `base_value` is an instance of `List`:
			1. *Let* `index` be `accessor_value`.
			2. *If* `index` is less than *0*:
				1. *Set* `index` to `index + base_value.count`.
			3. *If* `index` is an index in `base_value`:
				1. *Return:* the item accessed at index `accessor_value` in `base_value`.
			4. *Else If* `access.kind` is `MAYBE`:
				1. *Return:* `null`.
			5. *Else:*
				1. *Throw:* a new VoidError.
		4. *Else If* `base_value` is an instance of `Dict`:
			1. *If* `accessor_value` is a key in `base_value`:
				1. *Return:* the value accessed at key `accessor_value` in `base_value`.
			2. *Else If* `access.kind` is `MAYBE`:
				1. *Return:* `null`.
			3. *Else:*
				1. *Throw:* a new VoidError.
		5. *Else If* `base_value` is an instance of `Set`:
			1. *If* `accessor_value` is in `base_value`:
				1. *Return:* `true`.
			2. *Else:*
				1. *Return:* `false`.
		6. *Else If* `base_value` is an instance of `Map`:
			1. Find an antecedent `k` in `base_value` such that *UnwrapAffirm:* `Identical(k, accessor_value)`.
			2. *If* `k` is set:
				1. *Return:* the consequent accessed at antecedent `k` in `base_value`.
			3. *Return:* `null`.
		1. *Else:*
			1. *Assert:* `access.kind` is `MAYBE`.
			2. *Return:* `null`.
;



Object! ValueOf(SemanticExpressionCall call) :=
	1. *Assert:* `call.children.count` is greater than or equal to 1.
	2. *Let* `base` be `call.children.0`.
	3. *If* `base.source` is "List":
		1. *Assert:* `call.children.count` is 2 or 3.
		2. *If* `call.children.count` is 2:
			1. *Note:* The call looks like "List.<T>()".
			2. *Return:* a new empty List.
		3. *Note:* The call looks like "List.<T>(arg)".
		4. *Let* `tuple` be *Unwrap:* `ValueOf(call.children.2)`.
		5. *Return:* a new List containing the items in `tuple`.
	5. *Else If* `base.source` is "Dict":
		1. *Assert:* `call.children.count` is 2 or 3.
		2. *If* `call.children.count` is 2:
			1. *Note:* The call looks like "Dict.<T>()".
			2. *Return:* a new empty Dict.
		3. *Note:* The call looks like "Dict.<T>(arg)".
		4. *Let* `record` be *Unwrap:* `ValueOf(call.children.2)`.
		5. *Return:* a new Dict containing the properties in `record`.
	6. *Else If* `base.source` is "Set":
		1. *Assert:* `call.children.count` is 2 or 3.
		2. *If* `call.children.count` is 2:
			1. *Note:* The call looks like "Set.<T>()".
			2. *Return:* a new empty Set.
		3. *Note:* The call looks like "Set.<T>(arg)".
		4. *Let* `tuple` be *Unwrap:* `ValueOf(call.children.2)`.
		5. *Return:* a new Set containing the items in `tuple`.
	7. *Else:*
		1. *Assert:* `base.source` is "Map".
		2. *Assert:* `call.children.count` is 2 or 3 or 4.
		3. *If* `call.children.count` is 2:
			1. *Note:* The call looks like "Map.<K>()".
			2. *Return:* a new empty Map.
		4. *Else If* `call.children.count` is 3:
			1. *If* `call.children.2` is a SemanticType:
				1. *Note:* The call looks like "Map.<K, V>()".
				2. *Return:* a new empty Map.
			2. *Else:*
				1. *Note:* The call looks like "Map.<K>(arg)".
				2. *Let* `tuple` be *Unwrap:* `ValueOf(call.children.2)`.
				3. *Return:* a new Map containing the pairs in `tuple`.
		5. *Note:* The call looks like "Map.<K, V>(arg)".
		6. *Let* `tuple` be *Unwrap:* `ValueOf(call.children.3)`.
		7. *Return:* a new Map containing the pairs in `tuple`.
;



Object! ValueOf(SemanticExpressionClaim claim) :=
	1. *Assert:* `claim.children.count` is 2.
	2. *Return:* `ValueOf(claim.children.0)`.
;



Boolean! ValueOf(SemanticExpressionOperation[operator: NOT] expr) :=
	1. *Assert:* `expr.children.count` is 1.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *If* *UnwrapAffirm:* `ToBoolean(v0)` is `true`:
		1. *Return:* `false`.
	4. *Return:* `true`.
;

Boolean! ValueOf(SemanticExpressionOperation[operator: EMP] expr) :=
	1. *Assert:* `expr.children.count` is 1.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *If* *UnwrapAffirm:* `ToBoolean(v0)` is `false`:
		1. *Return:* `true`.
	4. *If* `v0` is an instance of `Integer` *and* `v0` is `0`:
		1. *Return:* `true`.
	5. *If* `v0` is an instance of `Natural` *and* `v0` is `+0`:
		1. *Return:* `true`.
	6. *If* `v0` is an instance of `Float` *and* `v0` is `0.0` or `-0.0`:
		1. *Return:* `true`.
	7. *If* `v0` is an instance of `String` *and* `v0` contains 0 codepoints:
		1. *Return:* `true`.
	8. *If* `v0` is an instance of `Tuple` or `Record` or `List` or `Dict` or `Set` or `Map` *and* `v0.count` is 0:
		1. *Return:* `true`.
	9. *Return:* `false`.
;

Number! ValueOf(SemanticExpressionOperation[operator: NEG] expr) :=
	1. *Assert:* `expr.children.count` is 1.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Assert:* `v0` is an instance of `Number`.
	4. *Let* `negation` be the additive inverse, `-v0`,
		obtained by negating `v0`.
	5. *Return:* `negation`.
;

Number! ValueOf(SemanticExpressionOperation[operator: INT] expr) :=
	1. *Assert:* `expr.children.count` is 1.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Assert:* `v0` is an instance of `Number`.
	4. *If* `v0` is an instance of `Natural`:
		1. *Let* `as_int` be the reinterpretation of `v0` as a 64-bit signed integer value.
		2. *Return:* `as_int`.
	5. *If* `v0` is an instance of `Float`:
		1. *Let* `as_int` be the conversion of `v0` to a 64-bit signed integer value.
		2. *Return:* `as_int`.
	6. *Assert:* `v0` is an instance of `Integer`.
	7. *Return:* `v0`.
;

Number! ValueOf(SemanticExpressionOperation[operator: NAT] expr) :=
	1. *Assert:* `expr.children.count` is 1.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Assert:* `v0` is an instance of `Number`.
	4. *If* `v0` is an instance of `Integer`:
		1. *Let* `as_nat` be the reinterpretation of `v0` to a 64-bit unsigned integer value.
		2. *Return:* `as_nat`.
	5. *If* `v0` is an instance of `Float`:
		1. *Let* `as_nat` be the conversion of `v0` to a 64-bit unsigned integer value.
		2. *Return:* `as_nat`.
	6. *Assert:* `v0` is an instance of `Natural`.
	7. *Return:* `v0`.
;

Number! ValueOf(SemanticExpressionOperation[operator: FLOAT] expr) :=
	1. *Assert:* `expr.children.count` is 1.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Assert:* `v0` is an instance of `Number`.
	4. *If* `v0` is an instance of `Integer` *or* `v0` is an instance of `Natural`:
		1. *Let* `as_float` be the conversion of `v0` to a 64-bit binary floating-point value.
		2. *Return:* `as_float`.
	5. *Assert:* `v0` is an instance of `Float`.
	6. *Return:* `v0`.
;

Number! ValueOf(SemanticExpressionOperation[operator: EXP | MUL | DIV | ADD | SUB] expr) :=
	1. *Assert:* `expr.children.count` is 2.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Let* `v1` be *Unwrap:* `ValueOf(expr.children.1)`.
	4. *Assert:* `v0` is an instance of `Number` *and* `v1` is an instance of `Number`.
	5. *Return:* `PerformBinaryArithmetic(expr.operator, v0, v1)`.
;

Boolean! ValueOf(SemanticExpressionOperation[operator: LT | GT | LE | GE] expr) :=
	1. *Assert:* `expr.children.count` is 2.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Let* `v1` be *Unwrap:* `ValueOf(expr.children.1)`.
	4. *Assert:* `v0` is an instance of `Number` *and* `v1` is an instance of `Number`.
	5. *Return:* `PerformBinaryCompare(expr.operator, v0, v1)`.
;

Boolean! ValueOf(SemanticExpressionOperation[operator: IS] expr) :=
	// TODO: implement
;

Boolean! ValueOf(SemanticExpressionOperation[operator: ID] expr) :=
	1. *Assert:* `expr.children.count` is 2.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Let* `v1` be *Unwrap:* `ValueOf(expr.children.1)`.
	4. *Return:* `Identical(v0, v1)`.
;

Boolean! ValueOf(SemanticExpressionOperation[operator: EQ] expr) :=
	1. *Assert:* `expr.children.count` is 2.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Let* `v1` be *Unwrap:* `ValueOf(expr.children.1)`.
	4. *Return:* `Equal(v0, v1)`.
;

Object! ValueOf(SemanticExpressionOperation[operator: AND] expr) :=
	1. *Assert:* `expr.children.count` is 2.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *If* *UnwrapAffirm:* `ToBoolean(v0)` is `false`:
		1. *Return:* `v0`.
	4. *Return:* `ValueOf(expr.children.1)`.
;

Object! ValueOf(SemanticExpressionOperation[operator: OR] expr) :=
	1. *Assert:* `expr.children.count` is 2.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *If* *UnwrapAffirm:* `ToBoolean(v0)` is `true`:
		1. *Return:* `v0`.
	4. *Return:* `ValueOf(expr.children.1)`.
;

Object! ValueOf(SemanticExpressionOperation[operator: COND] expr) :=
	1. *Assert:* `expr.children.count` is 3.
	2. *Let* `v0` be *Unwrap:* `ValueOf(expr.children.0)`.
	3. *Assert:* `v0` is an instance of `Boolean`.
	4. *If* `v0` is `true`:
		1. *Return:* `ValueOf(expr.children.1)`.
	5. *Else:*
		1. *Return:* `ValueOf(expr.children.2)`.
;
