None! VarCheck(Or<
	SemanticKey,
	SemanticPropertyType,
	SemanticProperty,
	SemanticCase,
	SemanticType,
	SemanticExpression,
	SemanticStatementExpression,
	SemanticStatementClaim,
	SemanticStatementConditional,
	SemanticGoal,
> list) :=
	1. *For each* `it` in `list.children`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(Or<SemanticTypeRecord, SemanticExpressionRecord, SemanticExpressionDict> assoc) :=
	1. *Note:* In keyed collection literals, all keys are var-checked before all values.
	2. *For each* `prop` in `assoc.children`:
		1. *Let* `key` be `prop.children.0`.
		2. *Perform:* *Unwrap:* `VarCheck(key)`.
		3. *If* `assoc.children` already contains a property `prop_dupe` such that `prop_dupe.children.0.id` is `key.id`:
			1. *Throw:* a new AssignmentErrorDuplicateKey.
	3. *For each* `prop` in `assoc.children`:
		1. *Peform:* *Unwrap:* `VarCheck(prop.children.1)`.
;



None! VarCheck(SemanticTypeAlias var) :=
	1. *Note:* Skip var-checking of `var` for now if source is "Object", as semantics is determined by syntax.
	2. *If* `var.source` is "Object":
		1. *Return.*
	3. *If* the validator’s symbol table does not contain a SymbolSchema `symbol` whose `id` is `var.id`:
		1. *Throw:* a new ReferenceErrorUndeclared.
	// TODO: Throw a ReferenceErrorDeadZone if the variable is declared further down in source.
	4. *If* `symbol` is an instance of `SymbolSchemaVar`:
		1. *Throw:* a new ReferenceErrorKind.
;



None! VarCheck(SemanticTypeCall call) :=
	1. *Note:* Skip var-checking of `call.children.0` for now, as semantics is determined by syntax.
	2. *If* `call.children.0.source` is not one of "List", "Dict", "Set", or "Map":
		1. *Throw:* a new SyntaxError.
	3. *For each* `it` in `call.children[1..]`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(SemanticExpressionVariable var) :=
	1. *If* the validator’s symbol table does not contain a SymbolSchema `symbol` whose `id` is `var.id`:
		1. *Throw:* a new ReferenceErrorUndeclared.
	// TODO: Throw a ReferenceErrorDeadZone if the variable is declared further down in source.
	2. *If* `symbol` is an instance of `SymbolSchemaType`:
		1. *Throw:* a new ReferenceErrorKind.
;



None! VarCheck(SemanticExpressionCall call) :=
	1. *Note:* Skip var-checking of `call.children.0` for now, as semantics is determined by syntax.
	2. *If* `call.children.0.source` is not one of "List", "Dict", "Set", or "Map":
		1. *Throw:* a new SyntaxError.
	3. *For each* `it` in `call.children[1..]`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(SemanticDeclarationType decl) :=
	1. *If* `decl.children.count` is 1:
		1. *Perform:* *Unwrap:* `VarCheck(decl.children.0)`.
	2. *Else:*
		1. *Assert:* `decl.children.count` is 2.
		2. *Perform:* *Unwrap:* `VarCheck(decl.children.1)`.
		3. *Let* `id` be `decl.children.0.id`.
		4. *If* the validator’s symbol table contains a SymbolSchema whose `id` is `var.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		5. *Let* `symbol` be a new SymbolSchemaType [
			id=        `id`,
			typevalue= `Anything`,
		].
		6. Add `symbol` as a record for `id` to the validator.
;



None! VarCheck(SemanticDeclarationVariable decl) :=
	1. *Let* `uninitialized` be `true`.
	2. *Let* `assignee` be an item `child` in `decl.children` such that `child` is a SemanticExpressionVariable.
	3. *Let* `typenode` be an item `child` in `decl.children` such that `child` is a SemanticType.
	4. *Let* `assigned` be an item `child` in `decl.children` such that `child` is a SemanticExpression.
	5. *If* `decl.writable` is `false`:
		1. *Assert:* `assigned` is not *none*.
		2. *Note:* We can make this assertion due to the language syntax.
	6. *Assert:* `typenode` is not *none*.
	7. *Perform:* *Unwrap:* `VarCheck(typenode)`.
	8. *If* `assigned` is not *none*:
		1. *Set* `uninitialized` to `false`.
		2. *Perform:* *Unwrap:* `VarCheck(assigned)`.
	9. *If* `assignee` is not *none*:
		1. *If* the validator’s symbol table contains a SymbolSchema whose `id` is `assignee.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		2. *Let* `symbol` be a new SymbolSchemaVar [
			id=              `assignee.id`,
			isWritable=      `decl.writable`,
			isUninitialized= `uninitialized`,
			type=            `Anything`,
			value=           *none*,
		].
		3. Add `symbol` as a record for `assignee.id` to the validator.
;



None! VarCheck(SemanticStatementRessignment assign) :=
	1. *For each* `it` in `assign`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
	2. *Assert:* `assign.children.count` is 2.
	3. *Let* `assignee` be `assign.children.0`.
	4. *If* `assignee` is a SemanticExpressionVariable:
		1. *Assert:* The validator’s symbol table contains a SymbolSchema `symbol` whose `id` is `assignee.id`.
		2. *Assert:* `symbol` is an instance of `SymbolSchemaVar`.
		3. *If* `symbol.isWritable` is `false`:
			1. *Throw:* a new AssignmentErrorReassignment.
;



None! VarCheck(SemanticStatementLoop stmt) :=
	1. *Let* `condition` be an item `child` in `stmt.children` such that `child` is a SemanticExpression.
	2. *Let* `block`     be an item `child` in `stmt.children` such that `child` is a SemanticBlock.
	3. *Assert:* `condition` is not *none*.
	4. *Assert:* `block`     is not *none*.
	5. *If* `stmt.doFirst` is `true`:
		1. *Perform:* *Unwrap:* `VarCheck(block)`.
		2. *Perform:* *Unwrap:* `VarCheck(condition)`.
	6. *Else:*
		1. *Perform:* *Unwrap:* `VarCheck(condition)`.
		2. *Perform:* *Unwrap:* `VarCheck(block)`.
;



None! VarCheck(SemanticStatementIteration stmt) :=
	1. *Let* `assignee` be an item `child` in `stmt.children` such that `child` is a SemanticExpressionVariable.
	2. *Let* `typenode` be an item `child` in `stmt.children` such that `child` is a SemanticType.
	3. *Let* `iterable` be an item `child` in `stmt.children` such that `child` is a SemanticExpression.
	4. *Let* `block`    be an item `child` in `stmt.children` such that `child` is a SemanticBlock.
	5. *Assert:* `typenode` is not *none*.
	6. *Perform:* *Unwrap:* `VarCheck(typenode)`.
	7. *Assert:* `iterable` is not *none*.
	8. *Perform:* *Unwrap:* `VarCheck(iterable)`.
	9. *Assert:* `block` is not *none*.
	10. *If* `assignee` is not *none*:
		1. *Let* `validator` be the validator of `block`.
		2. *If* `validator`’s symbol table contains a SymbolSchema whose `id` is `assignee.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		3. *Let* `symbol` be a new SymbolSchemaVar [
			id=              `assignee.id`,
			isWritable=      `false`,
			isUninitialized= `false`,
			type=            `Anything`,
			value=           *none*,
		].
		4. Add `symbol` as a record for `assignee.id` to `validator`.
	11. *Perform:* *Unwrap:* `VarCheck(block)`.
;
