None! VarCheck(Or<
	SemanticIndex,
	SemanticKey,
	SemanticItemType,
	SemanticPropertyType,
	SemanticProperty,
	SemanticCase,
	SemanticGoal,
	Difference<SemanticType, Or<SemanticTypeAlias, SemanticTypeCall, SemanticTypeFunction>>,
	Difference<SemanticExpression, Or<SemanticExpressionVariable, SemanticExpressionCall, SemanticExpressionFunction>>,
	SemanticStatementExpression,
	SemanticStatementClaim,
	SemanticStatementConditional,
	SemanticStatementBreak,
	SemanticStatementReturn,
> list) :=
	1. *For each* `it` in `list.children`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(SemanticParameterFunction param) :=
	1. *For each* `it` in `param.children`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
	2. *If* `param.id` is not *none*:
		1. *Let* `parent` be the parent node of `param`.
		2. *Assert:* `parent` is a SemanticExpressionFunction or a SemanticDeclarationFunction.
		3. *Let* `block` be `parent.children.-1`.
		4. *Assert:* `block` is a SemanticBlock.
		5. *Let* `validator` be the validator of `block`.
		6. *If* `validator`’s symbol table contains a SymbolSchema whose `id` is `param.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		7. *Else:*
			1. *Let* `symbol` be a new SymbolSchemaVar [
				id=              `param.id`,
				isWritable=      `param.writable`,
				isUninitialized= `false`, // TODO: with optional paramers: `param.uninitialized`
				type=            `Anything`,
			].
			2. Add `symbol` as a record for `param.id` to `validator`.
	3. *Else:*
		1. *Return.*
;



None! VarCheck(SemanticBlock block) :=
	1. *For each* `stmt` in `block.children`:
		1. *If* `stmt` is a SemanticDeclarationFunction:
			1. *If* `stmt.id` is not *none*:
				1. *If* the validator’s symbol table contains a SymbolSchema whose `id` is `stmt.id`:
					1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
				2. *Else:*
					1. *Let* `symbol` be a new SymbolSchemaFunc [
						id=   `stmt.id`,
						type= `Anything`,
					].
					2. Add `symbol` as a record for `stmt.id` to the validator.
			2. *Else:*
				1. Fall through.
		2. *Else:*
			1. Fall through.
	2. *For each* `stmt` in `block.children`:
		1. *Peform:* *Unwrap:* `VarCheck(stmt)`.
;



None! VarCheck(Or<SemanticTypeRecord, SemanticExpressionRecord, SemanticExpressionDict> assoc) :=
	1. *Note:* In keyed collection literals, all keys are var-checked before all values.
	2. *For each* `prop` in `assoc.children`:
		1. *Let* `key` be `prop.children.0`.
		2. *Perform:* *Unwrap:* `VarCheck(key)`.
		3. *If* `assoc.children` already contains a property `prop_dupe` such that `prop_dupe.children.0.id` is `key.id`:
			1. *Throw:* a new AssignmentErrorDuplicateKey.
	3. *For each* `child` in `assoc.children`:
		1. *Peform:* *Unwrap:* `VarCheck(child)`.
;



None! VarCheck(SemanticTypeAlias var) :=
	1. *Note:* Skip var-checking of `var` for now if source is "Object", as semantics is determined by syntax.
	2. *If* `var.source` is "Object":
		1. *Return.*
	3. *If* the validator’s symbol table does not contain a SymbolSchema `symbol` whose `id` is `var.id`:
		1. *Throw:* a new ReferenceErrorUndeclared.
	// TODO: Throw a ReferenceErrorDeadZone if the variable is declared further down in source.
	4. *If* `symbol` is not an instance of `SymbolSchemaType`:
		1. *Throw:* a new ReferenceErrorKind.
;



None! VarCheck(SemanticTypeCall call) :=
	1. *Note:* Skip var-checking of `call.children.0` for now, as semantics is determined by syntax.
	2. *If* `call.children.0.source` is not one of "List", "Dict", "Set", or "Map":
		1. *Throw:* a new SyntaxError.
	3. *For each* `it` in `call.children[1..]`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(SemanticTypeFunction fn) :=
	1. *Note:* In function types, all parameter labels are var-checked before all parameter types.
	2. *Let* `proptypes` be a filtering of `fn.children` for each `child` such that `child` is a SemanticPropertyType.
	3. *For each* `proptype` in `proptypes`:
		1. *Let* `key` be `proptype.children.0`.
		2. *Perform:* *Unwrap:* `VarCheck(key)`.
		3. *If* `proptypes` already contains a property `prop_dupe` such that `prop_dupe.children.0.id` is `key.id`:
			1. *Throw:* a new AssignmentErrorDuplicateKey.
	4. *For each* `child` in `fn.children`:
		1. *Peform:* *Unwrap:* `VarCheck(child)`.
;


None! VarCheck(SemanticExpressionVariable var) :=
	1. *If* the validator’s symbol table does not contain a SymbolSchema `symbol` whose `id` is `var.id`:
		1. *Throw:* a new ReferenceErrorUndeclared.
	// TODO: Throw a ReferenceErrorDeadZone if the variable is declared further down in source.
	2. *If* `symbol` is an instance of `SymbolSchemaType`:
		1. *Throw:* a new ReferenceErrorKind.
;



None! VarCheck(SemanticExpressionCall call) :=
	1. *Note:* Skip var-checking of `call.children.0` for now, as semantics is determined by syntax.
	2. *If* `call.children.0.source` is not one of "List", "Dict", "Set", or "Map":
		1. *Throw:* a new SyntaxError.
	3. *For each* `it` in `call.children[1..]`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(SemanticExpressionFunction fn) :=
	1. *Note:* In function expressions, all parameter labels are var-checked *after* all parameter types and default values. The block/return is var-checked last.
	2. *Let* `parameters` be a filtering of `fn.children` for each `child` such that `child` is a SemanticParameterFunction.
	3. *For each* `parameter` of `parameters`:
		1. *Perform:* *Unwrap:* `VarCheck(parameter)`.
	4. *Let* `named_params` be a filtering of `parameters` for each `parameter` such that `parameter.named` is `true`.
	5. *Let* `labels` be a new Sequence.
	6. *For each* `param` of `named_params`:
		1. *Let* `key` be an item `c` in `param` such that `c` is a SemanticKey.
		2. *If* `key` is not *none*:
			1. *Let* `label` be `key.id`.
		3. *Else:*
			1. *Assert* `param.id` is set.
			2. *Let* `label` be `param.id`.
		4. *If* `labels` already contains `label`:
			1. *Throw:* a new AssignmentErrorDuplicateKey.
		5. *Else:*
			1. Push `label` to `labels`.
	7. *Return:* `VarCheck(fn.children.-1)`.
;



None! VarCheck(SemanticDeclarationType decl) :=
	1. *Perform:* *Unwrap:* `VarCheck(decl.children.0)`.
	2. *If* the validator’s symbol table contains a SymbolSchema whose `id` is `decl.id`:
		1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
	3. *Else:*
		1. *Let* `symbol` be a new SymbolSchemaType [
			id=        `decl.id`,
			typevalue= `Anything`,
		].
		2. Add `symbol` as a record for `id` to the validator.
;



None! VarCheck(SemanticDeclarationVariable decl) :=
	1. *Let* `uninitialized` be `true`.
	2. *Let* `typenode` be an item `child` in `decl.children` such that `child` is a SemanticType.
	3. *Let* `assigned` be an item `child` in `decl.children` such that `child` is a SemanticExpression.
	4. *If* `decl.writable` is `false`:
		1. *Assert:* `assigned` is not *none*.
		2. *Note:* We can make this assertion due to the language syntax.
	5. *Else:*
		1. Fall through.
	6. *Assert:* `typenode` is not *none*.
	7. *Perform:* *Unwrap:* `VarCheck(typenode)`.
	8. *If* `assigned` is not *none*:
		1. *Set* `uninitialized` to `false`.
		2. *Perform:* *Unwrap:* `VarCheck(assigned)`.
	9. *Else:*
		1. Fall through.
	10. *If* `decl.id` is not *none*:
		1. *If* the validator’s symbol table contains a SymbolSchema whose `id` is `decl.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		2. *Else:*
			1. *Let* `symbol` be a new SymbolSchemaVar [
				id=              `decl.id`,
				isWritable=      `decl.writable`,
				isUninitialized= `uninitialized`,
				type=            `Anything`,
			].
			2. Add `symbol` as a record for `decl.id` to the validator.
	11. *Else:*
		1. *Return.*
;



None! VarCheck(SemanticDeclarationFunction fn) :=
	1. *Note:* In function declarations, all parameter labels are var-checked *after* all parameter types and default values. The block/return is var-checked last.
	2. *Let* `parameters` be a filtering of `fn.children` for each `child` such that `child` is a SemanticParameterFunction.
	3. *For each* `parameter` of `parameters`:
		1. *Perform:* *Unwrap:* `VarCheck(parameter)`.
	4. *Let* `named_params` be a filtering of `parameters` for each `parameter` such that `parameter.named` is `true`.
	5. *Let* `labels` be a new Sequence.
	5. *For each* `param` of `named_params`:
		1. *Let* `key` be an item `c` in `param` such that `c` is a SemanticKey.
		2. *If* `key` is not *none*:
			1. *Let* `label` be `key.id`.
		3. *Else:*
			1. *Assert* `param.id` is set.
			2. *Let* `label` be `param.id`.
		4. *If* `labels` already contains `label`:
			1. *Throw:* a new AssignmentErrorDuplicateKey.
		5. *Else:*
			1. Push `label` to `labels`.
	7. *Return:* `VarCheck(fn.children.-1)`.
;



None! VarCheck(SemanticStatementRessignment stmt) :=
	1. *For each* `it` in `stmt`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
	2. *Let* `assignee` be `stmt.children.0`.
	3. *If* `assignee` is a SemanticExpressionVariable:
		1. *Assert:* The validator’s symbol table contains a SymbolSchema `symbol` whose `id` is `assignee.id`.
		2. *Assert:* `symbol` is an instance of `SymbolSchemaVar`.
	4. *If* `stmt.children.count` is 2:
		1. *Note:* This is a `set` statement.
		2. *If* `symbol` is set:
			1. *If* `symbol.isWritable` is `false`:
				1. *Throw:* a new AssignmentErrorReassignment.
			2. *Else:*
				1. *Return.*
		3. *Else:*
			1. *Return.*
	5. *Else:*
		1. *Assert:* `stmt.children.count` is 1.
		2. *Note:* This is a `delete` statement.
		3. *If* `symbol` is set:
			1. *If* `symbol.isWritable` is `false` *or* `symbol.isUninitialized` is `false`:
				1. *Throw:* a new AssignmentErrorDeletion.
			2. *Else:*
				1. *Return.*
		4. *Else:*
			1. *Return.*
;



None! VarCheck(SemanticStatementLoop stmt) :=
	1. *Let* `condition` be an item `child` in `stmt.children` such that `child` is a SemanticExpression.
	2. *Let* `block`     be an item `child` in `stmt.children` such that `child` is a SemanticBlock.
	3. *Assert:* `condition` is not *none*.
	4. *Assert:* `block`     is not *none*.
	5. *If* `stmt.doFirst` is `true`:
		1. *Perform:* *Unwrap:* `VarCheck(block)`.
		2. *Perform:* *Unwrap:* `VarCheck(condition)`.
	6. *Else:*
		1. *Perform:* *Unwrap:* `VarCheck(condition)`.
		2. *Perform:* *Unwrap:* `VarCheck(block)`.
;



None! VarCheck(SemanticStatementIteration stmt) :=
	1. *Let* `typenode` be an item `child` in `stmt.children` such that `child` is a SemanticType.
	2. *Let* `iterable` be an item `child` in `stmt.children` such that `child` is a SemanticExpression.
	3. *Let* `block`    be an item `child` in `stmt.children` such that `child` is a SemanticBlock.
	4. *Assert:* `typenode` is not *none*.
	5. *Perform:* *Unwrap:* `VarCheck(typenode)`.
	6. *Assert:* `iterable` is not *none*.
	7. *Perform:* *Unwrap:* `VarCheck(iterable)`.
	8. *Assert:* `block` is not *none*.
	9. *If* `stmt.id` is not *none*:
		1. *Let* `validator` be the validator of `block`.
		2. *If* `validator`’s symbol table contains a SymbolSchema whose `id` is `stmt.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		3. *Else:*
			1. *Let* `symbol` be a new SymbolSchemaVar [
				id=              `stmt.id`,
				isWritable=      `false`,
				isUninitialized= `false`,
				type=            `Anything`,
			].
			2. Add `symbol` as a record for `stmt.id` to `validator`.
	10. *Else:*
		1. Fall through.
	11. *Perform:* *Unwrap:* `VarCheck(block)`.
;
