// IDENTIFIER      ::= [./lexicon.ebnf#Identifier];
// INTEGER         ::= [./lexicon.ebnf#Integer];
// FLOAT           ::= [./lexicon.ebnf#Float];
// STRING          ::= [./lexicon.ebnf#String];
// TEMPLATE_FULL   ::= [./lexicon.ebnf#TemplateFull];
// TEMPLATE_HEAD   ::= [./lexicon.ebnf#TemplateHead];
// TEMPLATE_MIDDLE ::= [./lexicon.ebnf#TempalteMiddle];
// TEMPLATE_TAIL   ::= [./lexicon.ebnf#TempalteTail];



KeywordType ::=
	| "nothing"
	| "bool"
	| "sym"
	| "int"
	| "float"
	| "str"
	| "anything"
;

KeywordValue ::=
	| "null"
	| "false"
	| "true"
;



Word ::=
	// operator
		| "mut"
		| "as"
		| "is"
		| "isnt"
		| "if"
		| "then"
		| "else"
	// storage
		| "type"
		| "let"
		| "claim"
		| "set"
		| "_"
		| "void"
	// modifier
		| "nominal"
		| "var"
	// control
		| "unless"
		| "while"
		| "until"
		| "for"
		| "of"
		| "do"
		| "break"
		| "continue"
	| IDENTIFIER
	| KeywordType
	| KeywordValue
;



PrimitiveLiteral ::=
	| INTEGER
	| FLOAT
	| STRING
	| KeywordValue
	| "@" Word
;



EntryType<Named, Optional>
	::= <Named+>(Word & <Optional->":") <Optional+>"?:" Type;

ItemsType ::=
	|                                                                  ","?  EntryType<-Named><+Optional>#   ","?
	| EntryType<-Named><-Optional>                                     ","  (EntryType<-Named><+Optional>#   ","?)?
	| EntryType<-Named><-Optional>? "," EntryType<-Named><-Optional># (","   EntryType<-Named><+Optional>#)? ","?
;

PropertiesType
	::= ","? EntryType<+Named><∓Optional># ","?;

PropertyAccessorType
	::= INTEGER | Word;

TypeGrouped       ::= "(" Type             ")";
TypeTupleLiteral  ::= "(" ItemsType?       ")";
TypeRecordLiteral ::= "(" PropertiesType   ")";
TypeListLiteral   ::= "[" Type             "]";
TypeDictLiteral   ::= "[" ":" Type         "]";
TypeSetLiteral    ::= "{" Type             "}";
TypeMapLiteral    ::= "{" Type "->" Type   "}";
GenericArguments  ::= "<"  ","? Type# ","? ">";

TypeUnit ::=
	| IDENTIFIER
	| KeywordType
	| PrimitiveLiteral
	| TypeGrouped
	| TypeTupleLiteral
	| TypeListLiteral
	| TypeRecordLiteral
	| TypeDictLiteral
	| TypeSetLiteral
	| TypeMapLiteral
;

TypeCompound ::=
	| TypeUnit
	| TypeCompound (
		| ("." | "?.") PropertyAccessorType
		|  "."         GenericArguments
	)
;

TypeUnarySymbol  ::= TypeCompound    | TypeUnarySymbol ("?" | "!");
TypeUnaryKeyword ::= TypeUnarySymbol | "mut" TypeUnaryKeyword;

TypeIntersection ::= (TypeIntersection "&")? TypeUnaryKeyword;
TypeUnion        ::= (TypeUnion        "|")? TypeIntersection;

Type ::=
	| TypeUnion
;



StringTemplate<Break> ::=
	| TEMPLATE_FULL
	| TEMPLATE_HEAD Expression<+Block><?Break>? (TEMPLATE_MIDDLE Expression<+Block><?Break>?)* TEMPLATE_TAIL
;

Items<Break> ::=
	| Expression<+Block><?Break>  ","
	| Expression<+Block><?Break>? "," Expression<+Block><?Break># ","?
;

Property <Break> ::= Word                       "="  Expression<+Block><?Break>;
Case     <Break> ::= Expression<+Block><?Break> "->" Expression<+Block><?Break>;

PropertyAccessor<Break>
	::= INTEGER | Word | "[" Expression<+Block><?Break> "]";

ExpressionGrouped <Break> ::= "("       Expression<+Block><?Break>         ")";
TupleLiteral      <Break> ::= "("       Items<?Break>?                     ")";
RecordLiteral     <Break> ::= "("  ","? Property<?Break>#           ","?   ")";
ListLiteral       <Break> ::= "[" (","? Expression<+Block><?Break># ","?)? "]";
DictLiteral       <Break> ::= "["  ","? Property<?Break>#           ","?   "]";
SetLiteral        <Break> ::= "{" (","? Expression<+Block><?Break># ","?)? "}";
MapLiteral        <Break> ::= "{"  ","? Case<?Break>#               ","?   "}";
FunctionArguments <Break> ::= "(" (","? Expression<+Block><?Break># ","?)? ")";

ExpressionUnit<Block, Break> ::=
	| IDENTIFIER
	| PrimitiveLiteral
	| StringTemplate    <?Break>
	| ExpressionGrouped <?Break>
	| TupleLiteral      <?Break>
	| RecordLiteral     <?Break>
	| ListLiteral       <?Break>
	| DictLiteral       <?Break>
	| SetLiteral        <?Break>
	| MapLiteral        <?Break>
	| <Block+>Block     <?Break>
;

ExpressionCompound<Block, Break> ::=
	| ExpressionUnit<?Block><?Break>
	| ExpressionCompound<?Block><?Break> (
		| ("." | "?." | "!.") PropertyAccessor<?Break>
		|  "."                GenericArguments? FunctionArguments<?Break>
	)
;

ExpressionUnarySymbol  <Block, Break> ::= ExpressionCompound    <?Block><?Break> | ("!" | "?" | "+" | "-") ExpressionUnarySymbol  <?Block><?Break>;
ExpressionUnaryKeyword <Block, Break> ::= ExpressionUnarySymbol <?Block><?Break> | ("int" | "float")       ExpressionUnaryKeyword <?Block><?Break>;

ExpressionCast<Block, Break> ::=
	| (ExpressionCast<?Block><?Break> ("as" | "as?" | "as!"))? ExpressionUnaryKeyword<?Block><?Break>
	|  ExpressionCast<?Block><?Break>  "as"                    "<" Type ">"
;

ExpressionExponential<Block, Break>
	::= ExpressionCast<?Block><?Break> ("^" ExpressionExponential<?Block><?Break>)?;

ExpressionMultiplicative <Block, Break> ::= (ExpressionMultiplicative <?Block><?Break> ("*" | "/" ))?                                            ExpressionExponential    <?Block><?Break>;
ExpressionAdditive       <Block, Break> ::= (ExpressionAdditive       <?Block><?Break> ("+" | "-" ))?                                            ExpressionMultiplicative <?Block><?Break>;
ExpressionComparative    <Block, Break> ::= (ExpressionComparative    <?Block><?Break> ("<" | ">" | "<=" | ">=" | "!<" | "!>" | "is" | "isnt"))? ExpressionAdditive       <?Block><?Break>;
ExpressionEquality       <Block, Break> ::= (ExpressionEquality       <?Block><?Break> ("===" | "!==" | "==" | "!="))?                           ExpressionComparative    <?Block><?Break>;
ExpressionConjunctive    <Block, Break> ::= (ExpressionConjunctive    <?Block><?Break> ("&&" | "!&"))?                                           ExpressionEquality       <?Block><?Break>;
ExpressionDisjunctive    <Block, Break> ::= (ExpressionDisjunctive    <?Block><?Break> ("||" | "!|"))?                                           ExpressionConjunctive    <?Block><?Break>;

ExpressionConditional<Break>
	::= "if" Expression<+Block><?Break> "then" Expression<-Block><?Break> "else" Expression<-Block><?Break>;

Expression<Block, Break> ::=
	| ExpressionDisjunctive<?Block><?Break>
	| ExpressionConditional<?Break>
;



StatementExpression<Break>
	::= Expression<+Block><?Break>? ";";

StatementConditional<Unless, Break> ::=
	& <Unless->"if" <Unless+>"unless" Expression<+Block><?Break>
	& "then" Block<?Break>
	& <Unless->(
		| ("else" Block<?Break>)? ";"
		| "else" StatementConditional<?Unless><?Break>
	)
	& <Unless+>";"
;

StatementLoop
	::= (("while" | "until") Expression<+Block><-Break> && "do" Block<+Break>) ";";

StatementIteration
	::= "for" ("_" | IDENTIFIER) ":" Type "of" Expression<+Block><-Break> "do" Block<+Break> ";";

StatementBreak
	::= ("break" | "continue") INTEGER? ";";

Statement<Break> ::=
	| StatementExpression<?Break>
	| StatementConditional<∓Unless><?Break>
	| StatementLoop
	| StatementIteration
	| <Break+>StatementBreak
	| Declaration<?Break>
;



Block<Break>
	::= "{" Statement<?Break>+ "}";



Assignee<Break> ::=
	| IDENTIFIER
	| ExpressionCompound<+Block><?Break> "." PropertyAccessor<?Break>
;



DeclarationType
	::= "type" ("_" | IDENTIFIER) "=" Type ";";

DeclarationVariable<Break> ::=
	| "let" "var"? ("_" | IDENTIFIER) ":"  Type "=" Expression<+Block><?Break> ";"
	| "let" "var"  ("_" | IDENTIFIER) "?:" Type                                ";"
;

DeclarationClaim        <Break> ::= "claim" Assignee<?Break> ":" Type                       ";";
DeclarationReassignment <Break> ::= "set"   Assignee<?Break> "=" Expression<+Block><?Break> ";";

Declaration<Break> ::=
	| DeclarationType
	| DeclarationVariable     <?Break>
	| DeclarationClaim        <?Break>
	| DeclarationReassignment <?Break>
;



Goal
	::= #x02 Block<-Break>? #x03;
