None! VarCheck(Or<
	SemanticKey,
	SemanticPropertyType,
	SemanticProperty,
	SemanticCase,
	SemanticType,
	SemanticExpression,
	SemanticStatementExpression,
	SemanticGoal,
> list) :=
	1. *For each* `it` in `list.children`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(Or<SemanticTypeRecord, SemanticRecord, SemanticDict> assoc) :=
	1. *Note:* In keyed collection literals, all keys are var-checked before all values.
	2. *For each* `prop` in `assoc.children`:
		1. *Let* `key` be `prop.children.0`.
		2. *Perform:* *Unwrap:* `VarCheck(key)`.
		3. *If* `assoc.children` already contains a property `prop_dupe` such that `prop_dupe.children.0.id` is `key.id`:
			1. *Throw:* a new AssignmentErrorDuplicateKey.
	3. *For each* `prop` in `assoc.children`:
		1. *Peform:* *Unwrap:* `VarCheck(prop.children.1)`.
;



None! VarCheck(SemanticTypeAlias var) :=
	1. *Note:* Skip var-checking of `var` for now if source is "Object", as semantics is determined by syntax.
	2. *If* `var.source` is "Object":
		1. *Return.*
	3. *If* the validator’s symbol table does not contain a SymbolSchema `symbol` whose `id` is `var.id`:
		1. *Throw:* a new ReferenceErrorUndeclared.
	// TODO: Throw a ReferenceErrorDeadZone if the variable is declared further down in source.
	4. *If* `symbol` is an instance of `SymbolSchemaVar`:
		1. *Throw:* a new ReferenceErrorKind.
;



None! VarCheck(SemanticTypeCall call) :=
	1. *Note:* Skip var-checking of `call.children.0` for now, as semantics is determined by syntax.
	2. *For each* `it` in `call.children[1..]`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(SemanticVariable var) :=
	1. *If* the validator’s symbol table does not contain a SymbolSchema `symbol` whose `id` is `var.id`:
		1. *Throw:* a new ReferenceErrorUndeclared.
	// TODO: Throw a ReferenceErrorDeadZone if the variable is declared further down in source.
	2. *If* `symbol` is an instance of `SymbolSchemaType`:
		1. *Throw:* a new ReferenceErrorKind.
;



None! VarCheck(SemanticCall call) :=
	1. *Note:* Skip var-checking of `call.children.0` for now, as semantics is determined by syntax.
	2. *For each* `it` in `call.children[1..]`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
;



None! VarCheck(SemanticDeclarationType decl) :=
	1. *If* `decl.children.count` is 1:
		1. *Perform:* *Unwrap:* `VarCheck(decl.children.0)`.
	2. *Else:*
		1. *Assert:* `decl.children.count` is 2.
		2. *Perform:* *Unwrap:* `VarCheck(decl.children.1)`.
		3. *Let* `id` be `decl.children.0.id`.
		4. *If* the validator’s symbol table contains a SymbolSchema whose `id` is `var.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		5. *Let* `symbol` be a new SymbolSchemaType [
			id=        `id`,
			typevalue= `Unknown`,
		].
		6. Add `symbol` as a record for `id` to the validator.
;



None! VarCheck(SemanticDeclarationVariable decl) :=
	1. *Let* `uninitialized` be `true`.
	2. *Let* `assignee` be an item `child` in `decl.children` such that `child` is a SemanticVariable.
	3. *Let* `typenode` be an item `child` in `decl.children` such that `child` is a SemanticType.
	4. *Let* `assigned` be an item `child` in `decl.children` such that `child` is a SemanticExpression.
	5. *If* `decl.unfixed` is `false`:
		1. *Assert:* `assigned` is not *none*.
		2. *Note:* We can make this assertion due to the language syntax.
	6. *Assert:* `typenode` is not *none*.
	7. *Perform:* *Unwrap:* `VarCheck(typenode)`.
	8. *If* `assigned` is not *none*:
		1. *Set* `uninitialized` to `false`.
		2. *Perform:* *Unwrap:* `VarCheck(assigned)`.
	9. *If* `assignee` is not *none*:
		1. *If* the validator’s symbol table contains a SymbolSchema whose `id` is `assignee.id`:
			1. *Throw:* a new AssignmentErrorDuplicateDeclaration.
		2. *Let* `symbol` be a new SymbolSchemaVar [
			id=            `assignee.id`,
			unfixed=       `decl.unfixed`,
			uninitialized= `uninitialized`,
			type=          `Unknown`,
			value=         *none*,
		].
		3. Add `symbol` as a record for `assignee.id` to the validator.
;



None! VarCheck(SemanticAssignment assignment) :=
	1. *For each* `it` in `assignment`:
		1. *Perform:* *Unwrap:* `VarCheck(it)`.
	2. *Assert:* `assignment.children.count` is 2.
	3. *Let* `assignee` be `assignment.children.0`.
	4. *If* `assignee` is a SemanticVariable:
		1. *Let* `id` be `assignee.id`.
		2. *Assert:* The validator contains a record for `id`.
		3. *Let* `info` be the record for `id` in the validator.
		4. *If* `info.unfixed` is `false`:
			1. *Throw:* a new AssignmentErrorReassignment.
;
